In [6]:
!pip install plt

Collecting plt
  Downloading plt-0.2.0-py3-none-any.whl.metadata (2.1 kB)
Collecting matplotlib (from plt)
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib->plt)
  Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib->plt)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib->plt)
  Using cached fonttools-4.65.0-cp314-cp314-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->plt)
  Using cached kiwisolver-1.5.1-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in D:\AgentCustomerSupport\.venv\Lib\site-packages (from matplotlib->plt) (2.5.3)
Requirement already satisfied: packaging>=20.0 in D:\AgentCustomerSupport\.venv\Lib\site-packages (from matplotlib->plt) (26.3)
Collecting pillow>=9 (from matplotlib->plt)
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib->plt)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in D:\AgentCustomerSupport\.venv\Lib\site-packages (from matplotlib->plt) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in D:\AgentCustomerSupport\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib->plt) (1.17.0)
Downloading plt-0.2.0-py3-none-any.whl (2.8 kB)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.5 MB 4.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.5 MB 3.9 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.5 MB 3.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.5 MB 2.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.5 MB 2.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.5 MB 1.6 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.5 MB 1.7 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.5 MB 1.7 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.5 MB 1.7 MB/s eta 0:00:05
   --------------- ------------------------ 3.7/9.5 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.5 MB 1.8 MB/s eta 0:00:03
   ---------------------- ----------------- 5.2/9.5 MB 1.9 MB/s eta 0:00:03
   ----------------------- ---------------- 5.5/9.5 MB 1.9 MB/s eta 0:00:03
   ----------------------- ---------------- 5.5/9.5 MB 1.9 MB/s eta 0:00:03
   ------------------------ --------------- 5.8/9.5 MB 1.7 MB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.5 MB 1.9 MB/s eta 0:00:02
   --------------------------------- ------ 7.9/9.5 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.5 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 1.3 MB/s  0:00:08
Downloading contourpy-1.4.0-cp314-cp314-win_amd64.whl (240 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.65.0-cp314-cp314-win_amd64.whl (2.5 MB)
Using cached kiwisolver-1.5.1-cp314-cp314-win_amd64.whl (72 kB)
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, plt

   ---------------------------------------- 0/8 [pyparsing]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   -------------------- ------------------- 4/8 [cycler]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ---------------------------------------- 8/8 [plt]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-12.3.0 plt-0.2.0 pyparsing-3.3.2

In [8]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_colwidth", 200)
pd.set_option("display.max_columns", None)

PROJECT_ROOT = Path.cwd().parent
RAW_FILE = PROJECT_ROOT / "data" / "raw" / "twcs.csv"

print("Project root:", PROJECT_ROOT)
print("Dataset:", RAW_FILE)
print("Exists:", RAW_FILE.exists())

Project root: d:\AgentCustomerSupport\hiver-sde-intern
Dataset: d:\AgentCustomerSupport\hiver-sde-intern\data\raw\twcs.csv
Exists: True

In [9]:
df_sample = pd.read_csv(
    RAW_FILE,
    nrows=100_000
)

print("Shape:", df_sample.shape)
df_sample.head()

Shape: (100000, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messages and no one is responding as usual,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [10]:
df_sample = pd.read_csv(
    RAW_FILE,
    nrows=100_000
)

print("Shape:", df_sample.shape)
df_sample.head()

Shape: (100000, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messages and no one is responding as usual,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [11]:
print(df_sample["inbound"].value_counts())

print("\nPercentages:")
print(
    df_sample["inbound"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

inbound
True     54948
False    45052
Name: count, dtype: int64

Percentages:
inbound
True     54.95
False    45.05
Name: proportion, dtype: float64

In [12]:
conversation_sample = df_sample[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text",
        "response_tweet_id",
        "in_response_to_tweet_id"
    ]
].head(30)

conversation_sample

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messages and no one is responding as usual,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0
5,6,sprintcare,False,Tue Oct 31 21:46:24 +0000 2017,"@115712 Can you please send us a private message, so that I can gain further details about your account?","5,7",8.0
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10",NaN
7,11,sprintcare,False,Tue Oct 31 22:10:35 +0000 2017,"@115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC",NaN,12.0
8,12,115713,True,Tue Oct 31 22:04:47 +0000 2017,@sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯,"11,13,14",15.0
9,15,sprintcare,False,Tue Oct 31 20:03:31 +0000 2017,"@115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further assist you. -AA",12,16.0
10,16,115713,True,Tue Oct 31 20:00:43 +0000 2017,@sprintcare Since I signed up with you....Since day 1,15,17.0
11,17,sprintcare,False,Tue Oct 31 19:59:13 +0000 2017,"@115713 H there! We'd definitely like to work with you on this, how long have you been experiencing this issue? -AA",16,18.0
12,18,115713,True,Tue Oct 31 19:56:01 +0000 2017,"@115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.",17,NaN
13,19,sprintcare,False,Tue Oct 31 22:10:10 +0000 2017,@115715 Please send me a private message so that I can send you the link to access your account. -FR,NaN,20.0
14,20,115715,True,Tue Oct 31 22:03:34 +0000 2017,"@115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK",19,NaN
15,21,Ask_Spectrum,False,Tue Oct 31 22:14:37 +0000 2017,@115716 What information is incorrect? ^JK,"22,23",24.0
16,22,115716,True,Tue Oct 31 22:16:48 +0000 2017,@Ask_Spectrum Would you like me to email you a copy of one since Spectrum is not updating your training?,25,21.0
17,25,Ask_Spectrum,False,Tue Oct 31 22:18:28 +0000 2017,"@115716 Our department is part of the corporate office. If you're particular area has gone to this format, we were unawa... https://t.co/P7XCmTzPQj",26,22.0
18,26,115716,True,Tue Oct 31 22:19:56 +0000 2017,@Ask_Spectrum I received this from your corporate office would you like a copy?,27,25.0
19,27,Ask_Spectrum,False,Tue Oct 31 22:21:26 +0000 2017,@115716 No thank you. ^JK,NaN,26.0
20,23,115716,True,Tue Oct 31 22:16:05 +0000 2017,@Ask_Spectrum The correct way to do it is via an OCS Account Takeover and email Consent Form it does not need to be done in a local office,NaN,21.0
21,24,115716,True,Tue Oct 31 22:13:02 +0000 2017,@Ask_Spectrum That is INCORRECT information I have the form in front of me that is faxed over-maybe you need to maintain up to date information,21,28.0
22,28,Ask_Spectrum,False,Tue Oct 31 22:05:37 +0000 2017,@115716 The information pertaining to the account assumption is correct. This does need to be done at a local outlet wit... https://t.co/P7XCmTzPQj,24,29.0
23,29,115716,True,Tue Oct 31 22:01:35 +0000 2017,actually that's a broken link you sent me and incorrect information https://t.co/V4yfrHR8VI,28,NaN
24,30,Ask_Spectrum,False,Tue Oct 31 22:12:09 +0000 2017,"@115717 Hello, My apologies for any frustrations or inconvenience. I’d be happy to look into this for you? ^MG",NaN,31.0
25,31,115717,True,Tue Oct 31 22:06:54 +0000 2017,"Yo @Ask_Spectrum, your customer service reps are super nice— but imma start trippin if y’all don’t get my service going!",30,NaN
26,32,Ask_Spectrum,False,Tue Oct 31 22:10:08 +0000 2017,@115718 I apologize for the inconvenience. I will be glad to assist you. Can you DM me your Name and acct # or phone #? -JB,NaN,33.0
27,33,115718,True,Tue Oct 31 22:06:56 +0000 2017,My picture on @Ask_Spectrum pretty much every day. Why should I pay $171 per month? https://t.co/U6ptkQa5Ik,32,NaN
28,34,VerizonSupport,False,Tue Oct 31 22:13:33 +0000 2017,@115719 Help has arrived! We are sorry to see that you are having trouble. How can we help?\n^HSB,35,36.0
29,35,115719,True,Tue Oct 31 22:49:16 +0000 2017,"@VerizonSupport I finally got someone that helped me, thanks!",37,34.0

In [13]:
apple_mentions = df_sample[
    df_sample["text"]
    .str.contains(
        "AppleSupport",
        case=False,
        na=False
    )
]

print("Tweets mentioning AppleSupport:")
print(len(apple_mentions))

apple_mentions[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text"
    ]
].head(30)

Tweets mentioning AppleSupport:
3020

,tweet_id,author_id,inbound,text
397,697,115854,True,@AppleSupport The newest update. I️ made sure to download it yesterday.
399,698,115854,True,@AppleSupport https://t.co/NV0yucs0lB
400,700,115854,True,@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
402,702,115855,True,@AppleSupport Tried resetting my settings .. restarting my phone .. all that
404,704,115855,True,@AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
406,707,115855,True,@AppleSupport I️ have an iPhone 7 Plus and yes I️ do
408,709,115855,True,@AppleSupport I️ need answers because it’s annoying 🙃
412,713,115856,True,@AppleSupport Just sent you all my DM
413,714,115856,True,"Hey @AppleSupport and anyone else who upgraded to ios11.1, are y’all having issues with capital “I️” in the Mail app? As it puts in “A”?"
415,717,115857,True,@AppleSupport This is what is happening... https://t.co/X3SZSJXfAT
419,721,115859,True,@AppleSupport are the call centres closed for the night?
421,723,115859,True,@115858 @AppleSupport hello are all the lines closed for tonight #help
423,725,115860,True,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.
424,727,115861,True,@115862 @AppleSupport I will!
425,728,115862,True,@AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!
427,730,115861,True,"Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7"
429,733,115863,True,@AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?
431,735,115864,True,@AppleSupport I have the iPhone 6s Plus and just did the most recent update.
433,736,115864,True,Thank you @AppleSupport I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.😤
435,739,115865,True,@AppleSupport iOS 11.0.3
437,742,115865,True,@AppleSupport Okey. Thank you! 🤗
439,740,115865,True,@AppleSupport iPhone 7 Plus 😊
441,745,115865,True,@AppleSupport I need the software update urgently. The battery lasts literally half a day 🙍🏼🙁@AppleSupport
443,747,115865,True,Hola @AppleSupport necesito urgente la actualización de software. La batería me dura literal medio día 🙍🏼🙇🏼‍♀️
445,749,115866,True,@AppleSupport Hi! What is going on? Has Youtube lost it? What can be done about it? Thanks for the support! https://t.co/T8ZZp4IH6t
447,751,115867,True,@AppleSupport ? hello
448,752,115867,True,"@AppleSupport my Apple TV works fine with my phone, but when playing videos on Mac air it stutters so much &amp; sound is still on Mac not tv?"
450,754,115868,True,"@AppleSupport Yes it did, 11.0.3"
452,756,115868,True,MY HOME BUTTON DOESN’T WORK #IOS11 @AppleSupport
456,760,115870,True,@AppleSupport I can not find an option to get it there. It was just always there when playing.

In [14]:
apple_mentions = df_sample[
    df_sample["text"]
    .str.contains(
        "AppleSupport",
        case=False,
        na=False
    )
]

print("Tweets mentioning AppleSupport:")
print(len(apple_mentions))

apple_mentions[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text"
    ]
].head(30)

Tweets mentioning AppleSupport:
3020

,tweet_id,author_id,inbound,text
397,697,115854,True,@AppleSupport The newest update. I️ made sure to download it yesterday.
399,698,115854,True,@AppleSupport https://t.co/NV0yucs0lB
400,700,115854,True,@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
402,702,115855,True,@AppleSupport Tried resetting my settings .. restarting my phone .. all that
404,704,115855,True,@AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
406,707,115855,True,@AppleSupport I️ have an iPhone 7 Plus and yes I️ do
408,709,115855,True,@AppleSupport I️ need answers because it’s annoying 🙃
412,713,115856,True,@AppleSupport Just sent you all my DM
413,714,115856,True,"Hey @AppleSupport and anyone else who upgraded to ios11.1, are y’all having issues with capital “I️” in the Mail app? As it puts in “A”?"
415,717,115857,True,@AppleSupport This is what is happening... https://t.co/X3SZSJXfAT
419,721,115859,True,@AppleSupport are the call centres closed for the night?
421,723,115859,True,@115858 @AppleSupport hello are all the lines closed for tonight #help
423,725,115860,True,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.
424,727,115861,True,@115862 @AppleSupport I will!
425,728,115862,True,@AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!
427,730,115861,True,"Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7"
429,733,115863,True,@AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?
431,735,115864,True,@AppleSupport I have the iPhone 6s Plus and just did the most recent update.
433,736,115864,True,Thank you @AppleSupport I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.😤
435,739,115865,True,@AppleSupport iOS 11.0.3
437,742,115865,True,@AppleSupport Okey. Thank you! 🤗
439,740,115865,True,@AppleSupport iPhone 7 Plus 😊
441,745,115865,True,@AppleSupport I need the software update urgently. The battery lasts literally half a day 🙍🏼🙁@AppleSupport
443,747,115865,True,Hola @AppleSupport necesito urgente la actualización de software. La batería me dura literal medio día 🙍🏼🙇🏼‍♀️
445,749,115866,True,@AppleSupport Hi! What is going on? Has Youtube lost it? What can be done about it? Thanks for the support! https://t.co/T8ZZp4IH6t
447,751,115867,True,@AppleSupport ? hello
448,752,115867,True,"@AppleSupport my Apple TV works fine with my phone, but when playing videos on Mac air it stutters so much &amp; sound is still on Mac not tv?"
450,754,115868,True,"@AppleSupport Yes it did, 11.0.3"
452,756,115868,True,MY HOME BUTTON DOESN’T WORK #IOS11 @AppleSupport
456,760,115870,True,@AppleSupport I can not find an option to get it there. It was just always there when playing.

In [15]:
apple_related = df_sample[
    df_sample["text"].str.contains(
        "AppleSupport",
        case=False,
        na=False
    )
]

print("AppleSupport mentions:", len(apple_related))

print("\nInbound / outbound:")
print(apple_related["inbound"].value_counts())

outbound_apple_related = apple_related[
    apple_related["inbound"] == False
]

outbound_apple_related[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "in_response_to_tweet_id",
        "response_tweet_id"
    ]
].head(30)

AppleSupport mentions: 3020

Inbound / outbound:
inbound
True    3020
Name: count, dtype: int64

Empty DataFrame
Columns: [tweet_id, author_id, inbound, text, in_response_to_tweet_id, response_tweet_id]
Index: []

In [16]:
# Get customer tweets that mention AppleSupport
apple_customer_tweets = df_sample[
    (df_sample["inbound"] == True) &
    (df_sample["text"].str.contains("AppleSupport", case=False, na=False))
].copy()

print("Apple customer tweets:", len(apple_customer_tweets))

# Inspect response IDs
print("\nSample response_tweet_id values:")
print(
    apple_customer_tweets[
        ["tweet_id", "author_id", "text", "response_tweet_id"]
    ].head(20).to_string(index=False)
)

Apple customer tweets: 3020

Sample response_tweet_id values:
 tweet_id author_id                                                                                                                                                               text response_tweet_id
      697    115854                                                                                            @AppleSupport The newest update. I️ made sure to download it yesterday.               699
      698    115854                                                                                                                             @AppleSupport  https://t.co/NV0yucs0lB               696
      700    115854                                       @AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE               698
      702    115855                                                                                       @AppleSupport Tried resetting my settings .. restarting my phone .. all that               701
      704    115855                                                                                                   @AppleSupport This is what it looks like https://t.co/XCQU2l4xUB               703
      707    115855                                                                                                               @AppleSupport I️ have an iPhone 7 Plus and yes I️ do               705
      709    115855                                                                                                              @AppleSupport I️ need answers because it’s annoying 🙃               708
      713    115856                                                                                                                              @AppleSupport Just sent you all my DM               NaN
      714    115856                           Hey @AppleSupport and anyone else who upgraded to ios11.1, are y’all having issues with capital “I️” in the Mail app? As it puts in “A”?           712,715
      717    115857                                                                                                 @AppleSupport This is what is happening... https://t.co/X3SZSJXfAT               716
      721    115859                                                                                                           @AppleSupport are the call centres closed for the night?               720
      723    115859                                                                                             @115858 @AppleSupport hello are all the lines closed for tonight #help               722
      725    115860                                                                                                        @115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.           724,726
      727    115861                                                                                                                                      @115862 @AppleSupport I will!               725
      728    115862                                                                    @AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!               727
      730    115861 Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7           729,731
      733    115863                                @AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?               732
      735    115864                                                                                       @AppleSupport I have the iPhone 6s Plus and just did the most recent update.               737
      736    115864                                            Thank you @AppleSupport I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.😤               734
      739    115865                                                                                                                                           @AppleSupport iOS 11.0.3               741

In [17]:
response_ids = (
    apple_customer_tweets["response_tweet_id"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
)

print("Total response IDs:", len(response_ids))
print("Unique response IDs:", response_ids.nunique())

print("\nFirst 30 response IDs:")
print(response_ids.head(30).tolist())

Total response IDs: 3487
Unique response IDs: 3487

First 30 response IDs:
['699', '696', '698', '701', '703', '705', '708', '712', '715', '716', '720', '722', '724', '726', '725', '727', '729', '731', '732', '737', '734', '741', '743', '738', '744', '746', '748', '750', '751', '753']

In [18]:
response_id_set = set(response_ids)

linked_responses = df_sample[
    df_sample["tweet_id"].astype(str).isin(response_id_set)
].copy()

print("Responses found inside first 100k rows:", len(linked_responses))

linked_responses[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "in_response_to_tweet_id",
        "response_tweet_id"
    ]
].head(30)

Responses found inside first 100k rows: 2738

,tweet_id,author_id,inbound,text,in_response_to_tweet_id,response_tweet_id
396,696,AppleSupport,False,@115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.,698.0,697
398,699,AppleSupport,False,@115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT,697.0,NaN
399,698,115854,True,@AppleSupport https://t.co/NV0yucs0lB,700.0,696
401,701,AppleSupport,False,@115855 Let's go to DM for the next steps. DM us here: https://t.co/GDrqU22YpT,702.0,NaN
403,703,AppleSupport,False,@115855 Any steps tried since it started last night?,704.0,702
405,705,AppleSupport,False,@115855 That's great it has iOS 11.1 as we can rule out being outdated. Any steps tried since this started? Do you recall when it started?,707.0,"706,704"
407,708,AppleSupport,False,@115855 We'd like to look into this with you. Which model do you have and is iOS 11.1 installed? Any steps tried so far?,709.0,707
411,712,AppleSupport,False,"@115856 Hey, let's work together to figure out what's going on. Meet us in DM and we'll continue from there. https://t.co/GDrqU22YpT",714.0,713
414,716,AppleSupport,False,@115857 We'd like to investigate further with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT,717.0,NaN
418,720,AppleSupport,False,@115859 We've received your DM and will continue there.,721.0,NaN
420,722,AppleSupport,False,@115859 What's going on? We're hapy to help if we can. https://t.co/GDrqU22YpT,723.0,721
422,724,AppleSupport,False,"@115860 Reach out to us via DM, and we can take a look at this with you. https://t.co/GDrqU22YpT",725.0,NaN
423,725,115860,True,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.,727.0,"724,726"
424,727,115861,True,@115862 @AppleSupport I will!,728.0,725
426,729,AppleSupport,False,"@115861 You're in the right place; we'll do all we can to help. To start, let us know what iOS version is installed via DM: https://t.co/GDrqU22YpT",730.0,728
428,732,AppleSupport,False,@115863 Go ahead and send us a DM please. Let us know the country you're in.,733.0,NaN
430,734,AppleSupport,False,"@115864 We'd like to help, but we'll need more details. What's happening on your device and which model is it? Do you have iOS 11.1?",736.0,735
432,737,AppleSupport,False,"@115864 To make sure, is iOS 11.1 installed on it currently? Also, any steps tried so far? DM us here: https://t.co/GDrqU22YpT",735.0,NaN
434,738,AppleSupport,False,@115865 Thanks! Which iOS version is currently showing in Settings &gt; General &gt; About?,740.0,739
436,741,AppleSupport,False,"@115865 Let's check Settings &gt; General &gt; Software Update. iOS 11.1 was released earlier today. If you see it, please backup &amp; update.",739.0,742
438,743,AppleSupport,False,"@115865 Our pleasure. If you're still having issues after a back up and update, contact us back. We're happy to help.",742.0,NaN
440,744,AppleSupport,False,@115865 Hi there! What type of device are we working with?,745.0,740
442,746,AppleSupport,False,@115865 We offer support via Twitter in English. Get help in Spanish here: https://t.co/IBIY3vMgPj or join https://t.co/OczyRx7IOs,747.0,745
444,748,AppleSupport,False,@115866 We want to help! DM us and let us know more about the issues you are having. https://t.co/GDrqU22YpT,749.0,NaN
446,750,AppleSupport,False,@115867 We'd like to get you speaking to our experts here: https://t.co/IBIY3vMgPj,751.0,NaN
447,751,115867,True,@AppleSupport ? hello,752.0,750
449,753,AppleSupport,False,"@115868 We've just released iOS 11.1. We suggest backing up &amp; updating. Then, test the issue again. Here's how: https://t.co/80YRnjDFDk",754.0,NaN
451,755,AppleSupport,False,@115868 Let us help with your Home button. Did this issue start right after iOS 11? Which version of iOS 11 are you running?,756.0,754
455,759,AppleSupport,False,@115870 DM us the specific iOS version you are running currently and we'll continue there. https://t.co/GDrqU22YpT,760.0,NaN
457,761,AppleSupport,False,"@115870 Just to confirm, this is only happening with Spotify, correct?",763.0,"760,762"

In [19]:
# Convert response_tweet_id into individual tweet IDs

response_ids = (
    apple_customer_tweets["response_tweet_id"]
    .dropna()
    .astype(str)
    .str.split(",")
    .explode()
    .str.strip()
)

response_ids = response_ids[
    response_ids != ""
]

print("Total response links:", len(response_ids))
print("Unique response tweet IDs:", response_ids.nunique())

print("\nSample:")
print(response_ids.head(30).tolist())

Total response links: 3487
Unique response tweet IDs: 3487

Sample:
['699', '696', '698', '701', '703', '705', '708', '712', '715', '716', '720', '722', '724', '726', '725', '727', '729', '731', '732', '737', '734', '741', '743', '738', '744', '746', '748', '750', '751', '753']

In [20]:
linked_tweets = df_sample[
    df_sample["tweet_id"].astype(str).isin(set(response_ids))
].copy()

print("Linked tweets found:", len(linked_tweets))

linked_tweets[
    [
        "tweet_id",
        "author_id",
        "inbound",
        "text",
        "in_response_to_tweet_id",
        "response_tweet_id"
    ]
].head(50)

Linked tweets found: 2738

,tweet_id,author_id,inbound,text,in_response_to_tweet_id,response_tweet_id
396,696,AppleSupport,False,@115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.,698.0,697
398,699,AppleSupport,False,@115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT,697.0,NaN
399,698,115854,True,@AppleSupport https://t.co/NV0yucs0lB,700.0,696
401,701,AppleSupport,False,@115855 Let's go to DM for the next steps. DM us here: https://t.co/GDrqU22YpT,702.0,NaN
403,703,AppleSupport,False,@115855 Any steps tried since it started last night?,704.0,702
405,705,AppleSupport,False,@115855 That's great it has iOS 11.1 as we can rule out being outdated. Any steps tried since this started? Do you recall when it started?,707.0,"706,704"
407,708,AppleSupport,False,@115855 We'd like to look into this with you. Which model do you have and is iOS 11.1 installed? Any steps tried so far?,709.0,707
411,712,AppleSupport,False,"@115856 Hey, let's work together to figure out what's going on. Meet us in DM and we'll continue from there. https://t.co/GDrqU22YpT",714.0,713
414,716,AppleSupport,False,@115857 We'd like to investigate further with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT,717.0,NaN
418,720,AppleSupport,False,@115859 We've received your DM and will continue there.,721.0,NaN
420,722,AppleSupport,False,@115859 What's going on? We're hapy to help if we can. https://t.co/GDrqU22YpT,723.0,721
422,724,AppleSupport,False,"@115860 Reach out to us via DM, and we can take a look at this with you. https://t.co/GDrqU22YpT",725.0,NaN
423,725,115860,True,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.,727.0,"724,726"
424,727,115861,True,@115862 @AppleSupport I will!,728.0,725
426,729,AppleSupport,False,"@115861 You're in the right place; we'll do all we can to help. To start, let us know what iOS version is installed via DM: https://t.co/GDrqU22YpT",730.0,728
428,732,AppleSupport,False,@115863 Go ahead and send us a DM please. Let us know the country you're in.,733.0,NaN
430,734,AppleSupport,False,"@115864 We'd like to help, but we'll need more details. What's happening on your device and which model is it? Do you have iOS 11.1?",736.0,735
432,737,AppleSupport,False,"@115864 To make sure, is iOS 11.1 installed on it currently? Also, any steps tried so far? DM us here: https://t.co/GDrqU22YpT",735.0,NaN
434,738,AppleSupport,False,@115865 Thanks! Which iOS version is currently showing in Settings &gt; General &gt; About?,740.0,739
436,741,AppleSupport,False,"@115865 Let's check Settings &gt; General &gt; Software Update. iOS 11.1 was released earlier today. If you see it, please backup &amp; update.",739.0,742
438,743,AppleSupport,False,"@115865 Our pleasure. If you're still having issues after a back up and update, contact us back. We're happy to help.",742.0,NaN
440,744,AppleSupport,False,@115865 Hi there! What type of device are we working with?,745.0,740
442,746,AppleSupport,False,@115865 We offer support via Twitter in English. Get help in Spanish here: https://t.co/IBIY3vMgPj or join https://t.co/OczyRx7IOs,747.0,745
444,748,AppleSupport,False,@115866 We want to help! DM us and let us know more about the issues you are having. https://t.co/GDrqU22YpT,749.0,NaN
446,750,AppleSupport,False,@115867 We'd like to get you speaking to our experts here: https://t.co/IBIY3vMgPj,751.0,NaN
447,751,115867,True,@AppleSupport ? hello,752.0,750
449,753,AppleSupport,False,"@115868 We've just released iOS 11.1. We suggest backing up &amp; updating. Then, test the issue again. Here's how: https://t.co/80YRnjDFDk",754.0,NaN
451,755,AppleSupport,False,@115868 Let us help with your Home button. Did this issue start right after iOS 11? Which version of iOS 11 are you running?,756.0,754
455,759,AppleSupport,False,@115870 DM us the specific iOS version you are running currently and we'll continue there. https://t.co/GDrqU22YpT,760.0,NaN
457,761,AppleSupport,False,"@115870 Just to confirm, this is only happening with Spotify, correct?",763.0,"760,762"
459,764,AppleSupport,False,@115870 Thanks for reaching out to us. Are you experiencing the missing app after restating your device?,765.0,763
1166,1756,AppleSupport,False,@116098 Let's dig into this further with you. DM us and we'll continue there.,1757.0,NaN
1168,1758,AppleSupport,False,"@116098 We definitely understand your concern. Please backup your iPhone, update and let us know the result: https://t.co/ahjigcvFRG",1759.0,1757
1172,1762,AppleSupport,False,@116100 This article should help with that: https://t.co/usOJWy6ChP,1764.0,1763
1174,1765,AppleSupport,False,@116100 Try contacting our iTunes Store team here for more help: https://t.co/SDIe7UiyJN,1763.0,1766
1177,1767,AppleSupport,False,@116101 Thanks for clarifying. Let's meet in DM so we can do more in-depth on this. https://t.co/GDrqU22YpT,1768.0,NaN
1179,1769,AppleSupport,False,@116101 We're happy to help. Has Home Sharing worked with these devices before?,1770.0,1768
1181,1771,AppleSupport,False,@116102 Which model do you have and is iOS 11.1 installed on it? Any steps tried so far?,1773.0,1772
1183,1774,AppleSupport,False,"@116102 To make sure, is iOS 11.1 showing here: Settings &gt; General &gt; About &gt; Version? Please DM us the answer here: https://t.co/GDrqU22YpT",1772.0,"1775,1776"
1185,1777,AppleSupport,False,"@116103 We'll make sure to get this straightened out. DM us, and we'll see you there. https://t.co/GDrqU22YpT",1775.0,NaN
1190,1780,AppleSupport,False,@116104 Let us look into that. What device and OS version are you using?,1781.0,NaN
1194,1784,AppleSupport,False,@116106 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj,1785.0,NaN
1196,1786,AppleSupport,False,@116107 Glad to hear and just reach out again if you need help. Have a good one!,1787.0,NaN
1198,1788,AppleSupport,False,@116107 Please keep us posted afterwards.,1789.0,1787
1200,1790,AppleSupport,False,@116107 Apps are important and we want you to get back to enjoying them. Which model do you have? Is iOS 11.1 installed on it?,1791.0,1789
1886,2609,AppleSupport,False,@116332 Let us know and we'll continue from there. https://t.co/GDrqU22YpT,2610.0,NaN
1888,2611,AppleSupport,False,@116332 We'd like to see what we can do to assist. What version of iOS are you currently running? We released iOS 11.1 today.,2613.0,"2610,2612"
1890,2614,AppleSupport,False,"@116334 Let’s work together on this situation. To clarify, did this start after updating to iOS 11.1? Also, which device are you using?",2616.0,2615
1892,2617,AppleSupport,False,@116334 Got it. Does this happen while using any particular App or feature? Let us know via a DM. We’ll keep moving forward from there. https://t.co/GDrqU22YpT,2615.0,NaN
1894,2618,AppleSupport,False,@116335 You should still be able to control Music on your iPhone from the watch. Check out the user guide here: https://t.co/vRQnmrhVHj,2620.0,2619

In [21]:
apple_responses = linked_tweets[
    (linked_tweets["author_id"] == "AppleSupport") &
    (linked_tweets["inbound"] == False)
].copy()

print("AppleSupport responses found:", len(apple_responses))

print("\nUnique AppleSupport tweets:")
print(apple_responses["tweet_id"].nunique())

print("\nSample responses:")
display(
    apple_responses[
        [
            "tweet_id",
            "text",
            "in_response_to_tweet_id",
            "response_tweet_id"
        ]
    ].head(20)
)

AppleSupport responses found: 2501

Unique AppleSupport tweets:
2501

Sample responses:

,tweet_id,text,in_response_to_tweet_id,response_tweet_id
396,696,@115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.,698.0,697
398,699,@115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT,697.0,NaN
401,701,@115855 Let's go to DM for the next steps. DM us here: https://t.co/GDrqU22YpT,702.0,NaN
403,703,@115855 Any steps tried since it started last night?,704.0,702
405,705,@115855 That's great it has iOS 11.1 as we can rule out being outdated. Any steps tried since this started? Do you recall when it started?,707.0,"706,704"
407,708,@115855 We'd like to look into this with you. Which model do you have and is iOS 11.1 installed? Any steps tried so far?,709.0,707
411,712,"@115856 Hey, let's work together to figure out what's going on. Meet us in DM and we'll continue from there. https://t.co/GDrqU22YpT",714.0,713
414,716,@115857 We'd like to investigate further with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT,717.0,NaN
418,720,@115859 We've received your DM and will continue there.,721.0,NaN
420,722,@115859 What's going on? We're hapy to help if we can. https://t.co/GDrqU22YpT,723.0,721
422,724,"@115860 Reach out to us via DM, and we can take a look at this with you. https://t.co/GDrqU22YpT",725.0,NaN
426,729,"@115861 You're in the right place; we'll do all we can to help. To start, let us know what iOS version is installed via DM: https://t.co/GDrqU22YpT",730.0,728
428,732,@115863 Go ahead and send us a DM please. Let us know the country you're in.,733.0,NaN
430,734,"@115864 We'd like to help, but we'll need more details. What's happening on your device and which model is it? Do you have iOS 11.1?",736.0,735
432,737,"@115864 To make sure, is iOS 11.1 installed on it currently? Also, any steps tried so far? DM us here: https://t.co/GDrqU22YpT",735.0,NaN
434,738,@115865 Thanks! Which iOS version is currently showing in Settings &gt; General &gt; About?,740.0,739
436,741,"@115865 Let's check Settings &gt; General &gt; Software Update. iOS 11.1 was released earlier today. If you see it, please backup &amp; update.",739.0,742
438,743,"@115865 Our pleasure. If you're still having issues after a back up and update, contact us back. We're happy to help.",742.0,NaN
440,744,@115865 Hi there! What type of device are we working with?,745.0,740
442,746,@115865 We offer support via Twitter in English. Get help in Spanish here: https://t.co/IBIY3vMgPj or join https://t.co/OczyRx7IOs,747.0,745

In [22]:
dm_keywords = [
    "dm",
    "direct message",
    "message us",
    "send us a message",
    "join us",
    "continue there",
]

apple_response_text = (
    apple_responses["text"]
    .fillna("")
    .str.lower()
)

dm_mask = apple_response_text.str.contains(
    "|".join(dm_keywords),
    regex=True,
    na=False
)

print("AppleSupport responses:", len(apple_responses))
print("DM / routing responses:", dm_mask.sum())

print(
    f"DM / routing percentage: "
    f"{dm_mask.mean() * 100:.2f}%"
)

AppleSupport responses: 2501
DM / routing responses: 1206
DM / routing percentage: 48.22%

In [23]:
display(
    apple_responses.loc[
        dm_mask,
        ["tweet_id", "text"]
    ].head(20)
)

,tweet_id,text
398,699,@115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT
401,701,@115855 Let's go to DM for the next steps. DM us here: https://t.co/GDrqU22YpT
411,712,"@115856 Hey, let's work together to figure out what's going on. Meet us in DM and we'll continue from there. https://t.co/GDrqU22YpT"
414,716,@115857 We'd like to investigate further with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT
418,720,@115859 We've received your DM and will continue there.
422,724,"@115860 Reach out to us via DM, and we can take a look at this with you. https://t.co/GDrqU22YpT"
426,729,"@115861 You're in the right place; we'll do all we can to help. To start, let us know what iOS version is installed via DM: https://t.co/GDrqU22YpT"
428,732,@115863 Go ahead and send us a DM please. Let us know the country you're in.
432,737,"@115864 To make sure, is iOS 11.1 installed on it currently? Also, any steps tried so far? DM us here: https://t.co/GDrqU22YpT"
444,748,@115866 We want to help! DM us and let us know more about the issues you are having. https://t.co/GDrqU22YpT
455,759,@115870 DM us the specific iOS version you are running currently and we'll continue there. https://t.co/GDrqU22YpT
1166,1756,@116098 Let's dig into this further with you. DM us and we'll continue there.
1177,1767,@116101 Thanks for clarifying. Let's meet in DM so we can do more in-depth on this. https://t.co/GDrqU22YpT
1183,1774,"@116102 To make sure, is iOS 11.1 showing here: Settings &gt; General &gt; About &gt; Version? Please DM us the answer here: https://t.co/GDrqU22YpT"
1185,1777,"@116103 We'll make sure to get this straightened out. DM us, and we'll see you there. https://t.co/GDrqU22YpT"
1892,2617,@116334 Got it. Does this happen while using any particular App or feature? Let us know via a DM. We’ll keep moving forward from there. https://t.co/GDrqU22YpT
1896,2621,@116335 We certainly want to take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT
1903,2629,@116337 Please meet with us in DM. We'd like to gather some additional details from you. https://t.co/GDrqU22YpT
1907,2633,"@116338 Thank you very much! Send us a DM to let us know if your speaker doesn't work on calls, or if other apps are affected as well. https://t.co/GDrqU22YpT"
1913,2639,@116340 We certainly want to take a closer look into this. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT

In [24]:
action_keywords = [
    "update",
    "backup",
    "restart",
    "settings",
    "check",
    "install",
    "turn off",
    "turn on",
    "reset",
    "contact",
    "try",
    "select",
]

action_mask = apple_response_text.str.contains(
    "|".join(action_keywords),
    regex=True,
    na=False
)

print("Responses containing troubleshooting/action language:")
print(action_mask.sum())

print(
    f"Percentage: "
    f"{action_mask.mean() * 100:.2f}%"
)

Responses containing troubleshooting/action language:
918
Percentage: 36.71%

In [25]:
display(
    apple_responses.loc[
        action_mask,
        ["tweet_id", "text"]
    ].head(30)
)

,tweet_id,text
396,696,@115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.
398,699,@115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT
407,708,@115855 We'd like to look into this with you. Which model do you have and is iOS 11.1 installed? Any steps tried so far?
426,729,"@115861 You're in the right place; we'll do all we can to help. To start, let us know what iOS version is installed via DM: https://t.co/GDrqU22YpT"
428,732,@115863 Go ahead and send us a DM please. Let us know the country you're in.
432,737,"@115864 To make sure, is iOS 11.1 installed on it currently? Also, any steps tried so far? DM us here: https://t.co/GDrqU22YpT"
434,738,@115865 Thanks! Which iOS version is currently showing in Settings &gt; General &gt; About?
436,741,"@115865 Let's check Settings &gt; General &gt; Software Update. iOS 11.1 was released earlier today. If you see it, please backup &amp; update."
438,743,"@115865 Our pleasure. If you're still having issues after a back up and update, contact us back. We're happy to help."
1168,1758,"@116098 We definitely understand your concern. Please backup your iPhone, update and let us know the result: https://t.co/ahjigcvFRG"
1174,1765,@116100 Try contacting our iTunes Store team here for more help: https://t.co/SDIe7UiyJN
1181,1771,@116102 Which model do you have and is iOS 11.1 installed on it? Any steps tried so far?
1183,1774,"@116102 To make sure, is iOS 11.1 showing here: Settings &gt; General &gt; About &gt; Version? Please DM us the answer here: https://t.co/GDrqU22YpT"
1194,1784,@116106 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj
1200,1790,@116107 Apps are important and we want you to get back to enjoying them. Which model do you have? Is iOS 11.1 installed on it?
1894,2618,@116335 You should still be able to control Music on your iPhone from the watch. Check out the user guide here: https://t.co/vRQnmrhVHj
1896,2621,@116335 We certainly want to take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT
1905,2630,@116338 We're here to help out! Which device is this on and which version of iOS is currently installed?
1913,2639,@116340 We certainly want to take a closer look into this. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT
1916,2641,@116341 Thanks for reaching out. DM which Bluetooth device you are trying to connect to so we can help. https://t.co/GDrqU22YpT
1928,2653,"@116345 Since we just released iOS 11.1 today, can you clarify which exact version you have installed?"
1953,2681,"@116351 We'd love to help with your alarm volume. Is the option to ""Change with Buttons"" disabled under Settings &gt; Sounds?"
2833,3762,@116621 Let's look at this together. Are you updated to iOS 11.1?
2835,3765,@116621 It was released earlier today. Let's use these steps to update iOS: \n https://t.co/80YRnjDFDk
2839,3768,@116623 Thank you for reaching out to us. Have you tried to restart the device? Let us know to get started.
2847,3778,@116625 Thanks for the update. Go ahead and send us a DM and we'll take it from there. https://t.co/GDrqU22YpT
3590,4878,@116855 We want to help. Does restarting help at all? DM us which iOS version you're on and we'll continue support there. https://t.co/GDrqU22YpT
3592,4880,@116856 We're here for you. What is the exact version of the iOS you're running? Check by tapping Settings &gt; General &gt; About.
3594,4883,@116856 Are all of your apps updated as well?
3609,4898,@116859 Does that continue after restarting your iPhone? Do you have any other iOS devices or a Mac computer? Let us know in DM. https://t.co/GDrqU22YpT

In [26]:
customer_text = apple_customer_tweets["text"].fillna("")

print("Customer tweets:", len(customer_text))

print("\nAverage characters:")
print(customer_text.str.len().mean())

print("\nMedian characters:")
print(customer_text.str.len().median())

print("\nVery short messages:")
display(
    apple_customer_tweets[
        customer_text.str.len() < 20
    ][
        ["tweet_id", "author_id", "text"]
    ].head(30)
)

Customer tweets: 3020

Average characters:
109.11291390728476

Median characters:
105.0

Very short messages:

       tweet_id author_id                 text
1938       2665    116348    @AppleSupport Yes
1942       2670    116349  @AppleSupport I did
3595       4884    116856     @AppleSupport It
4326       5810    117097     @AppleSupport No
8022      11632    118243    @AppleSupport Yes
8356      11990    118358   @AppleSupport 11.1
8879      12568    118508     @AppleSupport 11
8891      12580    118511   @AppleSupport 11.0
9467      13200    118713   @AppleSupport Sent
11825     15721    119461  @AppleSupport Okay.
24774     31407    122925   @AppleSupport 11.1
24829     31468    122940  @AppleSupport Ok 👌🏻
25204     31879    123042     @AppleSupport 6S
25676     32407    123183   @AppleSupport 11.1
25702     32435    123193   @AppleSupport 11.1
26875     34593    123494  @2154 @AppleSupport
26948     34672    123519   @AppleSupport 11.1
28121     36043    123833     @AppleSupport 😅👍
28651     36621    123976   @AppleSupport 11.1
30159     38647    124422   @AppleSupport Both
30353     38864    124480    @AppleSupport Yes
30374     38884    124484  @AppleSupport Sent!
31763     40503    124883   @AppleSupport Done
32693     41688    125176   @AppleSupport 11.1
32697     41691    125177  @AppleSupport Thank
33550     42617    125418   @AppleSupport 11.1
34194     43349    125608   @AppleSupport Yes.
35796     45572    126090   @AppleSupport 11.1
39741     50070    127212      @AppleSupport 😰
41020     51622    127589   @AppleSupport 11.1

In [27]:
print("Empty/very short:", (customer_text.str.len() < 10).sum())

print("URLs:", customer_text.str.contains(r"http\S+", regex=True).sum())

print("Questions:", customer_text.str.contains(r"\?", regex=True).sum())

print("Mentions:", customer_text.str.contains("@", regex=False).sum())

print("Hashtags:", customer_text.str.contains("#", regex=False).sum())

Empty/very short: 0
URLs: 476
Questions: 834
Mentions: 3020
Hashtags: 165

In [28]:
# ============================================
# DATA CLEANING - STEP 1
# Inspect noisy customer messages
# ============================================

customer_text = apple_customer_tweets["text"].fillna("").astype(str)

noise_patterns = {
    "urls": r"http\S+|www\.\S+",
    "mentions": r"@\w+",
    "hashtags": r"#\w+",
    "questions": r"\?",
    "emoji": r"[^\x00-\x7F]",
}

for name, pattern in noise_patterns.items():
    mask = customer_text.str.contains(
        pattern,
        regex=True,
        na=False
    )

    print(f"{name}: {mask.sum()} ({mask.mean() * 100:.2f}%)")

urls: 476 (15.76%)
mentions: 3020 (100.00%)
hashtags: 165 (5.46%)
questions: 834 (27.62%)
emoji: 1249 (41.36%)

In [29]:
# Tweets containing URLs
print("=== URL EXAMPLES ===")
display(
    apple_customer_tweets[
        apple_customer_tweets["text"]
        .str.contains(r"http\S+|www\.\S+", regex=True, na=False)
    ][["tweet_id", "text"]]
    .head(20)
)

=== URL EXAMPLES ===

,tweet_id,text
399,698,@AppleSupport https://t.co/NV0yucs0lB
400,700,@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
404,704,@AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
415,717,@AppleSupport This is what is happening... https://t.co/X3SZSJXfAT
427,730,"Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7"
445,749,@AppleSupport Hi! What is going on? Has Youtube lost it? What can be done about it? Thanks for the support! https://t.co/T8ZZp4IH6t
1167,1757,@AppleSupport I️ just updated it and it’s still coming up https://t.co/22RZsQyTbh
1169,1759,Why is “I️” keep changing to this and how do I️ stop it🤦🏽‍♀️ @115858 @AppleSupport #anybody https://t.co/urzAfSZL5z
1889,2613,"Cupertino, we have a problem. .@115858 .@116333 .@AppleSupport .@190 https://t.co/ImMcJ8QsTM"
1946,2674,@AppleSupport See how it says searching at the top instead of giving me signal?.....I’ve been dealing with that for 2 weeks and sprint did everything https://t.co/iB0NsSeL1G
1950,2678,"@AppleSupport Any idea why icons show up like this? I did force reset to no avail. After initial notification display, they show up. https://t.co/qBFIAlpGyD"
2842,3770,@AppleSupport this is my top bar every time I open messages on my SE after updating to iOS 11.1 https://t.co/Lzge3qzc7w
2844,3773,@AppleSupport iOS 11.1 - keyboard lag. 🤨 https://t.co/TdIHT9L9dt
3587,4875,Come on @AppleSupport #ios11.1 Same bug as before. Numbers disappear when entering info. Video below. #iosproblems https://t.co/eKirAn2Mam
3591,4879,@AppleSupport I can’t download songs. Progress icon keeps spinning. On both data + WiFi. Stream works though. Can’t add songs to playlists. https://t.co/x7uUxSqO9u
3603,4890,"@AppleSupport whenever I try to see the photos that I’ve just taken my #iphone6 shows me this. I’ve reset it, I’ve restored it... help? https://t.co/8tQy27WvMe"
3610,4896,@AppleSupport please make this stop!!! https://t.co/YoyrO8iZKe
3618,4906,@AppleSupport The ‘Overlapping url over TIME on Free WiFi hotspots’ remains. v11.0.3. Not a WiFi problem; two different hotspots shown. https://t.co/81ifcrDUeS
3620,4909,コレは本当に困る、ゲームも出来なくなったしアップデートしなきゃ良かった´д` ;\n@AppleSupport @115858 → 「バッテリーの減りが激しい」という問題に関しても同様）。 https://t.co/bGQly6cE2O
4352,5837,@AppleSupport Yes. Sorry. I️ just watched a video about 11.2 beta. 11.1 When I️ type the letter Eye I️ happens https://t.co/bUBElgADue

In [30]:
# Tweets containing mentions
print("=== MENTION EXAMPLES ===")
display(
    apple_customer_tweets[
        apple_customer_tweets["text"]
        .str.contains(r"@\w+", regex=True, na=False)
    ][["tweet_id", "text"]]
    .head(20)
)

=== MENTION EXAMPLES ===

,tweet_id,text
397,697,@AppleSupport The newest update. I️ made sure to download it yesterday.
399,698,@AppleSupport https://t.co/NV0yucs0lB
400,700,@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
402,702,@AppleSupport Tried resetting my settings .. restarting my phone .. all that
404,704,@AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
406,707,@AppleSupport I️ have an iPhone 7 Plus and yes I️ do
408,709,@AppleSupport I️ need answers because it’s annoying 🙃
412,713,@AppleSupport Just sent you all my DM
413,714,"Hey @AppleSupport and anyone else who upgraded to ios11.1, are y’all having issues with capital “I️” in the Mail app? As it puts in “A”?"
415,717,@AppleSupport This is what is happening... https://t.co/X3SZSJXfAT
419,721,@AppleSupport are the call centres closed for the night?
421,723,@115858 @AppleSupport hello are all the lines closed for tonight #help
423,725,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.
424,727,@115862 @AppleSupport I will!
425,728,@AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!
427,730,"Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7"
429,733,@AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?
431,735,@AppleSupport I have the iPhone 6s Plus and just did the most recent update.
433,736,Thank you @AppleSupport I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.😤
435,739,@AppleSupport iOS 11.0.3

In [31]:
# Tweets containing non-ASCII characters / emojis
print("=== EMOJI / NON-ASCII EXAMPLES ===")
display(
    apple_customer_tweets[
        apple_customer_tweets["text"]
        .str.contains(r"[^\x00-\x7F]", regex=True, na=False)
    ][["tweet_id", "text"]]
    .head(30)
)

=== EMOJI / NON-ASCII EXAMPLES ===

,tweet_id,text
397,697,@AppleSupport The newest update. I️ made sure to download it yesterday.
400,700,@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
406,707,@AppleSupport I️ have an iPhone 7 Plus and yes I️ do
408,709,@AppleSupport I️ need answers because it’s annoying 🙃
413,714,"Hey @AppleSupport and anyone else who upgraded to ios11.1, are y’all having issues with capital “I️” in the Mail app? As it puts in “A”?"
423,725,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.
425,728,@AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!
427,730,"Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7"
429,733,@AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?
433,736,Thank you @AppleSupport I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.😤
437,742,@AppleSupport Okey. Thank you! 🤗
439,740,@AppleSupport iPhone 7 Plus 😊
441,745,@AppleSupport I need the software update urgently. The battery lasts literally half a day 🙍🏼🙁@AppleSupport
443,747,Hola @AppleSupport necesito urgente la actualización de software. La batería me dura literal medio día 🙍🏼🙇🏼‍♀️
452,756,MY HOME BUTTON DOESN’T WORK #IOS11 @AppleSupport
1167,1757,@AppleSupport I️ just updated it and it’s still coming up https://t.co/22RZsQyTbh
1169,1759,Why is “I️” keep changing to this and how do I️ stop it🤦🏽‍♀️ @115858 @AppleSupport #anybody https://t.co/urzAfSZL5z
1178,1768,"@AppleSupport it has, but not for some time now. i’ve tried with two different apple ids but it’s still not showing up on my phone"
1182,1772,"@AppleSupport iPhone 6, yes ios11. Checked for updates, none available. I’ve swiped up to close the app several times and I’ve restarted it 2x"
1186,1776,@AppleSupport Sent twice. Don’t know if the first one went through but no reply either way.
1191,1781,@AppleSupport why can’t I change ringer volume with the buttons? Whose dumb idea was it to change that and how do they still have a job?
1195,1785,@AppleSupport epıl bana yardımcı olur musun telefon internet konusunda çok yakıyo napcaz ?
1197,1787,@AppleSupport Worked 👌🏽
1201,1791,why won’t my apps fuccin download or update @AppleSupport
1887,2610,@AppleSupport $100 billion says that solves my problem? I’m on 11.0.3 currently. Hold please.
1893,2616,"@AppleSupport why is my battery life short? I updated to 11.1, my battery is poor. Wife didn’t she likes her battery life"
1897,2620,@AppleSupport watchOs4 made my watch pointless Browsing music on my phone via the watch was 80% reason for buying it now it’s useless.
1902,2627,@AppleSupport iOS 11.1 it’s been getting worse for a few months now
1932,2612,"@AppleSupport While I️ have u,as imessaging has become so impersonal &amp; frequent, when will you implement italics/bold etc 2 give more context to message?"
1936,2662,So why is this happening I️ I️ I️ @AppleSupport

In [32]:
routing_keywords = [
    "dm",
    "direct message",
    "message me",
    "send me a message",
    "follow me",
    "follow back",
    "check your dm",
    "check dm",
    "inbox",
]

routing_pattern = "|".join(routing_keywords)

routing_mask = customer_text.str.contains(
    routing_pattern,
    case=False,
    regex=True,
    na=False
)

print("Potential routing messages:", routing_mask.sum())

display(
    apple_customer_tweets.loc[
        routing_mask,
        ["tweet_id", "text"]
    ].head(50)
)

Potential routing messages: 77

,tweet_id,text
412,713,@AppleSupport Just sent you all my DM
5496,8297,@AppleSupport Hello there i need help with the use of an administartors name and password on my imac
5501,8302,Every time I watch a live broadcast or video it skips or repeats a few seconds since updating @AppleSupport https://t.co/ufl7yqidmb
6199,9180,"@AppleSupport I bought an iTunes gift card worth £15 a week ago, and the email still hasn’t come into my inbox to tell me the code. Helpppp"
7613,11139,@AppleSupport I get prompted for a system administrator password on a MBP MacOS but there is no system administrator account I’m aware of!! https://t.co/M1DbEkDzaS
8373,12008,@AppleSupport So I sent you a DM and didn’t get a response. Are you actually willing to help or just trying to take it offline? Software upgrade was done
9826,13590,Tudo bom ??? Todos estão com o mesmo problema e é sempre com o iPhone 7 o que está acontecendo??? @115858 @AppleSupport https://t.co/pn1UYIjdMo
11583,15469,@AppleSupport ...sent DM
17842,23079,"@AppleSupport Thank you for the prompt reply. I appreciate it, and have DM'd."
17857,23096,@AppleSupport sent you a dm. Thanks
17864,23102,@AppleSupport The developper of Videoshop has been able to reproduce the bug and said it is a problem with iOS 11 and he can’t do anything about that problem. Sorry but... what is DM? (I’m sorry i...
20701,26716,@AppleSupport I hit up your DMs
25276,31954,"@AppleSupport everytime I go into social media I cannot DM anyone photos, not on twitter or Facebook. I have over 7k photos here it’s says 0 https://t.co/x2U9OUvota"
26908,34629,@123506 @AppleSupport I think it’s about time Apple admit that iOS 11 has an inherent battery related issue!
27540,35306,"@AppleSupport Sorry, I don’t know what is DM? Can u please help me out."
27544,35310,@AppleSupport DM’ed you
27549,35316,@AppleSupport please check your DMs
28096,36015,@AppleSupport I have dropped in a DM to you guys.
28106,36025,@AppleSupport Can you DM me please? Am really stuck!! x
28141,36069,@AppleSupport Its been an Hour can you please check the DMs
28157,36086,@AppleSupport DM sent
28661,36631,@AppleSupport I just sent a dm about an accident on iTunes I need help removing the payment please.
29772,38234,"@AppleSupport If you don’t follow me we cannot DM. I’ve said this preciously, but you wont follow. So this is just talk."
30154,38643,@AppleSupport sent DM just waiting on reply.
30367,38876,@AppleSupport Location details sent in DM !
30369,38879,@AppleSupport Responded back with the relevant details on the DM. Please have a look.
31019,39650,@AppleSupport @124677 Hi need help please see the DM
31768,40506,@124884 @AppleSupport Beth you may want to DM
31814,40547,@AppleSupport Problem solved - information for the masses. If you are confused contact me on DM.
32673,41666,@AppleSupport hi can someone Dm plz
34162,43314,@125598 @AppleSupport Good lmfao I’m about to DM them right now
35791,45568,"@AppleSupport I sent it to DM, look at it."
35824,45604,"@AppleSupport Sorry, what is DM?"
38923,49198,"@AppleSupport I DM’d yesterday. unable to update the repair as there was no information. I have now been informed my watch is being returned, broken."
39703,50031,@AppleSupport DM sent
40479,50880,@AppleSupport https://t.co/NAmOVlIDMr
41048,51652,@127597 @AppleSupport Apple sliding into your dms
41071,51674,@AppleSupport I’ll dm you if there’s any problem after i update it
41678,52326,@AppleSupport You guys have already messaged me in a DM about this and had me do this. It didn’t work. Literally 3 times you’ve recommended this.
42847,53574,@AppleSupport @128108 Lol apple finna slide in yo dm
42857,53584,@AppleSupport Same response as the image I sent. Can I DM my email for you guys to check? Thanks a lot! :)
42879,53605,@AppleSupport You just gonna ignore my dm 🤔
42884,53610,@AppleSupport I sent a DM
44962,55949,@AppleSupport @128690 It goes down in the DMs
45702,56948,"@AppleSupport Why do you only reply to new issues, immediately move them to DM, then ignore them?"
47414,58823,"@AppleSupport DM'ing, now!"
49355,61078,@AppleSupport check your DMs!
49611,61346,@AppleSupport Just Dm You
51222,63169,@AppleSupport need you to check your DM’s. 😩😩😩
53234,65657,@AppleSupport what do you mean by DM ?

In [35]:
import re
import html
import unicodedata

In [36]:
def clean_customer_text(text):
    """
    Conservative cleaning for AppleSupport customer tweets.

    Keeps:
    - technical terms
    - numbers
    - product names
    - error messages
    - hashtags as words

    Removes:
    - URLs
    - @mentions
    - emojis
    - unnecessary Unicode artifacts
    - excessive whitespace
    """

    if pd.isna(text):
        return ""

    text = str(text)

    # ----------------------------------------
    # 1. Decode HTML entities
    # ----------------------------------------
    text = html.unescape(text)

    # ----------------------------------------
    # 2. Remove URLs
    # ----------------------------------------
    text = re.sub(
        r"https?://\S+|www\.\S+",
        " ",
        text
    )

    # ----------------------------------------
    # 3. Remove @mentions
    # ----------------------------------------
    text = re.sub(
        r"@\w+",
        " ",
        text
    )

    # ----------------------------------------
    # 4. Keep hashtag word, remove '#'
    # ----------------------------------------
    text = re.sub(
        r"#(\w+)",
        r"\1",
        text
    )

    # ----------------------------------------
    # 5. Unicode normalization
    # ----------------------------------------
    text = unicodedata.normalize(
        "NFKC",
        text
    )

    # ----------------------------------------
    # 6. Remove variation selectors
    #    and zero-width characters
    # ----------------------------------------
    text = re.sub(
        r"[\u200b-\u200f\u202a-\u202e\ufeff\ufe0e\ufe0f]",
        "",
        text
    )

    # ----------------------------------------
    # 7. Remove emojis / symbols
    #
    # Keep normal letters, numbers and
    # punctuation.
    # ----------------------------------------
    cleaned_chars = []

    for char in text:
        category = unicodedata.category(char)

        if category.startswith("So"):
            continue

        if category.startswith("Sk"):
            continue

        cleaned_chars.append(char)

    text = "".join(cleaned_chars)

    # ----------------------------------------
    # 8. Normalize repeated whitespace
    # ----------------------------------------
    text = re.sub(
        r"\s+",
        " ",
        text
    )

    # ----------------------------------------
    # 9. Strip whitespace
    # ----------------------------------------
    text = text.strip()

    return text

In [37]:
test_examples = [
    "@AppleSupport iOS 11.1 - keyboard lag. 🤨 https://t.co/test",
    "@AppleSupport 😭 my fucking iPhone is sooo slow!!!",
    "@AppleSupport MY HOME BUTTON DOESN'T WORK #IOS11",
    "@AppleSupport DM sent",
    "@AppleSupport I sent a DM about an accident on iTunes I need help removing the payment",
]

for text in test_examples:
    print("RAW   :", text)
    print("CLEAN :", clean_customer_text(text))
    print("-" * 80)

RAW   : @AppleSupport iOS 11.1 - keyboard lag. 🤨 https://t.co/test
CLEAN : iOS 11.1 - keyboard lag.
--------------------------------------------------------------------------------
RAW   : @AppleSupport 😭 my fucking iPhone is sooo slow!!!
CLEAN : my fucking iPhone is sooo slow!!!
--------------------------------------------------------------------------------
RAW   : @AppleSupport MY HOME BUTTON DOESN'T WORK #IOS11
CLEAN : MY HOME BUTTON DOESN'T WORK IOS11
--------------------------------------------------------------------------------
RAW   : @AppleSupport DM sent
CLEAN : DM sent
--------------------------------------------------------------------------------
RAW   : @AppleSupport I sent a DM about an accident on iTunes I need help removing the payment
CLEAN : I sent a DM about an accident on iTunes I need help removing the payment
--------------------------------------------------------------------------------

In [38]:
apple_customer_tweets["text_raw"] = (
    apple_customer_tweets["text"]
    .fillna("")
    .astype(str)
)

apple_customer_tweets["text_clean"] = (
    apple_customer_tweets["text_raw"]
    .apply(clean_customer_text)
)

In [39]:
display(
    apple_customer_tweets[
        ["tweet_id", "text_raw", "text_clean"]
    ].head(30)
)

,tweet_id,text_raw,text_clean
397,697,@AppleSupport The newest update. I️ made sure to download it yesterday.,The newest update. I made sure to download it yesterday.
399,698,@AppleSupport https://t.co/NV0yucs0lB,
400,700,@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE,why are my I’s changing not showing up correctly on any of my social media platforms?
402,702,@AppleSupport Tried resetting my settings .. restarting my phone .. all that,Tried resetting my settings .. restarting my phone .. all that
404,704,@AppleSupport This is what it looks like https://t.co/XCQU2l4xUB,This is what it looks like
406,707,@AppleSupport I️ have an iPhone 7 Plus and yes I️ do,I have an iPhone 7 Plus and yes I do
408,709,@AppleSupport I️ need answers because it’s annoying 🙃,I need answers because it’s annoying
412,713,@AppleSupport Just sent you all my DM,Just sent you all my DM
413,714,"Hey @AppleSupport and anyone else who upgraded to ios11.1, are y’all having issues with capital “I️” in the Mail app? As it puts in “A”?","Hey and anyone else who upgraded to ios11.1, are y’all having issues with capital “I” in the Mail app? As it puts in “A”?"
415,717,@AppleSupport This is what is happening... https://t.co/X3SZSJXfAT,This is what is happening...
419,721,@AppleSupport are the call centres closed for the night?,are the call centres closed for the night?
421,723,@115858 @AppleSupport hello are all the lines closed for tonight #help,hello are all the lines closed for tonight help
423,725,@115861 @115862 @AppleSupport I️ upgraded. I️t didn’t work.,I upgraded. It didn’t work.
424,727,@115862 @AppleSupport I will!,I will!
425,728,@AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!,We’re going to need you to share the answers Angela. I can’t stand this!
427,730,"Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I️ try to type the letter I️? Also @AppleSupport https://t.co/QKwvTLtiN7","Hello, internet. Can someone explain why this symbol keeps appearing on my phone and when I try to type the letter I? Also"
429,733,@AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?,I’ve got a screenshot saying my iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?
431,735,@AppleSupport I have the iPhone 6s Plus and just did the most recent update.,I have the iPhone 6s Plus and just did the most recent update.
433,736,Thank you @AppleSupport I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.😤,Thank you I updated my phone and now it is even slower and barely works. Thank you for ruining my phone.
435,739,@AppleSupport iOS 11.0.3,iOS 11.0.3
437,742,@AppleSupport Okey. Thank you! 🤗,Okey. Thank you!
439,740,@AppleSupport iPhone 7 Plus 😊,iPhone 7 Plus
441,745,@AppleSupport I need the software update urgently. The battery lasts literally half a day 🙍🏼🙁@AppleSupport,I need the software update urgently. The battery lasts literally half a day
443,747,Hola @AppleSupport necesito urgente la actualización de software. La batería me dura literal medio día 🙍🏼🙇🏼‍♀️,Hola necesito urgente la actualización de software. La batería me dura literal medio día
445,749,@AppleSupport Hi! What is going on? Has Youtube lost it? What can be done about it? Thanks for the support! https://t.co/T8ZZp4IH6t,Hi! What is going on? Has Youtube lost it? What can be done about it? Thanks for the support!
447,751,@AppleSupport ? hello,? hello
448,752,"@AppleSupport my Apple TV works fine with my phone, but when playing videos on Mac air it stutters so much &amp; sound is still on Mac not tv?","my Apple TV works fine with my phone, but when playing videos on Mac air it stutters so much & sound is still on Mac not tv?"
450,754,"@AppleSupport Yes it did, 11.0.3","Yes it did, 11.0.3"
452,756,MY HOME BUTTON DOESN’T WORK #IOS11 @AppleSupport,MY HOME BUTTON DOESN’T WORK IOS11
456,760,@AppleSupport I can not find an option to get it there. It was just always there when playing.,I can not find an option to get it there. It was just always there when playing.

In [40]:
!pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     -------------------- ----------------- 524.3/981.5 kB 6.8 MB/s eta 0:00:01
     ---------------------------------------- 981.5/981.5 kB 2.2 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six in D:\AgentCustomerSupport\.venv\Lib\site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml): started
  Building wheel for langdetect (pyproject.toml): finished with status 'done'
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=1019155 sha256=cdb094463147ede5bda01edab5165316c4914f5b3312ff71ea477ea02c5b7e67
  Stored in directory: c:\users\shubhanshi gupta\appdata\local\pip\cache\wheels\13\60\5a\f2012969b3f7413b62b7b7063d6c9b45c93004a978cbe8ea2f
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [41]:
from langdetect import detect, DetectorFactory

# Make language detection deterministic
DetectorFactory.seed = 0

In [42]:
def detect_language(text):
    if pd.isna(text):
        return "unknown"

    text = str(text).strip()

    if len(text) < 10:
        return "unknown"

    try:
        return detect(text)
    except:
        return "unknown"

In [43]:
apple_customer_tweets["language"] = (
    apple_customer_tweets["text_clean"]
    .apply(detect_language)
)

In [45]:
language_counts = (
    apple_customer_tweets["language"]
    .value_counts()
)

display(language_counts)

language
en         2626
unknown     213
es           32
fr           23
pt           18
de           14
af           14
nl           14
cy            7
da            6
it            6
tl            6
tr            5
so            5
lt            4
ja            3
et            3
sv            3
no            3
hu            3
sl            2
ru            2
pl            2
ar            1
id            1
ca            1
hr            1
sw            1
lv            1
Name: count, dtype: int64

In [46]:
non_english = apple_customer_tweets[
    ~apple_customer_tweets["language"].isin(
        ["en", "unknown"]
    )
]

print("Non-English messages:", len(non_english))

display(
    non_english[
        ["tweet_id", "language", "text_raw", "text_clean"]
    ].head(50)
)

Non-English messages: 181

,tweet_id,language,text_raw,text_clean
435,739,de,@AppleSupport iOS 11.0.3,iOS 11.0.3
437,742,tr,@AppleSupport Okey. Thank you! 🤗,Okey. Thank you!
439,740,fr,@AppleSupport iPhone 7 Plus 😊,iPhone 7 Plus
443,747,es,Hola @AppleSupport necesito urgente la actualización de software. La batería me dura literal medio día 🙍🏼🙇🏼‍♀️,Hola necesito urgente la actualización de software. La batería me dura literal medio día
450,754,af,"@AppleSupport Yes it did, 11.0.3","Yes it did, 11.0.3"
1195,1785,tr,@AppleSupport epıl bana yardımcı olur musun telefon internet konusunda çok yakıyo napcaz ?,epıl bana yardımcı olur musun telefon internet konusunda çok yakıyo napcaz ?
2844,3773,so,@AppleSupport iOS 11.1 - keyboard lag. 🤨 https://t.co/TdIHT9L9dt,iOS 11.1 - keyboard lag.
3620,4909,ja,コレは本当に困る、ゲームも出来なくなったしアップデートしなきゃ良かった´д` ;\n@AppleSupport @115858 → 「バッテリーの減りが激しい」という問題に関しても同様）。 https://t.co/bGQly6cE2O,コレは本当に困る、ゲームも出来なくなったしアップデートしなきゃ良かった ́д ; → 「バッテリーの減りが激しい」という問題に関しても同様)。
4348,5833,fr,"sa fait 1h j’ai ios11.1 et mon tel redemarre seul, explication @AppleSupport ?????","sa fait 1h j’ai ios11.1 et mon tel redemarre seul, explication ?????"
5763,8570,da,"@115858 @AppleSupport FYI, Folders no longer show Folder Names after update unless folder highlighted. https://t.co/1iiNNz9ZFk","FYI, Folders no longer show Folder Names after update unless folder highlighted."
6190,9170,ja,11.1にあげたらTwitter少し見てるだけだし低電力モードなのに20パーへったぞ。デバイス本体ごと取り換えて数ヶ月だし今回のアプデはミスだな。バッテリー消費悪化してる。 @AppleSupport,11.1にあげたらTwitter少し見てるだけだし低電力モードなのに20パーへったぞ。デバイス本体ごと取り換えて数ヶ月だし今回のアプデはミスだな。バッテリー消費悪化してる。
6203,9184,da,@AppleSupport I️ have 11.0.3,I have 11.0.3
6703,9831,et,@applesupport please help us lmao https://t.co/EngGZoVACe,please help us lmao
6711,9840,es,"@AppleSupport mi iPhone no se puede conectar a la red wifi privadas pero si a las free, que hago 😢","mi iPhone no se puede conectar a la red wifi privadas pero si a las free, que hago"
6716,9843,pt,FOCO AQUI @AppleSupport Q Q TÁ ACONTECENDO ~ iOS 11 guloso https://t.co/Eonz2w9xPi,FOCO AQUI Q Q TÁ ACONTECENDO ~ iOS 11 guloso
7185,10679,pt,Depois da ultima atualizado do IOS a bateria do IPhone 6 tá durando quase nada @115858 @AppleSupport,Depois da ultima atualizado do IOS a bateria do IPhone 6 tá durando quase nada
7189,10683,es,@AppleSupport Baje la App de @701 la cual es gratuita y me llego un cargo de $18.11 Pesos ¿cuál es el motivo?,Baje la App de la cual es gratuita y me llego un cargo de $18.11 Pesos ¿cuál es el motivo?
7600,11127,es,@AppleSupport Open calendar... https://t.co/0WVfFpqX0k,Open calendar...
8901,12590,fr,@AppleSupport iPhone 7 Plus,iPhone 7 Plus
9469,13197,fr,Écran d’iPhone cassé. Impossible à connecter sur iTunes ... des astuces svp ? @AppleSupport,Écran d’iPhone cassé. Impossible à connecter sur iTunes ... des astuces svp ?
9471,13203,af,@AppleSupport my OTG adapter doesn't work on i8plus ios 11.1,my OTG adapter doesn't work on i8plus ios 11.1
9485,13217,nl,@118720 @118721 @AppleSupport Been having same issue,Been having same issue
9814,13578,sl,@AppleSupport Ohh got 11.2 beta 1 😸 https://t.co/iObpTCjQkp,Ohh got 11.2 beta 1
9817,13580,af,@115858 @AppleSupport buggie spotted https://t.co/uiuCiaj3Pl,buggie spotted
9826,13590,pt,Tudo bom ??? Todos estão com o mesmo problema e é sempre com o iPhone 7 o que está acontecendo??? @115858 @AppleSupport https://t.co/pn1UYIjdMo,Tudo bom ??? Todos estão com o mesmo problema e é sempre com o iPhone 7 o que está acontecendo???
10159,13591,pt,"@118837 @115858 @AppleSupport @118936 O meu está acontecendo a mesma coisa, já redefini a senha e nada","O meu está acontecendo a mesma coisa, já redefini a senha e nada"
10520,14334,de,.@AppleSupport @115858 WHY DOES THIS KEEP HAPPENING😭 https://t.co/7v4aCGW3lO,. WHY DOES THIS KEEP HAPPENING
11583,15469,nl,@AppleSupport ...sent DM,...sent DM
11823,15719,es,Actualize a iOS 11.1 y sobrecalienta el equipo @1048 @119459 @119460 @AppleSupport,Actualize a iOS 11.1 y sobrecalienta el equipo
16276,21137,de,@AppleSupport Version 11.11 (15B150),Version 11.11 (15B150)
17889,23132,de,@AppleSupport iOS 11.1.2,iOS 11.1.2
24791,31426,af,@AppleSupport iOS11 I’ve tried resetting the keyboard it didn’t work.,iOS11 I’ve tried resetting the keyboard it didn’t work.
24832,31470,de,"28 min Benutzung, 42 min Standby: 10% Akku verbraucht. Mit iOS 11.1 hat sich nichts getan, eher noch schlimmer geworden @AppleSupport","28 min Benutzung, 42 min Standby: 10% Akku verbraucht. Mit iOS 11.1 hat sich nichts getan, eher noch schlimmer geworden"
25195,31868,pt,@AppleSupport Please do as fast as u can I am so disturb,Please do as fast as u can I am so disturb
25214,31889,af,@AppleSupport It didn’t work.,It didn’t work.
25266,31944,fr,@AppleSupport 7 plus latest iOS,7 plus latest iOS
26367,33320,so,@AppleSupport So far so bad,So far so bad
26368,33321,cy,@AppleSupport Why do you guys do this,Why do you guys do this
26375,13956,pt,"@118935 @115858 @AppleSupport @118936 Eu tbm, ja redefini varias vezes a senha e nada, mas ai o suporte me mandou um link e eu marquei hj para alguém da apple me ligar e ajudar.","Eu tbm, ja redefini varias vezes a senha e nada, mas ai o suporte me mandou um link e eu marquei hj para alguém da apple me ligar e ajudar."
26882,34600,de,@123495 @AppleSupport Nachrichten werden bei mir auch nicht mehr zugestellt,Nachrichten werden bei mir auch nicht mehr zugestellt
26886,34598,de,iMessage-Aktivierung schlägt mal wieder fehl… @1652 @AppleSupport,iMessage-Aktivierung schlägt mal wieder fehl...
26929,34653,pt,Alguém sentiu um consumo maior com o novo IOS ou a @AppleSupport está de sacanagem comigo???,Alguém sentiu um consumo maior com o novo IOS ou a está de sacanagem comigo???
26958,34681,nl,@AppleSupport Hoe kan ik de externe microfooningang van mijn iPhone 6S blijven gebruiken voor een professionele microfoon?,Hoe kan ik de externe microfooningang van mijn iPhone 6S blijven gebruiken voor een professionele microfoon?
27520,35283,lt,"@AppleSupport 7 Plus, iOS 11.1","7 Plus, iOS 11.1"
27538,35302,cy,new iOS 11.1 bug? @AppleSupport https://t.co/EPcqhcyxPd,new iOS 11.1 bug?
27568,35335,de,@AppleSupport Series 3 LTE,Series 3 LTE
27570,35338,fr,@AppleSupport 6s plus iOS 11.03,6s plus iOS 11.03
28101,36020,ja,は。このバグ直してーーー\n\n@AppleSupport https://t.co/h089ruD8tv,は。このバグ直してーーー
28137,36065,fr,@AppleSupport insupportable le bug du clavier toujours pas corrigé sur iOS 11.1 ! C’est une priorité d’avoir un clavier fonctionnel non ?,insupportable le bug du clavier toujours pas corrigé sur iOS 11.1 ! C’est une priorité d’avoir un clavier fonctionnel non ?
28139,36067,es,Tengo un problema con macos high Sierra y no tengo ni idea de como solucionarlo. @AppleSupport @119459 https://t.co/ZZPzd8fZAw,Tengo un problema con macos high Sierra y no tengo ni idea de como solucionarlo.

In [47]:
def initial_quality_flag(text):
    """
    Initial conservative quality filtering.
    Does not permanently delete anything.
    """

    if not text or not text.strip():
        return "EMPTY_AFTER_CLEANING"

    text_lower = text.lower().strip()

    # Very short acknowledgement / conversational messages
    low_information = {
        "thanks",
        "thank you",
        "thx",
        "ok",
        "okay",
        "yes",
        "no",
        "yep",
        "nope",
        "sure",
        "i will",
        "will do",
        "great",
        "worked",
        "it worked"
    }

    if text_lower in low_information:
        return "LOW_INFORMATION"

    # Routing-only messages
    routing_only_patterns = [
        r"^dm sent$",
        r"^sent (you )?a dm$",
        r"^sent you (all )?my dm$",
        r"^i('?ve| have) sent (you )?(a )?dm$",
        r"^please check (your )?dms?$",
        r"^check (your )?dms?$",
        r"^dm me( please)?$",
        r"^please dm me$",
    ]

    for pattern in routing_only_patterns:
        if re.fullmatch(pattern, text_lower):
            return "ROUTING_ONLY"

    return "KEEP"

In [48]:
apple_customer_tweets["quality_flag"] = (
    apple_customer_tweets["text_clean"]
    .apply(initial_quality_flag)
)

In [49]:
quality_counts = (
    apple_customer_tweets["quality_flag"]
    .value_counts()
)

display(quality_counts)

quality_flag
KEEP                    2955
EMPTY_AFTER_CLEANING      35
LOW_INFORMATION           27
ROUTING_ONLY               3
Name: count, dtype: int64

In [50]:
display(
    apple_customer_tweets[
        apple_customer_tweets["quality_flag"] != "KEEP"
    ][
        [
            "tweet_id",
            "text_raw",
            "text_clean",
            "quality_flag"
        ]
    ].head(100)
)

,tweet_id,text_raw,text_clean,quality_flag
399,698,@AppleSupport https://t.co/NV0yucs0lB,,EMPTY_AFTER_CLEANING
1197,1787,@AppleSupport Worked 👌🏽,Worked,LOW_INFORMATION
1938,2665,@AppleSupport Yes,Yes,LOW_INFORMATION
4326,5810,@AppleSupport No,No,LOW_INFORMATION
5513,8315,@AppleSupport Thank you,Thank you,LOW_INFORMATION
...,...,...,...,...
95678,121516,@AppleSupport https://t.co/O1zo4tBVpR,,EMPTY_AFTER_CLEANING
95704,121540,@AppleSupport Thank you,Thank you,LOW_INFORMATION
97198,123118,@AppleSupport https://t.co/eoyB4bDXPM,,EMPTY_AFTER_CLEANING
98434,124431,@AppleSupport Yes,Yes,LOW_INFORMATION
99679,125785,@144223 @AppleSupport 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️,,EMPTY_AFTER_CLEANING

In [51]:
def detect_language(text):
    """
    Conservative language detection.

    Very short / technical messages are marked unknown
    because language detection is unreliable for them.
    """

    if pd.isna(text):
        return "unknown"

    text = str(text).strip()

    # Too short for reliable language detection
    if len(text) < 20:
        return "unknown"

    # Need enough alphabetic characters
    alpha_chars = sum(c.isalpha() for c in text)

    if alpha_chars < 10:
        return "unknown"

    try:
        return detect(text)
    except:
        return "unknown"

In [52]:
apple_customer_tweets["language"] = (
    apple_customer_tweets["text_clean"]
    .apply(detect_language)
)

In [53]:
language_distribution = (
    apple_customer_tweets["language"]
    .value_counts()
    .to_frame("count")
)

language_distribution["percentage"] = (
    language_distribution["count"]
    / len(apple_customer_tweets)
    * 100
).round(2)

display(language_distribution)

          count  percentage
language
en         2508       83.05
unknown     389       12.88
es           30        0.99
pt           18        0.60
fr           16        0.53
nl           11        0.36
af            6        0.20
de            6        0.20
da            5        0.17
tr            4        0.13
cy            4        0.13
it            4        0.13
no            3        0.10
ja            2        0.07
et            2        0.07
sv            2        0.07
tl            2        0.07
hu            2        0.07
so            1        0.03
ar            1        0.03
ru            1        0.03
hr            1        0.03
sl            1        0.03
lt            1        0.03

In [55]:
# ============================================
# Save cleaned AppleSupport customer dataset
# ============================================

import os

output_path = "../data/processed/apple_customer_tweets_cleaned.csv"

os.makedirs("../data/processed", exist_ok=True)

apple_customer_tweets.to_csv(
    output_path,
    index=False
)

print("Saved cleaned dataset to:")
print(output_path)

print("\nShape:", apple_customer_tweets.shape)

print("\nColumns:")
print(apple_customer_tweets.columns.tolist())

Saved cleaned dataset to:
../data/processed/apple_customer_tweets_cleaned.csv

Shape: (3020, 11)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'text_raw', 'text_clean', 'language', 'quality_flag']