In [1]:
# ============================================
# 02 - CONVERSATION RECONSTRUCTION
# ============================================

import pandas as pd
from pathlib import Path

RAW_FILE = Path("../data/raw/twcs.csv")

print("Starting conversation reconstruction...")

Starting conversation reconstruction...

In [2]:
# ============================================
# 02 - CONVERSATION RECONSTRUCTION
# Step 2.1 — Load data
# ============================================

import pandas as pd
import numpy as np
from pathlib import Path

RAW_FILE = Path("../data/raw/twcs.csv")

USECOLS = [
    "tweet_id",
    "author_id",
    "inbound",
    "created_at",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]

df = pd.read_csv(
    RAW_FILE,
    usecols=USECOLS,
    nrows=100_000
)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Shape: (100000, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

RAW_FILE = Path("../data/raw/twcs.csv")

USECOLS = [
    "tweet_id",
    "author_id",
    "inbound",
    "created_at",
    "text",
    "response_tweet_id",
    "in_response_to_tweet_id"
]

df = pd.read_csv(
    RAW_FILE,
    usecols=USECOLS,
    nrows=100_000
)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Shape: (100000, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [5]:
# ============================================
# Cell 2 — Normalize IDs and timestamps
# ============================================

df["tweet_id"] = df["tweet_id"].astype(str).str.strip()

df["author_id"] = (
    df["author_id"]
    .fillna("")
    .astype(str)
    .str.strip()
)

df["in_response_to_tweet_id"] = (
    df["in_response_to_tweet_id"]
    .fillna("")
    .astype(str)
    .str.strip()
    .replace("nan", "")
)

df["response_tweet_id"] = (
    df["response_tweet_id"]
    .fillna("")
    .astype(str)
    .str.strip()
    .replace("nan", "")
)

df["created_at"] = pd.to_datetime(
    df["created_at"],
    errors="coerce"
)

print("Data types after normalization:\n")
print(df.dtypes)

print("\nMissing values:\n")
print(df.isna().sum())

C:\Users\SHUBHANSHI GUPTA\AppData\Local\Temp\ipykernel_19640\152449431.py:30: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["created_at"] = pd.to_datetime(

Data types after normalization:

tweet_id                                   str
author_id                                  str
inbound                                   bool
created_at                 datetime64[us, UTC]
text                                       str
response_tweet_id                          str
in_response_to_tweet_id                    str
dtype: object

Missing values:

tweet_id                   0
author_id                  0
inbound                    0
created_at                 0
text                       0
response_tweet_id          0
in_response_to_tweet_id    0
dtype: int64

In [6]:
# ============================================
# Cell 3 — Inspect parent/response relationships
# ============================================

print("Tweets with a parent:")
print((df["in_response_to_tweet_id"] != "").sum())

print("\nTweets with responses:")
print((df["response_tweet_id"] != "").sum())

print("\nExamples of response relationships:\n")

print(
    df.loc[
        df["response_tweet_id"] != "",
        [
            "tweet_id",
            "response_tweet_id",
            "in_response_to_tweet_id"
        ]
    ].head(20).to_string(index=False)
)

Tweets with a parent:
74090

Tweets with responses:
67571

Examples of response relationships:

tweet_id response_tweet_id in_response_to_tweet_id
       1                 2                     3.0
       3                 1                     4.0
       4                 3                     5.0
       5                 4                     6.0
       6               5,7                     8.0
       8            9,6,10
      12          11,13,14                    15.0
      15                12                    16.0
      16                15                    17.0
      17                16                    18.0
      18                17
      20                19
      21             22,23                    24.0
      22                25                    21.0
      25                26                    22.0
      26                27                    25.0
      24                21                    28.0
      28                24                    29.0
      29                28
      31                30

In [7]:
# ============================================
# Cell 4 — Multiple response analysis
# ============================================

response_counts = (
    df["response_tweet_id"]
    .apply(lambda x: len([r.strip() for r in x.split(",") if r.strip()]))
)

print("Response count distribution:\n")
print(response_counts.value_counts().sort_index())

print("\nTweets with multiple responses:")
print((response_counts > 1).sum())

print("\nMaximum responses from one tweet:")
print(response_counts.max())

Response count distribution:

response_tweet_id
0       32429
1       57910
2        7204
3        1378
4         414
        ...
650         1
691         1
722         1
737         1
1090        1
Name: count, Length: 114, dtype: int64

Tweets with multiple responses:
9661

Maximum responses from one tweet:
1090

In [ ]:
'''RAW DATA
twcs.csv
   │
   ├── tweet_id
   ├── parent/response relationships
   ├── author
   ├── inbound
   └── timestamp
          │
          ▼
CONVERSATION RECONSTRUCTION
          │
          ▼
JOIN WITH CLEANED CUSTOMER DATA
          │
          ▼
conversation_id
turn_number
role
text_raw
text_clean
language
quality_flag'''

In [8]:
# ============================================
# Cell 4 — Multiple response analysis
# ============================================

response_counts = (
    df["response_tweet_id"]
    .apply(
        lambda x: len(
            [r.strip() for r in x.split(",") if r.strip()]
        )
    )
)

print("Response count distribution:")
print(response_counts.value_counts().sort_index())

print("\nTweets with multiple responses:")
print((response_counts > 1).sum())

print("\nMaximum responses from one tweet:")
print(response_counts.max())

Response count distribution:
response_tweet_id
0       32429
1       57910
2        7204
3        1378
4         414
        ...
650         1
691         1
722         1
737         1
1090        1
Name: count, Length: 114, dtype: int64

Tweets with multiple responses:
9661

Maximum responses from one tweet:
1090

In [9]:
# ============================================
# Cell 5 — Inspect extreme response case
# ============================================

max_responses = response_counts.max()

extreme_tweet = df.loc[
    response_counts == max_responses,
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "response_tweet_id"
    ]
]

print("Maximum response count:", max_responses)
print("\nTweet(s) with maximum responses:")
print(extreme_tweet.to_string(index=False))

print("\nNumber of response IDs:")
for value in extreme_tweet["response_tweet_id"]:
    ids = [x.strip() for x in value.split(",") if x.strip()]
    print(len(ids))
    print("First 20 IDs:", ids[:20])

Maximum response count: 1090

Tweet(s) with maximum responses:
tweet_id author_id  inbound                created_at                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           response_tweet_id
   87814    115765     True 2017-11-15 01:02:54+00:00 87815,87816,87817,87818,87819,87820,87821,87822,87823,87824,87825,87826,87827,87828,87829,87830,87831,87832,87833,87834,87835,87836,87837,87838,87839,87840,87841,87842,87843,87844,87845,87846,87847,87848,87849,87850,87851,87852,87853,87854,87855,87856,87857,87858,87859,87860,87861,87862,87813,87863,87864,87865,87866,87867,87868,87869,87870,87871,87872,87873,87874,87875,87876,87877,87878,87879,87880,87881,87882,87883,87884,87885,87886,87887,87888,87889,87890,87891,87892,87893,87894,87895,87896,87897,87898,87899,87900,87901,87902,87903,87904,87905,87906,87907,87908,87909,87910,87911,87912,87913,87914,87915,87916,87917,87918,87919,87920,87921,87922,87923,87924,87925,87926,87927,87928,87929,87930,87931,87932,87933,87934,87935,87936,87937,87938,87939,87940,87941,87942,87943,87944,87945,87946,87947,87948,87949,87950,87951,87952,87953,87954,87955,87956,87957,87958,87959,87960,87961,87962,87963,87964,87965,87966,87967,87968,87969,87970,87971,87972,87973,87974,87975,87976,87977,87978,87979,87980,87981,87982,87983,87984,87985,87986,87987,87988,87989,87990,87991,87992,87993,87994,87995,87996,87997,87998,87999,88000,88001,88002,88003,88004,88005,88006,88007,88008,88009,88010,88011,88012,88013,88014,88015,88016,88017,88018,88019,88020,88021,88022,88023,88024,88025,88026,88027,88028,88029,88030,88031,88032,88033,88034,88035,88036,88037,88038,88039,88040,88041,88042,88043,88044,88045,88046,88047,88048,88049,88050,88051,88052,88053,88054,88055,88056,88057,88058,88059,88060,88061,88062,88063,88064,88065,88066,88067,88068,88069,88070,88071,88072,88073,88074,88075,88076,88077,88078,88079,88080,88081,88082,88083,88084,88085,88086,88087,88088,88089,88090,88091,88092,88093,88094,88095,88096,88097,88098,88099,88100,88101,88102,88103,88104,88105,88106,88107,88108,88109,88110,88111,88112,88113,88114,88115,88116,88117,88118,88119,88120,88121,88122,88123,88124,88125,88126,88127,88128,88129,88130,88131,88132,88133,88134,88135,88136,88137,88138,88139,88140,88141,88142,88143,88144,88145,88146,88147,88148,88149,88150,88151,88152,88153,88154,88155,88156,88157,88158,88159,88160,88161,88162,88163,88164,88165,88166,88167,88168,88169,88170,88171,88172,88173,88174,88175,88176,88177,88178,88179,88180,88181,88182,88183,88184,88185,88186,88187,88188,88189,88190,88191,88192,88193,88194,88195,88196,88197,88198,88199,88200,88201,88202,88203,88204,88205,88206,88207,88208,88209,88210,88211,88212,88213,88214,88215,88216,88217,88218,88219,88220,88221,88222,88223,88224,88225,88226,88227,88228,88229,88230,88231,88232,88233,88234,88235,88236,88237,88238,88239,88240,88241,88242,88243,88244,88245,88246,88247,88248,88249,88250,88251,88252,88253,88254,88255,88256,88257,88258,88259,88260,88261,88262,88263,88264,88265,88266,88267,88268,88269,88270,88271,88272,88273,88274,88275,88276,88277,88278,88279,88280,88281,88282,88283,88284,88285,88286,88287,88288,88289,88290,88291,88292,88293,88294,88295,88296,88297,88298,88299,88300,88301,88302,88303,88304,88305,88306,88307,88308,88309,88310,88311,88312,88313,88314,88315,88316,88317,88318,88319,88320,88321,88322,88323,88324,88325,88326,88327,88328,88329,88330,88331,88332,88333,88334,88335,88336,88337,88338,88339,88340,88341,88342,88343,88344,88345,88346,88347,88348,88349,88350,88351,88352,88353,88354,88355,88356,88357,88358,88359,88360,88361,88362,88363,88364,88365,88366,88367,88368,88369,88370,88371,88372,88373,88374,88375,88376,88377,88378,88379,88380,88381,88382,88383,88384,88385,88386,88387,88388,88389,88390,88391,88392,88393,88394,88395,88396,88397,88398,88399,88400,88401,88402,88403,88404,88405,88406,88407,88408,88409,88410,88411,88412,88413,88414,88415,88416,88417,88418,88419,88420,88421,88422,88423,88424,88425,88426,88427,88428,88429,88430,88431,88432,88433,88434,88435,88436,88437,88438,88439,88440,88441,88442,88443,88444,88445,88446,88447,88448,88449,88450,88451,88452,88453,88454,88455,88456,88457,88458,88459,88460,88461,88462,88463,88464,88465,88466,88467,88468,88469,88470,88471,88472,88473,88474,88475,88476,88477,88478,88479,88480,88481,88482,88483,88484,88485,88486,88487,88488,88489,88490,88491,88492,88493,88494,88495,88496,88497,88498,88499,88500,88501,88502,88503,88504,88505,88506,88507,88508,88509,88510,88511,88512,88513,88514,88515,88516,88517,88518,88519,88520,88521,88522,88523,88524,88525,88526,88527,88528,88529,88530,88531,88532,88533,88534,88535,88536,88537,88538,88539,88540,88541,88542,88543,88544,88545,88546,88547,88548,88549,88550,88551,88552,88553,88554,88555,88556,88557,88558,88559,88560,88561,88562,88563,88564,88565,88566,88567,88568,88569,88570,88571,88572,88573,88574,88575,88576,88577,88578,88579,88580,88581,88582,88583,88584,88585,88586,88587,88588,88589,88590,88591,88592,88593,88594,88595,88596,88597,88598,88599,88600,88601,88602,88603,88604,88605,88606,88607,88608,88609,88610,88611,88612,88613,88614,88615,88616,88617,88618,88619,88620,88621,88622,88623,88624,88625,88626,88627,88628,88629,88630,88631,88632,88633,88634,88635,88636,88637,88638,88639,88640,88641,88642,88643,88644,88645,88646,88647,88648,88649,88650,88651,88652,88653,88654,88655,88656,88657,88658,88659,88660,88661,88662,88663,88664,88665,88666,88667,88668,88669,88670,88671,88672,88673,88674,88675,88676,88677,88678,88679,88680,88681,88682,88683,88684,88685,88686,88687,88688,88689,88690,88691,88692,88693,88694,88695,88696,88697,88698,88699,88700,88701,88702,88703,88704,88705,88706,88707,88708,88709,88710,88711,88712,88713,88714,88715,88716,88717,88718,88719,88720,88721,88722,88723,88724,88725,88726,88727,88728,88729,88730,88731,88732,88733,88734,88735,88736,88737,88738,88739,88740,88741,88742,88743,88744,88745,88746,88747,88748,88749,88750,88751,88752,88753,88754,88755,88756,88757,88758,88759,88760,88761,88762,88763,88764,88765,88766,88767,88768,88769,88770,88771,88772,88773,88774,88775,88776,88777,88778,88779,88780,88781,88782,88783,88784,88785,88786,88787,88788,88789,88790,88791,88792,88793,88794,88795,88796,88797,88798,88799,88800,88801,88802,88803,88804,88805,88806,88807,88808,88809,88810,88811,88812,88813,88814,88815,88816,88817,88818,88819,88820,88821,88822,88823,88824,88825,88826,88827,88828,88829,88830,88831,88832,88833,88834,88835,88836,88837,88838,88839,88840,88841,88842,88843,88844,88845,88846,88847,88848,88849,88850,88851,88852,88853,88854,88855,88856,88857,88858,88859,88860,88861,88862,88863,88864,88865,88866,88867,88868,88869,88870,88871,88872,88873,88874,88875,88876,88877,88878,88879,88880,88881,88882,88883,88884,88885,88886,88887,88888,88889,88890,88891,88892,88893,88894,88895,88896,88897,88898,88899,88900,88901,88902,88903

Number of response IDs:
1090
First 20 IDs: ['87815', '87816', '87817', '87818', '87819', '87820', '87821', '87822', '87823', '87824', '87825', '87826', '87827', '87828', '87829', '87830', '87831', '87832', '87833', '87834']

In [11]:
# ============================================
# Cell 7 — Fix parent tweet IDs
# ============================================

df["in_response_to_tweet_id"] = (
    df["in_response_to_tweet_id"]
    .replace("", pd.NA)
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
    .fillna("")
)

print(
    df[
        ["tweet_id", "in_response_to_tweet_id"]
    ].head(10).to_string(index=False)
)

tweet_id in_response_to_tweet_id
       1                       3
       2                       1
       3                       4
       4                       5
       5                       6
       6                       8
       8
      11                      12
      12                      15
      15                      16

In [12]:
# ============================================
# Cell 8 — Re-check parent relationships
# ============================================

tweet_ids = set(df["tweet_id"])

parent_ids = set(
    df.loc[
        df["in_response_to_tweet_id"] != "",
        "in_response_to_tweet_id"
    ]
)

existing_parents = parent_ids.intersection(tweet_ids)
missing_parents = parent_ids - tweet_ids

print("Tweets in dataset:", len(tweet_ids))
print("Unique parent IDs referenced:", len(parent_ids))
print("Parent IDs present in dataset:", len(existing_parents))
print("Parent IDs missing from dataset:", len(missing_parents))

print("\nPercentage of referenced parents available:")

if len(parent_ids) > 0:
    print(
        round(
            len(existing_parents) / len(parent_ids) * 100,
            2
        ),
        "%"
    )

Tweets in dataset: 100000
Unique parent IDs referenced: 67666
Parent IDs present in dataset: 67571
Parent IDs missing from dataset: 95

Percentage of referenced parents available:
99.86 %

In [13]:
# ============================================
# Cell 9 — Create parent lookup
# ============================================

parent_map = (
    df.set_index("tweet_id")["in_response_to_tweet_id"]
    .to_dict()
)

print("Parent map size:", len(parent_map))

print("\nSample parent relationships:")

for tweet_id in list(parent_map.keys())[:10]:
    print(
        f"Tweet {tweet_id} → "
        f"Parent {parent_map[tweet_id]}"
    )

Parent map size: 100000

Sample parent relationships:
Tweet 1 → Parent 3
Tweet 2 → Parent 1
Tweet 3 → Parent 4
Tweet 4 → Parent 5
Tweet 5 → Parent 6
Tweet 6 → Parent 8
Tweet 8 → Parent
Tweet 11 → Parent 12
Tweet 12 → Parent 15
Tweet 15 → Parent 16

In [14]:
# ============================================
# Cell 10 — Identify AppleSupport tweets
# ============================================

apple_support = df[
    df["author_id"].str.lower() == "applesupport"
].copy()

print("AppleSupport tweets:", len(apple_support))

print("\nFirst 10 AppleSupport tweets:")

print(
    apple_support[
        [
            "tweet_id",
            "created_at",
            "in_response_to_tweet_id",
            "response_tweet_id",
            "text"
        ]
    ].head(10).to_string(index=False)
)

AppleSupport tweets: 3106

First 10 AppleSupport tweets:
tweet_id                created_at in_response_to_tweet_id response_tweet_id                                                                                                                                           text
     696 2017-10-31 22:27:49+00:00                     698               697                             @115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.
     699 2017-10-31 22:36:27+00:00                     697                   @115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT
     701 2017-10-31 22:26:49+00:00                     702                                                                                   @115855 Let's go to DM for the next steps. DM us here: https://t.co/GDrqU22YpT
     703 2017-10-31 22:09:52+00:00                     704               702                                                                                           @115855 Any steps tried since it started last night?
     705 2017-10-31 21:57:00+00:00                     707           706,704     @115855 That's great it has iOS 11.1 as we can rule out being outdated. Any steps tried since this started? Do you recall when it started?
     708 2017-10-31 21:43:15+00:00                     709               707                       @115855 We'd like to look into this with you. Which model do you have and is iOS 11.1 installed? Any steps tried so far?
     712 2017-10-31 22:26:29+00:00                     714               713           @115856 Hey, let's work together to figure out what's going on. Meet us in DM and we'll continue from there. https://t.co/GDrqU22YpT
     716 2017-10-31 22:24:54+00:00                     717                                 @115857 We'd like to investigate further with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT
     718 2017-10-31 22:05:00+00:00                     719               717                                                                      @115857 Fill us in on what is happening, then we can help out from there.
     720 2017-10-31 22:24:27+00:00                     721                                                                                                          @115859 We've received your DM and will continue there.

In [15]:
# ============================================
# Cell 11 — Trace one conversation upward
# ============================================

def trace_parents(tweet_id, parent_map, max_depth=20):
    chain = []
    current = str(tweet_id)

    for _ in range(max_depth):
        if not current:
            break

        chain.append(current)

        parent = parent_map.get(current, "")

        if not parent:
            break

        if parent in chain:
            print("Cycle detected.")
            break

        current = parent

    return chain


tweet_id = "696"

chain = trace_parents(
    tweet_id,
    parent_map
)

print("Parent chain for tweet", tweet_id)
print(" → ".join(chain))

print("\nTweet details:\n")

for tid in chain:
    row = df[df["tweet_id"] == tid]

    if len(row) == 0:
        print(f"{tid}: NOT FOUND")
    else:
        row = row.iloc[0]

        print(
            f"Tweet {tid} | "
            f"Author: {row['author_id']} | "
            f"Inbound: {row['inbound']}"
        )
        print(row["text"])
        print("-" * 80)

Parent chain for tweet 696
696 → 698 → 700

Tweet details:

Tweet 696 | Author: AppleSupport | Inbound: False
@115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About.
--------------------------------------------------------------------------------
Tweet 698 | Author: 115854 | Inbound: True
@AppleSupport  https://t.co/NV0yucs0lB
--------------------------------------------------------------------------------
Tweet 700 | Author: 115854 | Inbound: True
@AppleSupport why are my I️’s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE
--------------------------------------------------------------------------------

In [16]:
# ============================================
# Cell 12 — Inspect a multi-response conversation
# ============================================

tweet_id = "705"

row = df[df["tweet_id"] == tweet_id].iloc[0]

print("Parent tweet:")
print(
    f"Tweet {row['tweet_id']} | "
    f"Author: {row['author_id']} | "
    f"Inbound: {row['inbound']}"
)
print(row["text"])

print("\nResponse IDs:")
print(row["response_tweet_id"])

response_ids = [
    x.strip()
    for x in row["response_tweet_id"].split(",")
    if x.strip()
]

print("\nChild tweets:\n")

for response_id in response_ids:

    child = df[df["tweet_id"] == response_id]

    if len(child) == 0:
        print(f"Tweet {response_id}: NOT FOUND")
        continue

    child = child.iloc[0]

    print(
        f"Tweet {child['tweet_id']} | "
        f"Author: {child['author_id']} | "
        f"Inbound: {child['inbound']} | "
        f"Parent: {child['in_response_to_tweet_id']}"
    )

    print(child["text"])
    print("-" * 80)

Parent tweet:
Tweet 705 | Author: AppleSupport | Inbound: False
@115855 That's great it has iOS 11.1 as we can rule out being outdated. Any steps tried since this started? Do you recall when it started?

Response IDs:
706,704

Child tweets:

Tweet 706: NOT FOUND
Tweet 704 | Author: 115855 | Inbound: True | Parent: 705
@AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
--------------------------------------------------------------------------------

In [17]:
# ============================================
# Cell 13 — Validate response IDs against dataset
# ============================================

tweet_ids = set(df["tweet_id"])

total_response_ids = 0
existing_response_ids = 0
missing_response_ids = 0

for value in df["response_tweet_id"]:
    ids = [
        x.strip()
        for x in value.split(",")
        if x.strip()
    ]

    total_response_ids += len(ids)

    for response_id in ids:
        if response_id in tweet_ids:
            existing_response_ids += 1
        else:
            missing_response_ids += 1

print("Total response IDs:", total_response_ids)
print("Response tweets present:", existing_response_ids)
print("Response tweets missing:", missing_response_ids)

print(
    "\nResponse IDs available in current sample:",
    round(
        existing_response_ids / total_response_ids * 100,
        2
    ),
    "%"
)

Total response IDs: 100025
Response tweets present: 73995
Response tweets missing: 26030

Response IDs available in current sample: 73.98 %

In [18]:
# ============================================
# Cell 14 — Build child lookup
# ============================================

child_map = {}

for _, row in df.iterrows():
    parent_id = row["in_response_to_tweet_id"]

    if parent_id:
        child_map.setdefault(parent_id, []).append(
            row["tweet_id"]
        )

print("Tweets with at least one child in sample:", len(child_map))

print("\nExample child relationships:")

for parent_id, children in list(child_map.items())[:10]:
    print(
        f"Parent {parent_id} → Children {children}"
    )

Tweets with at least one child in sample: 67666

Example child relationships:
Parent 3 → Children ['1']
Parent 1 → Children ['2']
Parent 4 → Children ['3']
Parent 5 → Children ['4']
Parent 6 → Children ['5']
Parent 8 → Children ['6']
Parent 12 → Children ['11', '13']
Parent 15 → Children ['12']
Parent 16 → Children ['15']
Parent 17 → Children ['16']

In [19]:
# ============================================
# Cell 15 — Assign conversation root IDs
# ============================================

from functools import lru_cache

@lru_cache(maxsize=None)
def find_root(tweet_id):
    current = str(tweet_id)
    visited = set()

    while current:
        if current in visited:
            # Safety against unexpected cycles
            return current

        visited.add(current)

        parent = parent_map.get(current, "")

        if not parent:
            return current

        # Parent exists in our sample
        if parent not in parent_map:
            return current

        current = parent

    return str(tweet_id)


df["conversation_id"] = df["tweet_id"].apply(find_root)

print("Unique conversations:", df["conversation_id"].nunique())

print("\nExample conversation assignments:")
print(
    df[
        ["tweet_id", "in_response_to_tweet_id", "conversation_id"]
    ]
    .head(20)
    .to_string(index=False)
)

Unique conversations: 26005

Example conversation assignments:
tweet_id in_response_to_tweet_id conversation_id
       1                       3               8
       2                       1               8
       3                       4               8
       4                       5               8
       5                       6               8
       6                       8               8
       8                                       8
      11                      12              18
      12                      15              18
      15                      16              18
      16                      17              18
      17                      18              18
      18                                      18
      19                      20              20
      20                                      20
      21                      24              29
      22                      21              29
      25                      22              29
      26                      25              29
      27                      26              29

In [20]:
# ============================================
# Cell 16 — Inspect one reconstructed conversation
# ============================================

conversation_id = "8"

conversation = (
    df[df["conversation_id"] == conversation_id]
    .sort_values("created_at")
    .copy()
)

print("Conversation ID:", conversation_id)
print("Number of tweets:", len(conversation))

print("\n" + "=" * 100)

for _, row in conversation.iterrows():
    role = (
        "CUSTOMER"
        if row["inbound"]
        else "SUPPORT"
    )

    print(
        f"[{row['created_at']}] "
        f"{role} | Tweet {row['tweet_id']}"
    )
    print(row["text"])
    print("-" * 100)

Conversation ID: 8
Number of tweets: 7

====================================================================================================
[2017-10-31 21:45:10+00:00] CUSTOMER | Tweet 8
@sprintcare is the worst customer service
----------------------------------------------------------------------------------------------------
[2017-10-31 21:46:24+00:00] SUPPORT | Tweet 6
@115712 Can you please send us a private message, so that I can gain further details about your account?
----------------------------------------------------------------------------------------------------
[2017-10-31 21:49:35+00:00] CUSTOMER | Tweet 5
@sprintcare I did.
----------------------------------------------------------------------------------------------------
[2017-10-31 21:54:49+00:00] SUPPORT | Tweet 4
@115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.
----------------------------------------------------------------------------------------------------
[2017-10-31 22:08:27+00:00] CUSTOMER | Tweet 3
@sprintcare I have sent several private messages and no one is responding as usual
----------------------------------------------------------------------------------------------------
[2017-10-31 22:10:47+00:00] SUPPORT | Tweet 1
@115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.
----------------------------------------------------------------------------------------------------
[2017-10-31 22:11:45+00:00] CUSTOMER | Tweet 2
@sprintcare and how do you propose we do that
----------------------------------------------------------------------------------------------------

In [21]:
# ============================================
# Cell 17 — Identify AppleSupport conversations
# ============================================

apple_support_conversation_ids = set(
    df.loc[
        df["author_id"].str.lower() == "applesupport",
        "conversation_id"
    ]
)

apple_conversations = df[
    df["conversation_id"].isin(apple_support_conversation_ids)
].copy()

print("AppleSupport conversations:", len(apple_support_conversation_ids))
print("Tweets belonging to AppleSupport conversations:", len(apple_conversations))

print("\nExample conversation IDs:")
print(list(apple_support_conversation_ids)[:20])

print("\nRole distribution:")
print(
    apple_conversations["inbound"]
    .map({True: "CUSTOMER", False: "SUPPORT"})
    .value_counts()
)

AppleSupport conversations: 2066
Tweets belonging to AppleSupport conversations: 6836

Example conversation IDs:
['4906', '31491', '79997', '62254', '13953', '51623', '12010', '44571', '41558', '65010', '107371', '105349', '114521', '31897', '124440', '125030', '59606', '92724', '92661', '61342']

Role distribution:
inbound
CUSTOMER    3729
SUPPORT     3107
Name: count, dtype: int64

In [22]:
# ============================================
# Cell 18 — Inspect one AppleSupport conversation
# ============================================

conversation_id = next(iter(apple_support_conversation_ids))

conversation = (
    apple_conversations[
        apple_conversations["conversation_id"] == conversation_id
    ]
    .sort_values("created_at")
    .copy()
)

print("Conversation ID:", conversation_id)
print("Number of tweets:", len(conversation))

print("\n" + "=" * 100)

for _, row in conversation.iterrows():

    role = (
        "CUSTOMER"
        if row["inbound"]
        else "SUPPORT"
    )

    print(
        f"[{row['created_at']}] "
        f"{role} | Tweet {row['tweet_id']}"
    )

    print(row["text"])

    print("-" * 100)

Conversation ID: 4906
Number of tweets: 4

====================================================================================================
[2017-10-31 23:06:38+00:00] CUSTOMER | Tweet 4906
@AppleSupport The ‘Overlapping url over TIME on Free WiFi hotspots’ remains. v11.0.3. Not a WiFi problem; two different hotspots shown. https://t.co/81ifcrDUeS
----------------------------------------------------------------------------------------------------
[2017-10-31 23:18:26+00:00] SUPPORT | Tweet 4904
@116855 We'd like to have you backup and update your iPhone to iOS 11.1 and let us know if that helps: https://t.co/ahjigcvFRG
----------------------------------------------------------------------------------------------------
[2017-10-31 23:21:45+00:00] CUSTOMER | Tweet 4905
@AppleSupport I've updated to iOS 11.1 just now. I shall check out these WiFi hotspots tomorrow and later in the week.
----------------------------------------------------------------------------------------------------
[2017-10-31 23:34:00+00:00] SUPPORT | Tweet 4907
@116855 Sounds good. Let us know the results in DM and we'll continue working with you there. Thanks again. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------

In [23]:
# ============================================
# Cell 19 — Build structured conversation data
# ============================================

conversation_df = (
    apple_conversations
    .sort_values(["conversation_id", "created_at"])
    .copy()
)

conversation_df["role"] = conversation_df["inbound"].map({
    True: "customer",
    False: "support"
})

conversation_df["turn_number"] = (
    conversation_df
    .groupby("conversation_id")
    .cumcount() + 1
)

conversation_df = conversation_df[
    [
        "conversation_id",
        "turn_number",
        "tweet_id",
        "author_id",
        "role",
        "created_at",
        "text",
        "in_response_to_tweet_id",
        "response_tweet_id"
    ]
].rename(
    columns={
        "text": "text_raw",
        "in_response_to_tweet_id": "parent_tweet_id",
        "response_tweet_id": "response_tweet_ids"
    }
)

print("Shape:", conversation_df.shape)

print("\nColumns:")
print(conversation_df.columns.tolist())

print("\nRole distribution:")
print(conversation_df["role"].value_counts())

print("\nExample:")
print(
    conversation_df[
        conversation_df["conversation_id"] == "4906"
    ].to_string(index=False)
)

Shape: (6836, 9)

Columns:
['conversation_id', 'turn_number', 'tweet_id', 'author_id', 'role', 'created_at', 'text_raw', 'parent_tweet_id', 'response_tweet_ids']

Role distribution:
role
customer    3729
support     3107
Name: count, dtype: int64

Example:
conversation_id  turn_number tweet_id    author_id     role                created_at                                                                                                                                                        text_raw parent_tweet_id response_tweet_ids
           4906            1     4906       116855 customer 2017-10-31 23:06:38+00:00 @AppleSupport The ‘Overlapping url over TIME on Free WiFi hotspots’ remains. v11.0.3. Not a WiFi problem; two different hotspots shown. https://t.co/81ifcrDUeS                               4904
           4906            2     4904 AppleSupport  support 2017-10-31 23:18:26+00:00                                  @116855 We'd like to have you backup and update your iPhone to iOS 11.1 and let us know if that helps: https://t.co/ahjigcvFRG            4906               4905
           4906            3     4905       116855 customer 2017-10-31 23:21:45+00:00                                          @AppleSupport I've updated to iOS 11.1 just now. I shall check out these WiFi hotspots tomorrow and later in the week.            4904               4907
           4906            4     4907 AppleSupport  support 2017-10-31 23:34:00+00:00                             @116855 Sounds good. Let us know the results in DM and we'll continue working with you there. Thanks again. https://t.co/GDrqU22YpT            4905

In [24]:
# ============================================
# Cell 20 — Conversation quality statistics
# ============================================

conversation_stats = (
    conversation_df
    .groupby("conversation_id")
    .agg(
        turns=("tweet_id", "count"),
        customer_turns=("role", lambda x: (x == "customer").sum()),
        support_turns=("role", lambda x: (x == "support").sum())
    )
)

print("Total conversations:", len(conversation_stats))

print("\nConversation length distribution:")
print(
    conversation_stats["turns"]
    .value_counts()
    .sort_index()
    .head(20)
)

print("\nConversations with multiple turns:")
print(
    (conversation_stats["turns"] > 1).sum()
)

print("\nConversations with customer + support:")
print(
    (
        (conversation_stats["customer_turns"] > 0) &
        (conversation_stats["support_turns"] > 0)
    ).sum()
)

print("\nAverage turns per conversation:")
print(round(conversation_stats["turns"].mean(), 2))

print("\nMaximum turns in one conversation:")
print(conversation_stats["turns"].max())

Total conversations: 2066

Conversation length distribution:
turns
2     1149
3      177
4      362
5      111
6      126
7       41
8       52
9       22
10      13
11       2
12       5
13       1
17       2
24       1
27       1
37       1
Name: count, dtype: int64

Conversations with multiple turns:
2066

Conversations with customer + support:
2066

Average turns per conversation:
3.31

Maximum turns in one conversation:
37

In [25]:
# ============================================
# Cell 21 — Inspect long conversations
# ============================================

long_conversations = (
    conversation_stats[
        conversation_stats["turns"] >= 10
    ]
    .sort_values("turns", ascending=False)
)

print("Conversations with 10+ turns:", len(long_conversations))

print("\nLongest conversations:")
print(long_conversations)

print("\n" + "=" * 100)

for conversation_id in long_conversations.head(3).index:

    conversation = (
        conversation_df[
            conversation_df["conversation_id"] == conversation_id
        ]
        .sort_values("turn_number")
    )

    print(
        f"\nConversation {conversation_id} "
        f"({len(conversation)} turns)"
    )

    for _, row in conversation.iterrows():
        print(
            f"{row['turn_number']}. "
            f"[{row['role'].upper()}] "
            f"{row['text_raw'][:250]}"
        )

    print("-" * 100)

Conversations with 10+ turns: 26

Longest conversations:
                 turns  customer_turns  support_turns
conversation_id
9200                37              20             17
117940              27              18              9
40514               24              21              3
33360               17               9              8
61348               17               9              8
61302               13               7              6
50818               12               7              5
39604               12               8              4
120658              12               9              3
62279               12               7              5
87091               12               6              6
38645               11               6              5
40527               11               6              5
110869              10               5              5
34598               10               5              5
125764              10               6              4
123099              10               6              4
50050               10               6              4
55942               10               6              4
45599               10               6              4
48026               10               6              4
711                 10               6              4
747                 10               5              5
90233               10               5              5
90600               10               5              5
96896               10               5              5

====================================================================================================

Conversation 9200 (37 turns)
1. [SUPPORT] It’s attack of the new emoji.

Unleash a zombie emoji-pocalypse this Halloween with the echo effect in Messages. https://t.co/P4l8dMu9dj
2. [CUSTOMER] @AppleSupport Does the person you send it too also have to have a iPhone to see this?I see it on my phone.
3. [SUPPORT] @117654 Great question. They must have a device with iOS 10 or later. Here's some more information: https://t.co/GCtGkHihKu
4. [CUSTOMER] @AppleSupport But would it work with another phone brand?Like LG galaxy phones?
5. [SUPPORT] @117654 Currently, only iPhones with iOS 10 or later are supported.
6. [CUSTOMER] @AppleSupport Im using iPhone6s,it is installed with iOS 11.0.3 n battery drain problem is not resolved in it.When they resolve this issue in wht update?
7. [SUPPORT] @118712 We've received your DM and will be responding there shortly. Thank you.
8. [CUSTOMER] @AppleSupport Fix our iOS 11.03 battery issue. I’m on a 7 plus. @1257
9. [CUSTOMER] @AppleSupport I have the iPhone 7 Plus but i can’t do that 😢
10. [CUSTOMER] @AppleSupport I thought this update would fix the problem with appstore/itunes payments. I cant open some apps , i cant update any and i cant download any
11. [CUSTOMER] @AppleSupport I updated to iOS 11.1 and the phone get really warm and the battery dropped by 10% in 10 minuets when I watched videos in YouTube. iPhone 7+
12. [CUSTOMER] @AppleSupport When will fix the problem with activation (error 0xE8000013)? Or your phones are now disposable?
13. [CUSTOMER] @AppleSupport Hello, I have questions, what model of an iPhone X that selling on Apple store Australia. And its sim free unlocked or not.
14. [CUSTOMER] @AppleSupport And when is the summer free is going to be released?
15. [SUPPORT] @123171 Thanks for reaching out. We are always happy to help. Are you running iOS 11.1? If not, learn how here: https://t.co/80YRnjDFDk
16. [SUPPORT] @123167 Send us a DM and let us know how long your battery is lasting. We'll help. https://t.co/GDrqU22YpT
17. [SUPPORT] @123366 That should not be happening. Let us help. Tell us more about this in DM. https://t.co/GDrqU22YpT
18. [SUPPORT] @123523 Let's explore this in more details. Which device is exact iOS version are you using? When are you receiving this error?
19. [SUPPORT] @123515 We'd be happy to look into what's going on. Which device and iOS version are you using?
20. [CUSTOMER] @AppleSupport Where’s the update for this I️. Why does the letter l do that. Why do I️ have to use a lowercase L for a capital l?!
21. [SUPPORT] @123846 We'd be happy to look into this with you.  Please reach out to us via DM and we'll get started. https://t.co/GDrqU22YpT
22. [CUSTOMER] @AppleSupport Thanks! I have iOS 11.1 but i dont see the new emojis 😫
23. [SUPPORT] @123171 Thanks for following up. Send us a DM so we can look into this with you there. https://t.co/GDrqU22YpT
24. [SUPPORT] @124299 We’re also excited for the iPhone X! You can find out more information about available models here: https://t.co/yl9mQrnFWP
25. [CUSTOMER] @AppleSupport I am using iOS 11.0.3 but I was unable to get that option
26. [CUSTOMER] @AppleSupport No thanks. My fiancé works tech support for Apple. He complains about the same thing.
27. [SUPPORT] @125903 Are you referring to the echo effect in Messages? Let us know via DM and we'll look into it. https://t.co/GDrqU22YpT
28. [CUSTOMER] @AppleSupport Ya I was asking about it
29. [SUPPORT] @125903 Be sure you don't have Reduce Motion turned on: https://t.co/P2Obw7hkfD Send us a DM if you still can't find it. https://t.co/GDrqU22YpT
30. [CUSTOMER] @AppleSupport Have bug... if send to people that have old ios... LCD freze. Need to close. To go back 😏
31. [SUPPORT] @129597 Thanks for reaching out to us. To clarify, when using the Echo effect, does your Messages app become unresponsive?
32. [CUSTOMER] @AppleSupport Yes unresponsive, i have blank screan, need to force close, and open again messages. Thanks
33. [SUPPORT] @129597 Thanks for those details. To help isolate the issue, can you tell us which version of iOS 11 your device is on?
34. [CUSTOMER] @AppleSupport I am using Iphone 7 and iOS 11.1
35. [SUPPORT] @123515 DM us your country, and we'll continue working there. https://t.co/GDrqU22YpT
36. [CUSTOMER] @AppleSupport @123366 Mee too
37. [CUSTOMER] @123367 @AppleSupport @123366 Mee to same issue
----------------------------------------------------------------------------------------------------

Conversation 117940 (27 turns)
1. [CUSTOMER] Hi @AppleSupport, could you pls explain why, since I downloaded yr iOS update, my iPhone crashes at 10%,  20%, even 40% battery? Massively inconvenient at best.
2. [CUSTOMER] @142155 @AppleSupport Same problems. And notifications all over the place. #shambolic
3. [CUSTOMER] @142155 @AppleSupport My battery is awful after the latest update. It’s flat by mid-morning.
4. [CUSTOMER] @142155 @AppleSupport Thank you! I thought it was just my phone. Come on Apple what’s going on?!
5. [CUSTOMER] @142528 @142155 @AppleSupport Mine too! I wonder what we can do about it? My phone is 6s but I have to charge it twice a day 😭
6. [SUPPORT] @142174 That's not expected, but we're glad to assist. Connect with us in DM to continue. https://t.co/GDrqU22YpT
7. [CUSTOMER] @142155 @AppleSupport Snap. Downloaded all the updates as well but my 5S still drains twice as quick as it used to and goes from 20% to ‘off’ in seconds. Grrrr
8. [SUPPORT] @142155 Thanks for reaching out to us. We'd like to work closely with you and get your iPhone working properly. Please join us in DM and we'll get started. https://t.co/GDrqU22YpT
9. [SUPPORT] @123246 Issues with your iPhone battery? We can help. DM us with more details to get started. https://t.co/GDrqU22YpT
10. [SUPPORT] @142527 Maximizing the battery life on your iPhone is vital. We'd be happy to review this for you. Please DM us with more details and we'll go from there. https://t.co/GDrqU2kzhr
11. [SUPPORT] @142516 We'll gladly assist. So you are updated to iOS 11.1.2? Not running the beta of iOS 11.2? Let us know in DM. https://t.co/GDrqU22YpT
12. [CUSTOMER] @142155 @AppleSupport My 6s starts as expected at 100% use it for 5 minutes and it needs recharged, really infuriating
13. [CUSTOMER] @AppleSupport As it seems to be a widespread problem, perhaps you can tell me by public message.
14. [SUPPORT] @142823 We'd like to look into what's happening on your iPhone. Could you join us in DM to get started? https://t.co/GDrqU22YpT
15. [CUSTOMER] @142155 @AppleSupport This helping any others with the same problem at the same time. Sound reasoning.
16. [SUPPORT] @142155 We would like to gather further details in DM. Let us know which device you are using and we can get started. https://t.co/GDrqU22YpT
17. [CUSTOMER] @142155 @AppleSupport How about a less than year old 7 - dies at 10%, freezes 15 times a day, skips music when multitasking and occasionally will load an app and then freeze up. This is a joke you’re quite right!
18. [SUPPORT] @143055 We'd like to look into the issues you're experiencing. Reach out via DM using the link below and let us know what version of iOS you have installed. You can check by tapping Settings &gt; General &gt; About.
19. [CUSTOMER] @142155 @AppleSupport They mean they don't want it so public. Android is the way. Far better system!
20. [CUSTOMER] @AppleSupport Ok I’ll have a look katerz
21. [CUSTOMER] @142155 @AppleSupport Any thoughts yet @AppleSupport as you’ve gone 🤫 quiet. Your “clients” are waiting for you to resolve this issue that’s more widespread than you want to believe.
22. [CUSTOMER] @AppleSupport I'm using a iPhone 6. Let's get started.
23. [CUSTOMER] @142155 @AppleSupport It is a problem that seems to effect mainly iPhone 6 en 6s. Battery should not be effected by updates, but it is. Promised fixes haven't helped so far. There also seems to be a problem with connecting stuff through lighting port
24. [CUSTOMER] @142156 @142155 @AppleSupport Also weird stuff happening with iPhone 7’s since the update. Mysterious temporary screen blackouts, occasional reboots and the phone doesn’t work well with the iPhone 7 Apple Battery Case
25. [SUPPORT] @142157 Let's take a look at this together. When the screen blacks out or reboots, are you using any app in particular, or is it random? When it turns back on, do you see the Apple logo or a spinning gear? Let us know in DM and we'll team up to get t
26. [CUSTOMER] @AppleSupport Hello @AppleSupport? Are you still there?
27. [CUSTOMER] @142155 @AppleSupport Thats not good ☹️
----------------------------------------------------------------------------------------------------

Conversation 40514 (24 turns)
1. [CUSTOMER] Yes!!!!! https://t.co/ouyrITWNYj
2. [CUSTOMER] @124888 Have you figured how to resolve?
3. [CUSTOMER] @124882 Nope &amp; Ive been reading everything for the past 10 days 😥
4. [CUSTOMER] @124888 @115858 @AppleSupport is there an official fix for the 11.0.3 battery issue? 😰😭😓
5. [SUPPORT] @124882 If you're having issues with your iPhone battery life, we'd like to help. Update to iOS 11.1 &amp; let us know if that persists after.
6. [CUSTOMER] @AppleSupport Is it now GA? I thought it was still in beta
7. [CUSTOMER] @AppleSupport @124882 Even i have the battery drain issues since updating to iOS 11. Not even any better on iOS 11.1
8. [CUSTOMER] @124883 @AppleSupport Seriously???
9. [CUSTOMER] @124882 @AppleSupport Yes, i waited eagerly for 11.1 but much disappointed. Performance has been much better but battery life sucks. I wish i stayed at 10.3.3
10. [CUSTOMER] @124882 @AppleSupport Just check my usage stats at 30%screen on time. And i just got a new battery 1-2 months ago, was running fine on 10.3.3 https://t.co/pRDYoTIHNk
11. [SUPPORT] @124882 We released iOS 11.1 yesterday publicly. DM us if you run into any further issues. https://t.co/GDrqU22YpT
12. [CUSTOMER] @AppleSupport Cool will dot thx
13. [SUPPORT] @124883 Battery life is important, so we'd like to help. Let us know in DM when this started happening. https://t.co/GDrqU22YpT
14. [CUSTOMER] @AppleSupport Done
15. [CUSTOMER] @AppleSupport @124882 It’s worse on 11.1
16. [CUSTOMER] @124885 @AppleSupport Mine actually has gotten better since updating
17. [CUSTOMER] @AppleSupport @124882 I updated to 11.1 and it got worse
18. [CUSTOMER] @124882 @AppleSupport Must be one of the lucky ones, it’s seems a lot are worse off and some are better off! Mines definitely ridiculously worse
19. [CUSTOMER] @AppleSupport @124882 I have a gen 6 Ipod Touch that is having a heck of a time with this new iOS. Please help!
20. [CUSTOMER] @124884 @AppleSupport Beth you may want to DM
21. [CUSTOMER] @AppleSupport @124882 I had no issues with battery drain until I updated to iOS 11.1
22. [CUSTOMER] @124887 @AppleSupport Mine actually got better. What device?
23. [CUSTOMER] @124882 @AppleSupport 6s plus
24. [CUSTOMER] @124887 @AppleSupport That sucks
----------------------------------------------------------------------------------------------------

In [26]:
# ============================================
# Cell 22 — Inspect longest conversation
# ============================================

conversation_id = "9200"

conversation = (
    conversation_df[
        conversation_df["conversation_id"] == conversation_id
    ]
    .sort_values("turn_number")
)

print("Conversation ID:", conversation_id)
print("Total turns:", len(conversation))

print("\n" + "=" * 100)

for _, row in conversation.iterrows():

    print(
        f"Turn {row['turn_number']} | "
        f"{row['role'].upper()} | "
        f"Tweet {row['tweet_id']} | "
        f"Parent {row['parent_tweet_id']}"
    )

    print(row["text_raw"])

    print("-" * 100)

Conversation ID: 9200
Total turns: 37

====================================================================================================
Turn 1 | SUPPORT | Tweet 9200 | Parent
It’s attack of the new emoji.

Unleash a zombie emoji-pocalypse this Halloween with the echo effect in Messages. https://t.co/P4l8dMu9dj
----------------------------------------------------------------------------------------------------
Turn 2 | CUSTOMER | Tweet 9198 | Parent 9200
@AppleSupport Does the person you send it too also have to have a iPhone to see this?I see it on my phone.
----------------------------------------------------------------------------------------------------
Turn 3 | SUPPORT | Tweet 9196 | Parent 9198
@117654 Great question. They must have a device with iOS 10 or later. Here's some more information: https://t.co/GCtGkHihKu
----------------------------------------------------------------------------------------------------
Turn 4 | CUSTOMER | Tweet 9197 | Parent 9196
@AppleSupport But would it work with another phone brand?Like LG galaxy phones?
----------------------------------------------------------------------------------------------------
Turn 5 | SUPPORT | Tweet 9199 | Parent 9197
@117654 Currently, only iPhones with iOS 10 or later are supported.
----------------------------------------------------------------------------------------------------
Turn 6 | CUSTOMER | Tweet 9272 | Parent 9200
@AppleSupport Im using iPhone6s,it is installed with iOS 11.0.3 n battery drain problem is not resolved in it.When they resolve this issue in wht update?
----------------------------------------------------------------------------------------------------
Turn 7 | SUPPORT | Tweet 13192 | Parent 9272
@118712 We've received your DM and will be responding there shortly. Thank you.
----------------------------------------------------------------------------------------------------
Turn 8 | CUSTOMER | Tweet 9212 | Parent 9200
@AppleSupport Fix our iOS 11.03 battery issue. I’m on a 7 plus. @1257
----------------------------------------------------------------------------------------------------
Turn 9 | CUSTOMER | Tweet 9214 | Parent 9200
@AppleSupport I have the iPhone 7 Plus but i can’t do that 😢
----------------------------------------------------------------------------------------------------
Turn 10 | CUSTOMER | Tweet 9217 | Parent 9200
@AppleSupport I thought this update would fix the problem with appstore/itunes payments. I cant open some apps , i cant update any and i cant download any
----------------------------------------------------------------------------------------------------
Turn 11 | CUSTOMER | Tweet 9275 | Parent 9200
@AppleSupport I updated to iOS 11.1 and the phone get really warm and the battery dropped by 10% in 10 minuets when I watched videos in YouTube. iPhone 7+
----------------------------------------------------------------------------------------------------
Turn 12 | CUSTOMER | Tweet 9221 | Parent 9200
@AppleSupport When will fix the problem with activation (error 0xE8000013)? Or your phones are now disposable?
----------------------------------------------------------------------------------------------------
Turn 13 | CUSTOMER | Tweet 9223 | Parent 9200
@AppleSupport Hello, I have questions, what model of an iPhone X that selling on Apple store Australia. And its sim free unlocked or not.
----------------------------------------------------------------------------------------------------
Turn 14 | CUSTOMER | Tweet 38209 | Parent 9223
@AppleSupport And when is the summer free is going to be released?
----------------------------------------------------------------------------------------------------
Turn 15 | SUPPORT | Tweet 32370 | Parent 9214
@123171 Thanks for reaching out. We are always happy to help. Are you running iOS 11.1? If not, learn how here: https://t.co/80YRnjDFDk
----------------------------------------------------------------------------------------------------
Turn 16 | SUPPORT | Tweet 32356 | Parent 9212
@123167 Send us a DM and let us know how long your battery is lasting. We'll help. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 17 | SUPPORT | Tweet 33327 | Parent 9275
@123366 That should not be happening. Let us help. Tell us more about this in DM. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 18 | SUPPORT | Tweet 34691 | Parent 9221
@123523 Let's explore this in more details. Which device is exact iOS version are you using? When are you receiving this error?
----------------------------------------------------------------------------------------------------
Turn 19 | SUPPORT | Tweet 34658 | Parent 9217
@123515 We'd be happy to look into what's going on. Which device and iOS version are you using?
----------------------------------------------------------------------------------------------------
Turn 20 | CUSTOMER | Tweet 9229 | Parent 9200
@AppleSupport Where’s the update for this I️. Why does the letter l do that. Why do I️ have to use a lowercase L for a capital l?!
----------------------------------------------------------------------------------------------------
Turn 21 | SUPPORT | Tweet 36075 | Parent 9229
@123846 We'd be happy to look into this with you.  Please reach out to us via DM and we'll get started. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 22 | CUSTOMER | Tweet 32371 | Parent 32370
@AppleSupport Thanks! I have iOS 11.1 but i dont see the new emojis 😫
----------------------------------------------------------------------------------------------------
Turn 23 | SUPPORT | Tweet 32372 | Parent 32371
@123171 Thanks for following up. Send us a DM so we can look into this with you there. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 24 | SUPPORT | Tweet 38208 | Parent 38209
@124299 We’re also excited for the iPhone X! You can find out more information about available models here: https://t.co/yl9mQrnFWP
----------------------------------------------------------------------------------------------------
Turn 25 | CUSTOMER | Tweet 9233 | Parent 9200
@AppleSupport I am using iOS 11.0.3 but I was unable to get that option
----------------------------------------------------------------------------------------------------
Turn 26 | CUSTOMER | Tweet 32357 | Parent 32356
@AppleSupport No thanks. My fiancé works tech support for Apple. He complains about the same thing.
----------------------------------------------------------------------------------------------------
Turn 27 | SUPPORT | Tweet 44617 | Parent 9233
@125903 Are you referring to the echo effect in Messages? Let us know via DM and we'll look into it. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 28 | CUSTOMER | Tweet 44618 | Parent 44617
@AppleSupport Ya I was asking about it
----------------------------------------------------------------------------------------------------
Turn 29 | SUPPORT | Tweet 44619 | Parent 44618
@125903 Be sure you don't have Reduce Motion turned on: https://t.co/P2Obw7hkfD Send us a DM if you still can't find it. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 30 | CUSTOMER | Tweet 9239 | Parent 9200
@AppleSupport Have bug... if send to people that have old ios... LCD freze. Need to close. To go back 😏
----------------------------------------------------------------------------------------------------
Turn 31 | SUPPORT | Tweet 59602 | Parent 9239
@129597 Thanks for reaching out to us. To clarify, when using the Echo effect, does your Messages app become unresponsive?
----------------------------------------------------------------------------------------------------
Turn 32 | CUSTOMER | Tweet 59603 | Parent 59602
@AppleSupport Yes unresponsive, i have blank screan, need to force close, and open again messages. Thanks
----------------------------------------------------------------------------------------------------
Turn 33 | SUPPORT | Tweet 59604 | Parent 59603
@129597 Thanks for those details. To help isolate the issue, can you tell us which version of iOS 11 your device is on?
----------------------------------------------------------------------------------------------------
Turn 34 | CUSTOMER | Tweet 34659 | Parent 34658
@AppleSupport I am using Iphone 7 and iOS 11.1
----------------------------------------------------------------------------------------------------
Turn 35 | SUPPORT | Tweet 34660 | Parent 34659
@123515 DM us your country, and we'll continue working there. https://t.co/GDrqU22YpT
----------------------------------------------------------------------------------------------------
Turn 36 | CUSTOMER | Tweet 33328 | Parent 33327
@AppleSupport @123366 Mee too
----------------------------------------------------------------------------------------------------
Turn 37 | CUSTOMER | Tweet 33329 | Parent 33328
@123367 @AppleSupport @123366 Mee to same issue
----------------------------------------------------------------------------------------------------

In [27]:
# ============================================
# Cell 23 — Measure conversation branching
# ============================================

branching = (
    conversation_df
    .groupby("parent_tweet_id")
    .size()
    .sort_values(ascending=False)
)

branching = branching[branching.index != ""]

print("Tweets with multiple direct replies:")
print((branching > 1).sum())

print("\nMaximum direct replies to one tweet:")
print(branching.max())

print("\nTop 20 most-replied-to tweets:")

print(
    branching.head(20).to_string()
)

Tweets with multiple direct replies:
150

Maximum direct replies to one tweet:
11

Top 20 most-replied-to tweets:
parent_tweet_id
9200      11
117940     7
33360      6
39661      6
40491      6
125796     4
117939     4
53607      4
61348      4
12573      3
39605      3
29554      3
50051      3
55938      3
90550      3
94772      3
23095      2
37656      2
39649      2
38869      2

In [30]:
# ============================================
# Cell 25 — Correct AppleSupport branching analysis
# ============================================

apple_parent_counts = (
    conversation_df[
        conversation_df["parent_tweet_id"] != ""
    ]
    .groupby("parent_tweet_id")
    .size()
    .sort_values(ascending=False)
)

apple_branch_points = apple_parent_counts[
    apple_parent_counts > 1
]

print(
    "Parent tweets with multiple direct replies:",
    len(apple_branch_points)
)

print(
    "\nMaximum direct replies:",
    apple_parent_counts.max()
    if len(apple_parent_counts) > 0
    else 0
)

print("\nTop branching parent tweets:")
print(
    apple_branch_points.head(20).to_string()
)

Parent tweets with multiple direct replies: 150

Maximum direct replies: 11

Top branching parent tweets:
parent_tweet_id
9200      11
117940     7
33360      6
39661      6
40491      6
117939     4
125796     4
53607      4
61348      4
39605      3
29554      3
12573      3
50051      3
55938      3
90550      3
94772      3
125806     2
23095      2
37656      2
39649      2

In [31]:
# ============================================
# Cell 26 — Mark branching tweets
# ============================================

conversation_df["direct_reply_count"] = (
    conversation_df["tweet_id"]
    .map(apple_parent_counts)
    .fillna(0)
    .astype(int)
)

conversation_df["is_branch_point"] = (
    conversation_df["direct_reply_count"] > 1
)

print(
    "Tweets that are branch points:",
    conversation_df["is_branch_point"].sum()
)

print("\nBranching tweets:")
print(
    conversation_df[
        conversation_df["is_branch_point"]
    ][
        [
            "conversation_id",
            "tweet_id",
            "role",
            "direct_reply_count",
            "text_raw"
        ]
    ]
    .sort_values("direct_reply_count", ascending=False)
    .head(20)
    .to_string(index=False)
)

Tweets that are branch points: 150

Branching tweets:
conversation_id tweet_id     role  direct_reply_count                                                                                                                                                                                                                                                      text_raw
           9200     9200  support                  11                                                                                                                   It’s attack of the new emoji. \n\nUnleash a zombie emoji-pocalypse this Halloween with the echo effect in Messages. https://t.co/P4l8dMu9dj
         117940   117940 customer                   7                                                                                              Hi @AppleSupport, could you pls explain why, since I downloaded yr iOS update, my iPhone crashes at 10%,  20%, even 40% battery? Massively inconvenient at best.
          40514    40491  support                   6                                                                                                                @124882 If you're having issues with your iPhone battery life, we'd like to help. Update to iOS 11.1 &amp; let us know if that persists after.
          33360    33360 customer                   6                                                                                                                                   Did anyone do the update @115858 and now your phone is having charging issues? Phones not even a year old. Driving me crazy
          39668    39661  support                   6                                                                                                                                      @124681 Thanks for reaching out.  Let's get you in touch with an Apple Online Store Advisor at: https://t.co/8yjRd1Xo0i.
         117940   117939 customer                   4                                                                                                                                                              @AppleSupport As it seems to be a widespread problem, perhaps you can tell me by public message.
          61348    61348  support                   4                                                                                                                                          Accidentally deleted an app? Here's how to find and reinstall your purchased apps in iOS 11. https://t.co/wvOgLJh2Kz
         125801   125796  support                   4                                                                                                                                    @144228 Hi. We are here to help. Please reach out to our Apple TV support team with this link:\n\n https://t.co/IBIY3vMgPj
          53612    53607  support                   4                                                                                                                                  @128119 We're happy to help with this. Here are instructions: https://t.co/xuZEqdPMFW Let us know if you have any questions.
          39604    39605  support                   3                                                                                                                          @124660 First, let's have you update to iOS 11.1: https://t.co/80YRnjDFDk Let us know if the issue continues after updating, please.
          94776    94772  support                   3                                    @136589 We can definitely look into this with you. Are you only experiencing this behavior in the Contacts app? Which iOS are you running currently? You can go to Settings &gt; General &gt; About to locate the version.
          90554    90550  support                   3                               @135596 Hey, can you tell us what's going on with the Mail app, specifically? Also, to clarify, are you referring to the native Mail app or a third-party mail app? Let us know some details and we'll work towards a solution.
          55942    55938  support                   3                                                                                                                      @128689 We're delighted to help. What's going on with your apps? Are they unable to open? Let us know a little more about the situation.
          50050    50051  support                   3                                                                                                                                 @127206 Thanks. If you play a song, does the info appear? Does the info and controls gray out after a certain amount of time?
          12577    12573  support                   3                                                                                                                                                         @118510 We'd love to help! Which version of iOS are you using? Which keyboards do you have installed?
          29558    29554  support                   3                                                                                 @122491 We understand how important your iPhone is, and we're here to help. Send us a DM, and we'll take a closer look at your device together there. https://t.co/GDrqU22YpT
          11101    11098  support                   2                                                                                                                                                                @118095 We're here to help. Did this happen after a specific update, or just recently? Thanks!
         110950   110947  support                   2                                                                                                        @140681 We'd like to assist with this. Which version of iTunes are you using? https://t.co/g2HM9lnith\n\nWhat Windows version are you running as well?
         107352   107349  support                   2 @139842 Are you using Control Center or Settings on your iPhone to turn Wi-Fi off? If you're using Control Center, that works a bit differently in iOS 11: https://t.co/G7BHuQnDS6 Let us know in DM if you have any other questions. https://t.co/GDrqU22YpT
         109011   109008  support                   2                                                                               @140191 We'd like to know more about the trouble you're having so we can help get your Music sharing working again. What was happening when you try to share a song to Twitter?

In [32]:
# ============================================
# Cell 27 — Inspect processed data files
# ============================================

from pathlib import Path

PROCESSED_DIR = Path("../data/processed")

print("Processed directory:", PROCESSED_DIR.resolve())

if not PROCESSED_DIR.exists():
    print("\nERROR: data/processed/ does not exist.")
else:
    files = sorted(
        [
            p for p in PROCESSED_DIR.rglob("*")
            if p.is_file()
        ]
    )

    print("\nFiles found:", len(files))

    for file in files:
        print(file.relative_to(PROCESSED_DIR))

Processed directory: D:\AgentCustomerSupport\hiver-sde-intern\data\processed

Files found: 1
.gitkeep

In [35]:
# ============================================
# Cell 29 — Load Notebook 01 cleaned dataset
# ============================================

cleaned_customers = pd.read_csv(
    "../data/processed/apple_customer_tweets_cleaned.csv"
)

print("Cleaned customer dataset shape:", cleaned_customers.shape)

print("\nColumns:")
print(cleaned_customers.columns.tolist())

print("\nSample:")
print(
    cleaned_customers[
        ["tweet_id", "text_clean", "language", "quality_flag"]
    ].head().to_string(index=False)
)

Cleaned customer dataset shape: (3020, 11)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'text_raw', 'text_clean', 'language', 'quality_flag']

Sample:
 tweet_id                                                                            text_clean language         quality_flag
      697                              The newest update. I made sure to download it yesterday.       en                 KEEP
      698                                                                                   NaN  unknown EMPTY_AFTER_CLEANING
      700 why are my I’s changing not showing up correctly on any of my social media platforms?       en                 KEEP
      702                        Tried resetting my settings .. restarting my phone .. all that       en                 KEEP
      704                                                            This is what it looks like       en                 KEEP

In [34]:
# ============================================
# Cell 29 — Validate cleaned text
# ============================================

print("Total tweets:", len(conversation_df))

print(
    "\nEmpty cleaned texts:",
    (conversation_df["text_clean"] == "").sum()
)

print(
    "Texts changed by cleaning:",
    (
        conversation_df["text_raw"]
        != conversation_df["text_clean"]
    ).sum()
)

print("\nCleaning examples:")

changed = conversation_df[
    conversation_df["text_raw"]
    != conversation_df["text_clean"]
]

print(
    changed[
        ["tweet_id", "role", "text_raw", "text_clean"]
    ]
    .head(10)
    .to_string(index=False)
)

Total tweets: 6836

Empty cleaned texts: 36
Texts changed by cleaning: 6820

Cleaning examples:
tweet_id     role                                                                                                                                                                                                                                                                                                           text_raw                                                                                                                                                                                                                                                              text_clean
  100245 customer                                                    What is this @AppleSupport? since I upgraded with this $hi&amp;*y #macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!                           What is this ? since I upgraded with this $hi&*y macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!
  100244  support                                                                                                        @137967 We'd like to help. Does this seem to persist when using multiple apps? Have you tried rebooting to see if that helps? Send us a DM, we'll be glad to work on this with you. https://t.co/GDrqU22YpT                                                                                             We'd like to help. Does this seem to persist when using multiple apps? Have you tried rebooting to see if that helps? Send us a DM, we'll be glad to work on this with you.
  100243 customer                                                                                                                                                                                         @AppleSupport I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.                                                                                                                                                            I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.
  100241  support                                                                                                                                                                                          @137967 Either way, let us know what happens via DM. We want to make sure this is fully resolved. https://t.co/GDrqU22YpT                                                                                                                                                                               Either way, let us know what happens via DM. We want to make sure this is fully resolved.
  100242 customer                                                                                                                                                                                                              @AppleSupport for now I just restarted, it doesn't lag yet. I will let you know when it happen again.                                                                                                                                                                                 for now I just restarted, it doesn't lag yet. I will let you know when it happen again.
  100540 customer                                                                                                                                                                                                                                  My iPhone been moving slow af the past couple weeks. I need answers @AppleSupport                                                                                                                                                                                                     My iPhone been moving slow af the past couple weeks. I need answers
  100539  support                                                 @137986 We’d love to help with the performance of your iPhone. To start, please send us a DM confirming which iPhone and exact software version you’re using. You can tap Settings &gt; General &gt; About to locate the software version. https://t.co/GDrqU22YpT                                            We’d love to help with the performance of your iPhone. To start, please send us a DM confirming which iPhone and exact software version you’re using. You can tap Settings > General > About to locate the software version.
  101228 customer                                                                                                                                                                                                                                                           Dear god not again,@AppleSupport https://t.co/5Zf0Mnd6SI                                                                                                                                                                                                                                                     Dear god not again,
  101227  support @138151 We want to make sure your words and texts are coming out as expected. What version of the iOS software do you currently have installed on your device? You can find this in Settings &gt; General &gt; About.  \n\nPlease send a DM with this information so we can better assist. https://t.co/GDrqU22YpT We want to make sure your words and texts are coming out as expected. What version of the iOS software do you currently have installed on your device? You can find this in Settings > General > About. Please send a DM with this information so we can better assist.
  101231 customer                                                                                                                                                                                                                         Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.                                                                                                                                                                                      Noticed a bug on my iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.

In [36]:
# ============================================
# Cell 30 — Load cleaned customer dataset
# ============================================

cleaned_customers = pd.read_csv(
    "../data/processed/apple_customer_tweets_cleaned.csv"
)

print("Cleaned customer dataset shape:", cleaned_customers.shape)

print("\nColumns:")
print(cleaned_customers.columns.tolist())

print("\nSample:")
print(
    cleaned_customers[
        ["tweet_id", "text_clean", "language", "quality_flag"]
    ].head().to_string(index=False)
)

Cleaned customer dataset shape: (3020, 11)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id', 'text_raw', 'text_clean', 'language', 'quality_flag']

Sample:
 tweet_id                                                                            text_clean language         quality_flag
      697                              The newest update. I made sure to download it yesterday.       en                 KEEP
      698                                                                                   NaN  unknown EMPTY_AFTER_CLEANING
      700 why are my I’s changing not showing up correctly on any of my social media platforms?       en                 KEEP
      702                        Tried resetting my settings .. restarting my phone .. all that       en                 KEEP
      704                                                            This is what it looks like       en                 KEEP

In [38]:
# ============================================
# Cell 31 — Attach Notebook 01 cleaning fields
# ============================================

# Normalize tweet IDs to strings on both datasets
conversation_df["tweet_id"] = (
    conversation_df["tweet_id"]
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
)

cleaned_customers["tweet_id"] = (
    cleaned_customers["tweet_id"]
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
)

# Keep only the cleaning fields from Notebook 01
cleaning_fields = cleaned_customers[
    ["tweet_id", "text_clean", "language", "quality_flag"]
].copy()

# Remove the temporary text_clean created earlier in Notebook 02
conversation_df = conversation_df.drop(
    columns=["text_clean"],
    errors="ignore"
)

# Merge Notebook 01 cleaning results
conversation_df = conversation_df.merge(
    cleaning_fields,
    on="tweet_id",
    how="left"
)

print("Conversation shape:", conversation_df.shape)

print("\nCleaning fields:")
print(
    conversation_df[
        ["tweet_id", "role", "text_raw", "text_clean",
         "language", "quality_flag"]
    ].head(10).to_string(index=False)
)

print("\nMissing cleaning fields:")
print(
    conversation_df[
        ["text_clean", "language", "quality_flag"]
    ].isna().sum()
)

Conversation shape: (6836, 14)

Cleaning fields:
tweet_id     role                                                                                                                                                                                                                                                                                                           text_raw                                                                                                                                                                                                                                    text_clean language quality_flag
  100245 customer                                                    What is this @AppleSupport? since I upgraded with this $hi&amp;*y #macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW! What is this ? since I upgraded with this $hi&*y macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!       en         KEEP
  100244  support                                                                                                        @137967 We'd like to help. Does this seem to persist when using multiple apps? Have you tried rebooting to see if that helps? Send us a DM, we'll be glad to work on this with you. https://t.co/GDrqU22YpT                                                                                                                                                                                                                                           NaN      NaN          NaN
  100243 customer                                                                                                                                                                                         @AppleSupport I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.                                                                                                                                  I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.       en         KEEP
  100241  support                                                                                                                                                                                          @137967 Either way, let us know what happens via DM. We want to make sure this is fully resolved. https://t.co/GDrqU22YpT                                                                                                                                                                                                                                           NaN      NaN          NaN
  100242 customer                                                                                                                                                                                                              @AppleSupport for now I just restarted, it doesn't lag yet. I will let you know when it happen again.                                                                                                                                                       for now I just restarted, it doesn't lag yet. I will let you know when it happen again.       en         KEEP
  100540 customer                                                                                                                                                                                                                                  My iPhone been moving slow af the past couple weeks. I need answers @AppleSupport                                                                                                                                                                           My iPhone been moving slow af the past couple weeks. I need answers       en         KEEP
  100539  support                                                 @137986 We’d love to help with the performance of your iPhone. To start, please send us a DM confirming which iPhone and exact software version you’re using. You can tap Settings &gt; General &gt; About to locate the software version. https://t.co/GDrqU22YpT                                                                                                                                                                                                                                           NaN      NaN          NaN
  101228 customer                                                                                                                                                                                                                                                           Dear god not again,@AppleSupport https://t.co/5Zf0Mnd6SI                                                                                                                                                                                                                           Dear god not again,  unknown         KEEP
  101227  support @138151 We want to make sure your words and texts are coming out as expected. What version of the iOS software do you currently have installed on your device? You can find this in Settings &gt; General &gt; About.  \n\nPlease send a DM with this information so we can better assist. https://t.co/GDrqU22YpT                                                                                                                                                                                                                                           NaN      NaN          NaN
  101231 customer                                                                                                                                                                                                                         Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.                                                                                                                                                                                                                                           NaN      NaN          NaN

Missing cleaning fields:
text_clean      3873
language        3838
quality_flag    3838
dtype: int64

In [39]:
# ============================================
# Cell 32 — Check customer coverage
# ============================================

customer_rows = conversation_df[
    conversation_df["role"] == "customer"
].copy()

missing_customer_cleaning = customer_rows[
    customer_rows["quality_flag"].isna()
]

print("Total customer tweets in conversations:",
      len(customer_rows))

print("Customer tweets with Notebook 01 cleaning:",
      customer_rows["quality_flag"].notna().sum())

print("Customer tweets missing Notebook 01 cleaning:",
      len(missing_customer_cleaning))

print("\nMissing customer examples:")

print(
    missing_customer_cleaning[
        ["tweet_id", "text_raw"]
    ].head(20).to_string(index=False)
)

Total customer tweets in conversations: 3729
Customer tweets with Notebook 01 cleaning: 2998
Customer tweets missing Notebook 01 cleaning: 731

Missing customer examples:
tweet_id                                                                                                                                                                                                                                                                                text_raw
  101231                                                                                                                                                                                              Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.
  101239                                                                                            @115858 Just because you're releasing new phones doesn't mean you should stop making my current iPhone stop working. I have a contract and cannot just purchase a new phone every 12 months.
  101249 My Apple account has been broken for more then 10 weeks now; family sharing doesn’t work, can’t enable it anymore. Can’t share calendars with girlfriend, she doesn’t have access to Apple Music via my family plan (which I do still pay for), etc. 10 weeks and it still isn’t fixed.
  101248                       @115858 @116333 My Apple account’s Family Sharing has been broken for 10 weeks now, and support doesn’t seem any closer to fixing this. When asked for alternative solutions the answer is to have yet more patience. This is horrible :( https://t.co/1W9S7hFGwC
  101259                                                                                                                                                                                                                Only to break File Sharing! Sigh :-( /cc @115858 https://t.co/QGw2mX4igg
  101285                                                                                                                                         Anybody else getting really annoyed with trying to type “it” and constantly having it autocorrect to I.T ???? What’s good with that @115858 ???
  103151                                                                                                                                                                              @115858 my iPhone gets slower and slower with every update and for this I thank you, keep up the good work
  103166                                                                                                                                                                                                                         @115858 iPhone X orange camera problem? https://t.co/HooDTPyYNl
  103184                                                                                                                                                                          The recent IOS update has slowed my 6S down to a crawl. I am seriously reconsidering my commitment to @115858.
  103186                                                                                                @115858  thanks for making my phone backup fucking useless, cant download it back onto my phone because of a shitty ''two-factior verification' with my fucking old number, load a shite
  103207                                                                                                                                                     Yo @115858 you can make my phone not send/receive texts all you want I’m not buying your overpriced piece of glass #CanYouHearMeNow
  103210                                                                                                                                                                                                         OMFG @115858 this is my 3rd pair of fkn headphones that have crapped out on me.
  103215                                                                                                                                                                                                                    @116333 Please help me, apple call centre in India unable to support
  103224                                                                                       "Keep in mind that this version will still be available to all users as a manual update from the App Store"...@118936 @115858.. the app store does not behave like this. Please can we fix this 🙏
  103228                                                                                                 A Apple, que vende IPhone, é um lixo no Brasil. Lixo que faz buscar o “Bombita” do Darin nos “Relatos Selvagens. Irei no dantesco calvário em que me meti até o fim pra depois relatar.
  103227                                                                                                                                                                                                     @138713 Estou com problemas com a querida @115858 tbem e tive que acionar o Procon.
  103235                      @115858 Estoy muy decepcionado con la calidad de la compra online. Despues de esperar tanto tiempo para el IPhone X + AppleWatch teneis problemas con el sistema de pago. Muy muy decepcionado !!! Espero que esto no afecte a la fecha de entrega de mi pedido!!!
  103253                                                                                                                                                                                                              iPad Pro + iOS 11. Use Apple Pencil to create expressive multimedia notes.
  103252                                                                                                                                                                @115858 The upgrade is messing up with FaceTime. I had to restart 4 times in one day because it freezes. Fix this please
  105315                                                                                                                                                                                             Anybody else having a problem uploading  screenshotted pictures from their #iphone? @115858

In [40]:
# ============================================
# Cell 33 — Validate Notebook 01 cleaning coverage
# ============================================

customer_rows = conversation_df[
    conversation_df["role"] == "customer"
].copy()

covered_customers = customer_rows[
    customer_rows["quality_flag"].notna()
]

uncovered_customers = customer_rows[
    customer_rows["quality_flag"].isna()
]

print("Customer tweets in reconstructed conversations:",
      len(customer_rows))

print("Customer tweets covered by Notebook 01:",
      len(covered_customers))

print("Customer tweets not covered by Notebook 01:",
      len(uncovered_customers))

print(
    "\nCoverage:",
    round(len(covered_customers) / len(customer_rows) * 100, 2),
    "%"
)

print("\nUncovered tweets are retained as raw conversation context.")

Customer tweets in reconstructed conversations: 3729
Customer tweets covered by Notebook 01: 2998
Customer tweets not covered by Notebook 01: 731

Coverage: 80.4 %

Uncovered tweets are retained as raw conversation context.

In [41]:
# ============================================
# Cell 34 — Branch-aware conversation check
# ============================================

branch_summary = (
    conversation_df[
        conversation_df["direct_reply_count"] > 1
    ]
    .groupby("conversation_id")
    .agg(
        branch_points=("tweet_id", "count"),
        max_direct_replies=("direct_reply_count", "max"),
        total_tweets=("tweet_id", "size")
    )
    .sort_values(
        ["max_direct_replies", "total_tweets"],
        ascending=False
    )
)

print("Conversation components containing branch points:",
      len(branch_summary))

print("\nTop branching components:")

print(
    branch_summary.head(15).to_string()
)

Conversation components containing branch points: 132

Top branching components:
                 branch_points  max_direct_replies  total_tweets
conversation_id
9200                         1                  11             1
117940                       3                   7             3
40514                        3                   6             3
33360                        1                   6             1
39668                        1                   6             1
125801                       1                   4             1
53612                        1                   4             1
61348                        1                   4             1
29558                        2                   3             2
39604                        2                   3             2
12577                        1                   3             1
50050                        1                   3             1
55942                        1                   3             1
90554                        1                   3             1
94776                        1                   3             1

In [42]:
# ============================================
# Cell 35 — Inspect a branching component
# ============================================

branch_id = "9200"

branch_example = conversation_df[
    conversation_df["conversation_id"] == branch_id
].copy()

print("Tweets currently inside component:", len(branch_example))

print("\nTweets:")
print(
    branch_example[
        [
            "tweet_id",
            "role",
            "text_raw",
            "parent_tweet_id",
            "direct_reply_count",
            "is_branch_point"
        ]
    ].to_string(index=False)
)

print("\nAvailable direct children from child_map:")

children = child_map.get(branch_id, [])

print("Number of children:", len(children))
print("Child tweet IDs:", children)

Tweets currently inside component: 37

Tweets:
tweet_id     role                                                                                                                                                   text_raw parent_tweet_id  direct_reply_count  is_branch_point
    9200  support                It’s attack of the new emoji. \n\nUnleash a zombie emoji-pocalypse this Halloween with the echo effect in Messages. https://t.co/P4l8dMu9dj                                  11             True
    9198 customer                                                 @AppleSupport Does the person you send it too also have to have a iPhone to see this?I see it on my phone.            9200                   1            False
    9196  support                                @117654 Great question. They must have a device with iOS 10 or later. Here's some more information: https://t.co/GCtGkHihKu            9198                   1            False
    9197 customer                                                                            @AppleSupport But would it work with another phone brand?Like LG galaxy phones?            9196                   1            False
    9199  support                                                                                        @117654 Currently, only iPhones with iOS 10 or later are supported.            9197                   0            False
    9272 customer  @AppleSupport Im using iPhone6s,it is installed with iOS 11.0.3 n battery drain problem is not resolved in it.When they resolve this issue in wht update?            9200                   1            False
   13192  support                                                                            @118712 We've received your DM and will be responding there shortly. Thank you.            9272                   0            False
    9212 customer                                                                                      @AppleSupport Fix our iOS 11.03 battery issue. I’m on a 7 plus. @1257            9200                   1            False
    9214 customer                                                                                               @AppleSupport I have the iPhone 7 Plus but i can’t do that 😢            9200                   1            False
    9217 customer @AppleSupport I thought this update would fix the problem with appstore/itunes payments. I cant open some apps , i cant update any and i cant download any            9200                   1            False
    9275 customer @AppleSupport I updated to iOS 11.1 and the phone get really warm and the battery dropped by 10% in 10 minuets when I watched videos in YouTube. iPhone 7+            9200                   1            False
    9221 customer                                             @AppleSupport When will fix the problem with activation (error 0xE8000013)? Or your phones are now disposable?            9200                   1            False
    9223 customer                  @AppleSupport Hello, I have questions, what model of an iPhone X that selling on Apple store Australia. And its sim free unlocked or not.            9200                   1            False
   38209 customer                                                                                         @AppleSupport And when is the summer free is going to be released?            9223                   1            False
   32370  support                    @123171 Thanks for reaching out. We are always happy to help. Are you running iOS 11.1? If not, learn how here: https://t.co/80YRnjDFDk            9214                   1            False
   32356  support                                                 @123167 Send us a DM and let us know how long your battery is lasting. We'll help. https://t.co/GDrqU22YpT            9212                   1            False
   33327  support                                                  @123366 That should not be happening. Let us help. Tell us more about this in DM. https://t.co/GDrqU22YpT            9275                   1            False
   34691  support                            @123523 Let's explore this in more details. Which device is exact iOS version are you using? When are you receiving this error?            9221                   0            False
   34658  support                                                            @123515 We'd be happy to look into what's going on. Which device and iOS version are you using?            9217                   1            False
    9229 customer                         @AppleSupport Where’s the update for this I️. Why does the letter l do that. Why do I️ have to use a lowercase L for a capital l?!            9200                   1            False
   36075  support                            @123846 We'd be happy to look into this with you.  Please reach out to us via DM and we'll get started. https://t.co/GDrqU22YpT            9229                   0            False
   32371 customer                                                                                      @AppleSupport Thanks! I have iOS 11.1 but i dont see the new emojis 😫           32370                   1            False
   32372  support                                             @123171 Thanks for following up. Send us a DM so we can look into this with you there. https://t.co/GDrqU22YpT           32371                   0            False
   38208  support                        @124299 We’re also excited for the iPhone X! You can find out more information about available models here: https://t.co/yl9mQrnFWP           38209                   0            False
    9233 customer                                                                                    @AppleSupport I am using iOS 11.0.3 but I was unable to get that option            9200                   1            False
   32357 customer                                                        @AppleSupport No thanks. My fiancé works tech support for Apple. He complains about the same thing.           32356                   0            False
   44617  support                               @125903 Are you referring to the echo effect in Messages? Let us know via DM and we'll look into it. https://t.co/GDrqU22YpT            9233                   1            False
   44618 customer                                                                                                                     @AppleSupport Ya I was asking about it           44617                   1            False
   44619  support           @125903 Be sure you don't have Reduce Motion turned on: https://t.co/P2Obw7hkfD Send us a DM if you still can't find it. https://t.co/GDrqU22YpT           44618                   0            False
    9239 customer                                                    @AppleSupport Have bug... if send to people that have old ios... LCD freze. Need to close. To go back 😏            9200                   1            False
   59602  support                                 @129597 Thanks for reaching out to us. To clarify, when using the Echo effect, does your Messages app become unresponsive?            9239                   1            False
   59603 customer                                                  @AppleSupport Yes unresponsive, i have blank screan, need to force close, and open again messages. Thanks           59602                   1            False
   59604  support                                    @129597 Thanks for those details. To help isolate the issue, can you tell us which version of iOS 11 your device is on?           59603                   0            False
   34659 customer                                                                                                             @AppleSupport I am using Iphone 7 and iOS 11.1           34658                   1            False
   34660  support                                                                      @123515 DM us your country, and we'll continue working there. https://t.co/GDrqU22YpT           34659                   0            False
   33328 customer                                                                                                                              @AppleSupport @123366 Mee too           33327                   1            False
   33329 customer                                                                                                            @123367 @AppleSupport @123366 Mee to same issue           33328                   0            False

Available direct children from child_map:
Number of children: 11
Child tweet IDs: ['9198', '9272', '9212', '9214', '9275', '9217', '9221', '9229', '9223', '9233', '9239']

In [43]:
# ============================================
# Cell 36 — Validate graph coverage for AppleSupport
# ============================================

conversation_tweet_ids = set(
    conversation_df["tweet_id"].astype(str)
)

graph_children_in_subset = 0
graph_children_outside_subset = 0

for parent_id, children in child_map.items():
    if parent_id in conversation_tweet_ids:
        for child_id in children:
            if child_id in conversation_tweet_ids:
                graph_children_in_subset += 1
            else:
                graph_children_outside_subset += 1

print("Parent-child edges inside AppleSupport subset:",
      graph_children_in_subset)

print("Parent-child edges pointing outside subset:",
      graph_children_outside_subset)

print(
    "\nTotal parent-child edges from AppleSupport parents:",
    graph_children_in_subset + graph_children_outside_subset
)

Parent-child edges inside AppleSupport subset: 4770
Parent-child edges pointing outside subset: 0

Total parent-child edges from AppleSupport parents: 4770

In [44]:
# ============================================
# Cell 37 — Build branch-aware thread IDs
# ============================================

from collections import defaultdict

# Map each tweet to its children that are actually
# present in the AppleSupport conversation subset
subset_children = defaultdict(list)

for _, row in conversation_df.iterrows():
    parent_id = row["parent_tweet_id"]

    if parent_id and parent_id in conversation_tweet_ids:
        subset_children[parent_id].append(row["tweet_id"])


def build_threads(df):
    """
    Create branch-aware thread IDs from the actual
    parent-child graph.

    A new thread starts from a root tweet or from
    every child of a branching parent.
    """

    thread_records = []

    for root_id, group in df.groupby("conversation_id"):
        group_ids = set(group["tweet_id"])

        # Find the root tweet(s) of this component
        roots = [
            tweet_id
            for tweet_id in group_ids
            if not group.loc[
                group["tweet_id"] == tweet_id,
                "parent_tweet_id"
            ].iloc[0]
        ]

        # DFS through the graph
        stack = []

        for root in roots:
            stack.append((root, [root]))

        while stack:
            current, path = stack.pop()

            children = [
                child
                for child in subset_children.get(current, [])
                if child in group_ids
            ]

            if not children:
                thread_records.append({
                    "conversation_id": root_id,
                    "thread_path": path
                })
            else:
                for child in children:
                    stack.append(
                        (child, path + [child])
                    )

    return thread_records


thread_records = build_threads(conversation_df)

print("Branch-aware threads created:", len(thread_records))

print("\nSample thread paths:")

for record in thread_records[:10]:
    print(
        record["conversation_id"],
        "→",
        " → ".join(record["thread_path"])
    )

Branch-aware threads created: 2247

Sample thread paths:
100245 → 100245 → 100244 → 100243 → 100241 → 100242
100540 → 100540 → 100539
101228 → 101228 → 101227
101231 → 101231 → 101230
101234 → 101234 → 101232 → 101233 → 101235 → 101236 → 101237
101239 → 101239 → 101238
101241 → 101241 → 101240
101244 → 101244 → 101243
101246 → 101246 → 101245
101249 → 101249 → 101248 → 101247

In [45]:
# ============================================
# Cell 38 — Validate branch-aware threads
# ============================================

threads_9200 = [
    record
    for record in thread_records
    if record["conversation_id"] == "9200"
]

print("Threads generated from component 9200:",
      len(threads_9200))

print("\nThread paths from 9200:")

for i, record in enumerate(threads_9200, start=1):
    print(
        f"Thread {i}:",
        " → ".join(record["thread_path"])
    )

Threads generated from component 9200: 11

Thread paths from 9200:
Thread 1: 9200 → 9239 → 59602 → 59603 → 59604
Thread 2: 9200 → 9233 → 44617 → 44618 → 44619
Thread 3: 9200 → 9229 → 36075
Thread 4: 9200 → 9223 → 38209 → 38208
Thread 5: 9200 → 9221 → 34691
Thread 6: 9200 → 9275 → 33327 → 33328 → 33329
Thread 7: 9200 → 9217 → 34658 → 34659 → 34660
Thread 8: 9200 → 9214 → 32370 → 32371 → 32372
Thread 9: 9200 → 9212 → 32356 → 32357
Thread 10: 9200 → 9272 → 13192
Thread 11: 9200 → 9198 → 9196 → 9197 → 9199

In [46]:
# ============================================
# Cell 39 — Attach branch-aware thread IDs
# ============================================

thread_map = {}

for index, record in enumerate(thread_records, start=1):

    thread_id = (
        f"{record['conversation_id']}_thread_{index}"
    )

    for position, tweet_id in enumerate(record["thread_path"], start=1):
        thread_map[tweet_id] = {
            "thread_id": thread_id,
            "thread_position": position
        }

# Attach thread metadata
conversation_df["thread_id"] = (
    conversation_df["tweet_id"]
    .map(lambda x: thread_map.get(x, {}).get("thread_id"))
)

conversation_df["thread_position"] = (
    conversation_df["tweet_id"]
    .map(lambda x: thread_map.get(x, {}).get("thread_position"))
)

print("Unique branch-aware threads:",
      conversation_df["thread_id"].nunique())

print(
    "\nMissing thread IDs:",
    conversation_df["thread_id"].isna().sum()
)

print("\nSample:")
print(
    conversation_df[
        [
            "conversation_id",
            "thread_id",
            "thread_position",
            "tweet_id",
            "role",
            "text_raw"
        ]
    ].head(15).to_string(index=False)
)

Unique branch-aware threads: 2247

Missing thread IDs: 26

Sample:
conversation_id       thread_id  thread_position tweet_id     role                                                                                                                                                                                                                                                                                                             text_raw
         100245 100245_thread_1              1.0   100245 customer                                                      What is this @AppleSupport? since I upgraded with this $hi&amp;*y #macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!
         100245 100245_thread_1              2.0   100244  support                                                                                                          @137967 We'd like to help. Does this seem to persist when using multiple apps? Have you tried rebooting to see if that helps? Send us a DM, we'll be glad to work on this with you. https://t.co/GDrqU22YpT
         100245 100245_thread_1              3.0   100243 customer                                                                                                                                                                                           @AppleSupport I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.
         100245 100245_thread_1              4.0   100241  support                                                                                                                                                                                            @137967 Either way, let us know what happens via DM. We want to make sure this is fully resolved. https://t.co/GDrqU22YpT
         100245 100245_thread_1              5.0   100242 customer                                                                                                                                                                                                                @AppleSupport for now I just restarted, it doesn't lag yet. I will let you know when it happen again.
         100540 100540_thread_2              1.0   100540 customer                                                                                                                                                                                                                                    My iPhone been moving slow af the past couple weeks. I need answers @AppleSupport
         100540 100540_thread_2              2.0   100539  support                                                   @137986 We’d love to help with the performance of your iPhone. To start, please send us a DM confirming which iPhone and exact software version you’re using. You can tap Settings &gt; General &gt; About to locate the software version. https://t.co/GDrqU22YpT
         101228 101228_thread_3              1.0   101228 customer                                                                                                                                                                                                                                                             Dear god not again,@AppleSupport https://t.co/5Zf0Mnd6SI
         101228 101228_thread_3              2.0   101227  support   @138151 We want to make sure your words and texts are coming out as expected. What version of the iOS software do you currently have installed on your device? You can find this in Settings &gt; General &gt; About.  \n\nPlease send a DM with this information so we can better assist. https://t.co/GDrqU22YpT
         101231 101231_thread_4              1.0   101231 customer                                                                                                                                                                                                                           Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.
         101231 101231_thread_4              2.0   101230  support                                                                                                                                                                          @138152 We can assist you. Thanks for bringing this to our attention. If you restart your device and test the issue again, does it persist?
         101234 101234_thread_5              1.0   101234 customer @AppleSupport leg dit even uit? Dit is mijn oud e-mail adress/apple id, sinds een recente update krijg ik constant deze melding. Ik heb sinds paar jaar een nieuw e-mail adres en ook een apple id op dit adres. Ik was (nog altijd) het wachtwoord kwijt van het oude e-mail &amp; apple-id https://t.co/5GWgrlFu74
         101234 101234_thread_5              2.0   101232  support                                                                                                                                                                                        @138153 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj
         101234 101234_thread_5              3.0   101233 customer                                          @AppleSupport Since a recent update i’m constantly getting these notifications about my old apple ID /e-mail adress, wich i’ve lost the pw years ago. I allready got a new account and e-mail, but it doesn’t appear anywhere, alltho i can still acces the app store etc..
         101234 101234_thread_5              4.0   101235  support                                 @138153 We'd be happy to look into why that Apple ID is popping up now, and see what we need to do to get it to stop. To get started, can you tell us which iPhone and iOS version you're using? You can find the version by going to Settings &gt; General &gt; About &gt; Version.

In [47]:
# ============================================
# Cell 40 — Diagnose missing thread IDs
# ============================================

missing_threads = conversation_df[
    conversation_df["thread_id"].isna()
].copy()

print("Tweets missing thread_id:",
      len(missing_threads))

print("\nMissing tweets:")

print(
    missing_threads[
        [
            "conversation_id",
            "tweet_id",
            "role",
            "parent_tweet_id",
            "text_raw"
        ]
    ].to_string(index=False)
)

print("\nAffected conversation components:")

print(
    missing_threads["conversation_id"]
    .value_counts()
    .to_string()
)

Tweets missing thread_id: 26

Missing tweets:
conversation_id tweet_id     role parent_tweet_id                                                                                                                                                                                                                                                                                   text_raw
          11651    11651  support           11653                                                                                                                                                                  @118247 Thanks for reaching out to us. Can you please let us know if you have updated to iOS 11.1? It was released today.
          11651    11650 customer           11651                                                                                                                                                                                                   @AppleSupport Just updated it and still is turing my letter I️ into something different.
          11651    11649  support           11650                                                                                                                                                                                                     @118247 Alright, no problem. Let's look into it closer via DM: https://t.co/GDrqU22YpT
          31908    31908 customer           31909                                                                                                                                                                                                                                             @1111 @AppleSupport Yes. It became unstable :(
          31908    31907  support           31908                                                                                                                                                               @123051 We understand your concern. Let's work together to solve these issues. Does this Wi-Fi issue happen on all networks?
           3777     3777 customer            3779                                                                                                                                                                                                @AppleSupport I've also forced the app to close from the background and reopened, no dice 🎲
           3777     3775  support            3777                                                                                                                                                     @116625 Let’s team up on this. How long has this been happening? What version number of iOS are you running? Which iPhone do you have?
           3777     3776 customer            3775                                                                                                                                                                                                                  @AppleSupport still happening, including on iOS 11.2 beta now. any ideas?
           3777     3778  support            3776                                                                                                                                                                             @116625 Thanks for the update. Go ahead and send us a DM and we'll take it from there. https://t.co/GDrqU22YpT
          38227    38227 customer           38228                                                                                                                                                   @1756 @115858 Mine is shite mate....crashing, turning itself off, apps randomly freezing, won’t let me call anyone @115858 @AppleSupport
          38227    38226  support           38227                                                                                                                                                                        @124304 We'd like to look into this with you. When did these issues begin? Tell us in a DM. https://t.co/GDrqU22YpT
          41669    41669  support           41670                                                                                                                                                                                      @117967 What version of iOS are you currently running? Find that in Settings &gt; General &gt; About.
          41669    41668 customer           41669                                                                                                                                                                                                                                                    @AppleSupport It says “11.0.3 (15A432)”
          41669    41667  support           41668                                                                                                                                                              @117967 Let's follow this article to make a backup and update to iOS 11.1, then test the issue again: https://t.co/80YRnjDFDk
          52282    52282 customer           52283                                                                                                                                                                                                                              @2855 @AppleSupport так ты и фоточки туда переносишь, бекапы?
          52282    52281  support           52282                                                                                                                                                              @127759 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj
          53005    53005 customer           53006                                                                                                                                                  @AppleSupport it happens on the center control and on the dock, no particularity with any app, happens with native and downloaded apps :(
          53005    53004  support           53005                                                                                                                                                              @127945 Thanks for reaching out. We're here to help. DM us so we can look into this further with you. https://t.co/GDrqU22YpT
          81815    81815 customer           81816                                                                                                                                                                                                              @113848 @115858 lmao i am on the 6 and my phone crashes from opening snapchat
          81815    81814  support           81815                    @134121 Let's take a closer look together. When you say your iPhone 'crashes' when opening the Snapchat app, please provide us more details about what exactly happens.\n\nAlso, which exact iOS version number is installed on it and have you tried any steps so far?
          81815    81813 customer           81814                                                                                                            @AppleSupport Since you asked. I open up Snapchat and then screen goes black. Then a buffering icon appears and my phone restarts. It’s not just snapchat either. I’m on 11.0.3
          81815    81812  support           81813 @134121 The first step we'd like to have you do, is complete any updates for iOS and apps. Please, back up your iPhone, then update your iOS under Settings &gt; General &gt; Software Update. Once completed, make sure all apps are updated in the App Store. Let us know if that helps.
          86987    86987 customer           86988                                                                                                                                                                                      @4043 @AppleSupport And every time I’ve reached out, I’m told to reboot my phone. How many times??? 😫
          86987    86986  support           86987                                                                                                                @135031 We'd like to get this sorted for you. We know how important it is to have your phone working properly. Click here to connect with us in DM: https://t.co/GDrqU22YpT
          94878    94878 customer           94879                  @115858 @1647 @122986 I’m disappointed with @115858 @AppleSupport I think I’ll never going to order something again on apple, I'm almost canceling my order and I'm almost going to the @1647 or @122986 competition after being an apple customer for more than 10 years
          94878    94877  support           94878                                                                                                                @136198 We’d like to understand more about what's going on. Please DM us some details, and which country you're in, and we’ll take a look with you. https://t.co/GDrqU22YpT

Affected conversation components:
conversation_id
3777     4
81815    4
11651    3
41669    3
31908    2
38227    2
52282    2
53005    2
86987    2
94878    2

In [48]:
# ============================================
# Cell 41 — Correct branch-aware thread construction
# ============================================

from collections import defaultdict

# Build children using only tweets inside conversation_df
subset_children = defaultdict(list)

for _, row in conversation_df.iterrows():
    parent_id = row["parent_tweet_id"]
    tweet_id = row["tweet_id"]

    if (
        parent_id
        and parent_id in conversation_tweet_ids
    ):
        subset_children[parent_id].append(tweet_id)


def build_threads(df):
    """
    Build branch-aware threads.

    A thread starts when a tweet's parent is NOT present
    inside the current AppleSupport component.

    This correctly handles components whose actual parent
    exists outside the selected subset.
    """

    thread_records = []

    for component_id, group in df.groupby("conversation_id"):

        group_ids = set(group["tweet_id"])

        # A local root is a tweet whose parent is not
        # present inside this component.
        roots = []

        for _, row in group.iterrows():
            parent_id = row["parent_tweet_id"]

            if not parent_id or parent_id not in group_ids:
                roots.append(row["tweet_id"])

        # Traverse every local root
        stack = [
            (root, [root])
            for root in roots
        ]

        while stack:

            current, path = stack.pop()

            children = [
                child
                for child in subset_children.get(current, [])
                if child in group_ids
            ]

            if not children:
                thread_records.append({
                    "conversation_id": component_id,
                    "thread_path": path
                })

            else:
                for child in children:
                    stack.append(
                        (child, path + [child])
                    )

    return thread_records


thread_records = build_threads(conversation_df)

print(
    "Branch-aware threads created:",
    len(thread_records)
)

print("\nSample thread paths:")

for record in thread_records[:10]:
    print(
        record["conversation_id"],
        "→",
        " → ".join(record["thread_path"])
    )

Branch-aware threads created: 2257

Sample thread paths:
100245 → 100245 → 100244 → 100243 → 100241 → 100242
100540 → 100540 → 100539
101228 → 101228 → 101227
101231 → 101231 → 101230
101234 → 101234 → 101232 → 101233 → 101235 → 101236 → 101237
101239 → 101239 → 101238
101241 → 101241 → 101240
101244 → 101244 → 101243
101246 → 101246 → 101245
101249 → 101249 → 101248 → 101247

In [49]:
# ============================================
# Cell 42 — Validate branch-aware threads
# ============================================

print("Total branch-aware threads:", len(thread_records))

# Check for empty threads
empty_threads = [
    record
    for record in thread_records
    if not record["thread_path"]
]

print("Empty threads:", len(empty_threads))

# Check for duplicate tweet IDs inside a thread
duplicate_threads = []

for record in thread_records:
    path = record["thread_path"]

    if len(path) != len(set(path)):
        duplicate_threads.append(record)

print("Threads containing duplicate tweet IDs:", len(duplicate_threads))

# Thread length statistics
thread_lengths = [
    len(record["thread_path"])
    for record in thread_records
]

print("\nThread length statistics:")
print("Shortest thread:", min(thread_lengths))
print("Longest thread:", max(thread_lengths))
print(
    "Average thread length:",
    round(sum(thread_lengths) / len(thread_lengths), 2)
)

Total branch-aware threads: 2257
Empty threads: 0
Threads containing duplicate tweet IDs: 0

Thread length statistics:
Shortest thread: 2
Longest thread: 12
Average thread length: 3.25

In [51]:
# ============================================
# Cell 43 — Check tweet coverage
# ============================================

all_thread_tweet_ids = set()

for record in thread_records:
    all_thread_tweet_ids.update(record["thread_path"])

conversation_tweet_ids = set(
    conversation_df["tweet_id"]
)

missing_tweets = conversation_tweet_ids - all_thread_tweet_ids
extra_tweets = all_thread_tweet_ids - conversation_tweet_ids

print("Tweets in conversation_df:", len(conversation_tweet_ids))
print("Tweets appearing in threads:", len(all_thread_tweet_ids))

print("\nMissing tweets:", len(missing_tweets))
print("Extra tweets:", len(extra_tweets))

if missing_tweets:
    print("\nSample missing tweets:")
    print(list(missing_tweets)[:20])

Tweets in conversation_df: 6836
Tweets appearing in threads: 6836

Missing tweets: 0
Extra tweets: 0

In [52]:
# ============================================
# Cell 45 — Create tweet lookup
# ============================================

tweet_lookup = (
    conversation_df
    .set_index("tweet_id")
    .to_dict("index")
)

print("Tweet lookup created:", len(tweet_lookup))

Tweet lookup created: 6836

In [55]:
# ============================================
# Cell 46 — Convert thread paths to messages
# ============================================

conversation_threads = []

for record in thread_records:

    messages = []

    for tweet_id in record["thread_path"]:

        tweet = tweet_lookup.get(tweet_id)

        if tweet is None:
            continue

        messages.append({
            "tweet_id": tweet_id,
            "author_id": tweet["author_id"],
            "role": tweet["role"],
            "text": tweet["text_raw"],
            "text_clean": tweet["text_clean"],
            "created_at": tweet["created_at"]
        })

    conversation_threads.append({
        "conversation_id": record["conversation_id"],
        "thread_path": record["thread_path"],
        "messages": messages
    })

print(
    "Conversation threads created:",
    len(conversation_threads)
)

Conversation threads created: 2257

In [56]:
# ============================================
# Cell 47 — Validate customer/support roles
# ============================================

customer_messages = 0
support_messages = 0
other_messages = 0

for thread in conversation_threads:

    for message in thread["messages"]:

        if message["role"] == "customer":
            customer_messages += 1

        elif message["role"] == "support":
            support_messages += 1

        else:
            other_messages += 1

print("Customer messages:", customer_messages)
print("Support messages:", support_messages)
print("Other messages:", other_messages)

print(
    "Total messages:",
    customer_messages
    + support_messages
    + other_messages
)

Customer messages: 4018
Support messages: 3309
Other messages: 0
Total messages: 7327

In [57]:
# ============================================
# Cell 48 — Inspect real conversations
# ============================================

for thread in conversation_threads[:10]:

    print("\n" + "=" * 80)
    print("Conversation ID:", thread["conversation_id"])

    for message in thread["messages"]:

        print(f"\n{message['role'].upper()}:")
        print(message["text"])

================================================================================
Conversation ID: 100245

CUSTOMER:
What is this @AppleSupport? since I upgraded with this $hi&amp;*y #macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!

SUPPORT:
@137967 We'd like to help. Does this seem to persist when using multiple apps? Have you tried rebooting to see if that helps? Send us a DM, we'll be glad to work on this with you. https://t.co/GDrqU22YpT

CUSTOMER:
@AppleSupport I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.

SUPPORT:
@137967 Either way, let us know what happens via DM. We want to make sure this is fully resolved. https://t.co/GDrqU22YpT

CUSTOMER:
@AppleSupport for now I just restarted, it doesn't lag yet. I will let you know when it happen again.

================================================================================
Conversation ID: 100540

CUSTOMER:
My iPhone been moving slow af the past couple weeks. I need answers @AppleSupport

SUPPORT:
@137986 We’d love to help with the performance of your iPhone. To start, please send us a DM confirming which iPhone and exact software version you’re using. You can tap Settings &gt; General &gt; About to locate the software version. https://t.co/GDrqU22YpT

================================================================================
Conversation ID: 101228

CUSTOMER:
Dear god not again,@AppleSupport https://t.co/5Zf0Mnd6SI

SUPPORT:
@138151 We want to make sure your words and texts are coming out as expected. What version of the iOS software do you currently have installed on your device? You can find this in Settings &gt; General &gt; About.

Please send a DM with this information so we can better assist. https://t.co/GDrqU22YpT

================================================================================
Conversation ID: 101231

CUSTOMER:
Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.

SUPPORT:
@138152 We can assist you. Thanks for bringing this to our attention. If you restart your device and test the issue again, does it persist?

================================================================================
Conversation ID: 101234

CUSTOMER:
@AppleSupport leg dit even uit? Dit is mijn oud e-mail adress/apple id, sinds een recente update krijg ik constant deze melding. Ik heb sinds paar jaar een nieuw e-mail adres en ook een apple id op dit adres. Ik was (nog altijd) het wachtwoord kwijt van het oude e-mail &amp; apple-id https://t.co/5GWgrlFu74

SUPPORT:
@138153 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj

CUSTOMER:
@AppleSupport Since a recent update i’m constantly getting these notifications about my old apple ID /e-mail adress, wich i’ve lost the pw years ago. I allready got a new account and e-mail, but it doesn’t appear anywhere, alltho i can still acces the app store etc..

SUPPORT:
@138153 We'd be happy to look into why that Apple ID is popping up now, and see what we need to do to get it to stop. To get started, can you tell us which iPhone and iOS version you're using? You can find the version by going to Settings &gt; General &gt; About &gt; Version.

CUSTOMER:
@AppleSupport Yes ofcourse, iphone 6s version 11.1.2 (15B202)

SUPPORT:
@138153 Go ahead and DM us your country, and we'll continue working there. https://t.co/GDrqU22YpT

================================================================================
Conversation ID: 101239

CUSTOMER:
@115858 Just because you're releasing new phones doesn't mean you should stop making my current iPhone stop working. I have a contract and cannot just purchase a new phone every 12 months.

SUPPORT:
@138154 If at all possible, we would love to help. Can you tell us in more detail about what you're experiencing with the current iPhone you have?

================================================================================
Conversation ID: 101241

CUSTOMER:
anyone else’s phone changing “it” to I.T 😑😒 @AppleSupport

SUPPORT:
@138155 We've received your DM and will respond to you there shortly.

================================================================================
Conversation ID: 101244

CUSTOMER:
@AppleSupport Spam emails .... https://t.co/9C2RdPu2zs

SUPPORT:
@138156 Thank you for reaching out to us and providing us with this information. Please report this phishing message using the info here: https://t.co/LNMCdqt6fD

================================================================================
Conversation ID: 101246

CUSTOMER:
@AppleSupport updated to iOS 11.1.2, phone crashes repeatedly at 32% battery life. Briefly flashes ‘plug in graphic’, the will restart and crash again within seconds. When drained past 30%, suddenly works fine. Something buggy with the low battery emergency shutdown trigger.

SUPPORT:
@138157 We can help. Was this happening on the iPhone before the update?  Is there any activity that seems to trigger the issue otherwise?

================================================================================
Conversation ID: 101249

CUSTOMER:
My Apple account has been broken for more then 10 weeks now; family sharing doesn’t work, can’t enable it anymore. Can’t share calendars with girlfriend, she doesn’t have access to Apple Music via my family plan (which I do still pay for), etc. 10 weeks and it still isn’t fixed.

CUSTOMER:
@115858 @116333 My Apple account’s Family Sharing has been broken for 10 weeks now, and support doesn’t seem any closer to fixing this. When asked for alternative solutions the answer is to have yet more patience. This is horrible :( https://t.co/1W9S7hFGwC

SUPPORT:
@138158 We'd like to see how we can help with this. Send us a DM with further information such as a case number or serial number, if you have one. https://t.co/GDrqU22YpT

In [76]:
# ============================================
# Cell 49 — Extract valid customer/support pairs
# ============================================

support_pairs = []

for thread in conversation_threads:

    messages = thread["messages"]

    for i in range(len(messages) - 1):

        customer = messages[i]
        support = messages[i + 1]

        # We only want customer → support interactions
        if (
            customer["role"] == "customer"
            and support["role"] == "support"
        ):

            # -----------------------------
            # Get customer message
            # -----------------------------
            customer_text = customer["text_clean"]

            # If cleaned text is missing,
            # use the original/raw text
            if pd.isna(customer_text):
                customer_text = customer["text"]

            # -----------------------------
            # Get support response
            # -----------------------------
            # Support text_clean is currently empty,
            # so use the raw text stored in "text"
            support_text = support["text"]

            # -----------------------------
            # Skip missing values
            # -----------------------------
            if pd.isna(customer_text) or pd.isna(support_text):
                continue

            customer_text = str(customer_text).strip()
            support_text = str(support_text).strip()

            # Skip empty messages
            if not customer_text or not support_text:
                continue

            # -----------------------------
            # Store valid pair
            # -----------------------------
            support_pairs.append({
                "conversation_id": thread["conversation_id"],
                "customer_tweet_id": customer["tweet_id"],
                "support_tweet_id": support["tweet_id"],
                "customer_message": customer_text,
                "support_response": support_text
            })


print(
    "Valid customer → support pairs:",
    len(support_pairs)
)

Valid customer → support pairs: 3276

In [77]:
# ============================================
# Cell 50 — Inspect valid customer/support pairs
# ============================================

for i, pair in enumerate(support_pairs[:20], start=1):

    print("\n" + "=" * 80)
    print(f"Example {i}")
    print("Conversation:", pair["conversation_id"])

    print("\nCUSTOMER:")
    print(pair["customer_message"])

    print("\nSUPPORT:")
    print(pair["support_response"])

================================================================================
Example 1
Conversation: 100245

CUSTOMER:
What is this ? since I upgraded with this $hi&*y macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!

SUPPORT:
@137967 We'd like to help. Does this seem to persist when using multiple apps? Have you tried rebooting to see if that helps? Send us a DM, we'll be glad to work on this with you. https://t.co/GDrqU22YpT

================================================================================
Example 2
Conversation: 100245

CUSTOMER:
I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.

SUPPORT:
@137967 Either way, let us know what happens via DM. We want to make sure this is fully resolved. https://t.co/GDrqU22YpT

================================================================================
Example 3
Conversation: 100540

CUSTOMER:
My iPhone been moving slow af the past couple weeks. I need answers

SUPPORT:
@137986 We’d love to help with the performance of your iPhone. To start, please send us a DM confirming which iPhone and exact software version you’re using. You can tap Settings &gt; General &gt; About to locate the software version. https://t.co/GDrqU22YpT

================================================================================
Example 4
Conversation: 101228

CUSTOMER:
Dear god not again,

SUPPORT:
@138151 We want to make sure your words and texts are coming out as expected. What version of the iOS software do you currently have installed on your device? You can find this in Settings &gt; General &gt; About.

Please send a DM with this information so we can better assist. https://t.co/GDrqU22YpT

================================================================================
Example 5
Conversation: 101231

CUSTOMER:
Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.

SUPPORT:
@138152 We can assist you. Thanks for bringing this to our attention. If you restart your device and test the issue again, does it persist?

================================================================================
Example 6
Conversation: 101234

CUSTOMER:
leg dit even uit? Dit is mijn oud e-mail adress/apple id, sinds een recente update krijg ik constant deze melding. Ik heb sinds paar jaar een nieuw e-mail adres en ook een apple id op dit adres. Ik was (nog altijd) het wachtwoord kwijt van het oude e-mail & apple-id

SUPPORT:
@138153 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3vMgPj

================================================================================
Example 7
Conversation: 101234

CUSTOMER:
Since a recent update i’m constantly getting these notifications about my old apple ID /e-mail adress, wich i’ve lost the pw years ago. I allready got a new account and e-mail, but it doesn’t appear anywhere, alltho i can still acces the app store etc..

SUPPORT:
@138153 We'd be happy to look into why that Apple ID is popping up now, and see what we need to do to get it to stop. To get started, can you tell us which iPhone and iOS version you're using? You can find the version by going to Settings &gt; General &gt; About &gt; Version.

================================================================================
Example 8
Conversation: 101234

CUSTOMER:
Yes ofcourse, iphone 6s version 11.1.2 (15B202)

SUPPORT:
@138153 Go ahead and DM us your country, and we'll continue working there. https://t.co/GDrqU22YpT

================================================================================
Example 9
Conversation: 101239

CUSTOMER:
@115858 Just because you're releasing new phones doesn't mean you should stop making my current iPhone stop working. I have a contract and cannot just purchase a new phone every 12 months.

SUPPORT:
@138154 If at all possible, we would love to help. Can you tell us in more detail about what you're experiencing with the current iPhone you have?

================================================================================
Example 10
Conversation: 101241

CUSTOMER:
anyone else’s phone changing “it” to I.T

SUPPORT:
@138155 We've received your DM and will respond to you there shortly.

================================================================================
Example 11
Conversation: 101244

CUSTOMER:
Spam emails ....

SUPPORT:
@138156 Thank you for reaching out to us and providing us with this information. Please report this phishing message using the info here: https://t.co/LNMCdqt6fD

================================================================================
Example 12
Conversation: 101246

CUSTOMER:
updated to iOS 11.1.2, phone crashes repeatedly at 32% battery life. Briefly flashes ‘plug in graphic’, the will restart and crash again within seconds. When drained past 30%, suddenly works fine. Something buggy with the low battery emergency shutdown trigger.

SUPPORT:
@138157 We can help. Was this happening on the iPhone before the update?  Is there any activity that seems to trigger the issue otherwise?

================================================================================
Example 13
Conversation: 101249

CUSTOMER:
@115858 @116333 My Apple account’s Family Sharing has been broken for 10 weeks now, and support doesn’t seem any closer to fixing this. When asked for alternative solutions the answer is to have yet more patience. This is horrible :( https://t.co/1W9S7hFGwC

SUPPORT:
@138158 We'd like to see how we can help with this. Send us a DM with further information such as a case number or serial number, if you have one. https://t.co/GDrqU22YpT

================================================================================
Example 14
Conversation: 101251

CUSTOMER:
why is my MacBook doing this

SUPPORT:
@138159 We can work together on this display issue. Were there any recent changes to the Mac or damage (liquid contact or drops). Let us know in DM to get started. https://t.co/GDrqU22YpT

================================================================================
Example 15
Conversation: 101253

CUSTOMER:
please, since the last update 10.13.1, there is a huge delay in the refresh of the files in the Finder. Same problem was before but it was fixed in the previous version. Now, the problem appears again

SUPPORT:
@138160 We want to ensure we're able to get your Mac running as expected. Please meet us in DM with more information on the exact issue you're experiencing.

You can meet us in DM, here: https://t.co/GDrqU22YpT

================================================================================
Example 16
Conversation: 101256

CUSTOMER:
please helpmeni can't sign in icloud account

SUPPORT:
@138161 Having access to your account is important and we're happy to help determine the best options to gain access to your account. Are you receiving an error message when you attempt to log in? DM us and we'll work with you there. https://t.co/GDrqU22YpT

================================================================================
Example 17
Conversation: 101256

CUSTOMER:
I forget account and pasword icloud,

SUPPORT:
@138161 This link can help with a forgotten password: https://t.co/fJnZYmbI9N We'll need to refer you here for further help:  https://t.co/UJm15vmMM2 https://t.co/GDrqU22YpT

================================================================================
Example 18
Conversation: 101259

CUSTOMER:
Only to break File Sharing! Sigh :-( /cc @115858 https://t.co/QGw2mX4igg

SUPPORT:
@138162 Having issues with File Sharing since updating to the latest macOS? We'd like to hear more about this to see how we can help. Send us a message in DM at the link below with more details to get started. https://t.co/GDrqU22YpT

================================================================================
Example 19
Conversation: 101262

CUSTOMER:
Why does the iPhone have “I.T” as the autocorrect for “it”??!

SUPPORT:
@138163 Thanks for reaching out. We'd be happy to help. Which version of iOS are you using? You can check in Settings &gt; General &gt; About.

================================================================================
Example 20
Conversation: 101262

CUSTOMER:
11.0.3

SUPPORT:
@138163 Let's backup your device, then update to the latest version of iOS, as shown here: https://t.co/80YRnjDFDk Then test it out and let us know what you see. Shoot us a DM if the issue persists by tapping here: https://t.co/GDrqU22YpT

In [78]:
# ============================================
# Cell 51 — Check duplicate customer messages
# ============================================

customer_texts = [
    pair["customer_message"].strip().lower()
    for pair in support_pairs
]

unique_customer_texts = set(customer_texts)

print("Total valid pairs:", len(support_pairs))
print("Unique customer messages:", len(unique_customer_texts))
print(
    "Duplicate customer messages:",
    len(support_pairs) - len(unique_customer_texts)
)

Total valid pairs: 3276
Unique customer messages: 3023
Duplicate customer messages: 253

In [79]:
# ============================================
# Cell 52 — Check exact duplicate customer/support pairs
# ============================================

pair_keys = [
    (
        pair["customer_message"].strip().lower(),
        pair["support_response"].strip().lower()
    )
    for pair in support_pairs
]

unique_pair_keys = set(pair_keys)

print("Total valid pairs:", len(support_pairs))
print("Unique customer-support pairs:", len(unique_pair_keys))
print(
    "Exact duplicate pairs:",
    len(support_pairs) - len(unique_pair_keys)
)

Total valid pairs: 3276
Unique customer-support pairs: 3092
Exact duplicate pairs: 184

In [80]:
# ============================================
# Cell 53 — Inspect exact duplicate pairs
# ============================================

from collections import Counter

pair_counts = Counter(pair_keys)

duplicate_keys = [
    key
    for key, count in pair_counts.items()
    if count > 1
]

print(
    "Number of duplicated pair types:",
    len(duplicate_keys)
)

for i, key in enumerate(duplicate_keys[:10], start=1):

    customer_text, support_text = key

    print("\n" + "=" * 80)
    print("Duplicate example", i)

    print("\nCUSTOMER:")
    print(customer_text)

    print("\nSUPPORT:")
    print(support_text)

    print("\nCount:", pair_counts[key])

Number of duplicated pair types: 145

================================================================================
Duplicate example 1

CUSTOMER:
applesupport since sierra update (10.12.6) mouse & keyboard constantly losing/regaining bluetooth esp in fcpx. bought wired set up & even then mac freezes on occasions. out of pocket by €300 with this upgrade and doesn't function properly - any suggestions

SUPPORT:
@139271 thanks for reaching out. we know how important it is to have your mac working as expected. we'd like some details to assist. are these issues currently occurring on 10.12.6 or have you updated to high sierra? also, let us know the mac model you're using.

Count: 2

================================================================================
Duplicate example 2

CUSTOMER:
thanks for reply. these issues occurring on 10.12.6 since upgrading from el capitan. (i didn't experience these problems in el cap) nervous about updating to high sierra (i had to replace an unsupported audio interface on last upgrade) i have a mid 2011 imac 21.5 inch

SUPPORT:
@139271 our pleasure. since the issues began are there any steps you've attempted or have you ran a hardware test? if not, we recommend doing so now. keep us posted on the results. https://t.co/yiwr4sw2u7

Count: 2

================================================================================
Duplicate example 3

CUSTOMER:
so, since updating the latest ios, pages no longer lets me open any docs, all show, just don’t open. suggestions? anyone?

SUPPORT:
@117959 can you confirm what version of ios you updated to? also, have you tried restarting your device?

Count: 2

================================================================================
Duplicate example 4

CUSTOMER:
i swear to god i’m going to throw my iphone out of frustration. stop turning wifi back on i turn it off, it comes back on. every 5 minutes. it’s fucking annoying not having a phone that works right anymore

SUPPORT:
@139842 are you using control center or settings on your iphone to turn wi-fi off? if you're using control center, that works a bit differently in ios 11: https://t.co/g7bhuqnds6 let us know in dm if you have any other questions. https://t.co/gdrqu22ypt

Count: 2

================================================================================
Duplicate example 5

CUSTOMER:
i guess i can’t tweet a song from my music app anymore, why was that feature even added if it doesn’t work

SUPPORT:
@140191 we'd like to know more about the trouble you're having so we can help get your music sharing working again. what was happening when you try to share a song to twitter?

Count: 2

================================================================================
Duplicate example 6

CUSTOMER:
i don't get this screen on my itunes for windows. hence i cannot sync my ripped music to icloud, iphone and other i-devices. home sharing isn't good enough! help

SUPPORT:
@140681 we'd like to assist with this. which version of itunes are you using? https://t.co/g2hm9lnith

what windows version are you running as well?

Count: 2

================================================================================
Duplicate example 7

CUSTOMER:
music and podcast “skip” around like a cd, then distorts and clears up in few seconds, only happens after ios 11

SUPPORT:
@118095 we're here to help. did this happen after a specific update, or just recently? thanks!

Count: 2

================================================================================
Duplicate example 8

CUSTOMER:
@115858, your new ios 11.1 not resolve the calendar problem. 😡#ios11 #iosfail

SUPPORT:
@118102 we want you to be able to rely on your calendar. what exactly is going on with it?

Count: 2

================================================================================
Duplicate example 9

CUSTOMER:
my iphone 7+ has screen touch issues when it’s plugged up! and yes, i do have an apple brand charger. help me bc it’s driving me crazy. same for my macbook, but my charger isn’t apple brand for the laptop. help before i die plz.

SUPPORT:
@141849 we definitely want you to be able to use your iphone, and we're glad to lend a hand. to start, what ios is running under settings &gt; general &gt; about?

Count: 2

================================================================================
Duplicate example 10

CUSTOMER:
11.1.1

SUPPORT:
@141849 thanks for that detail. let's get you up to speed as a first step and see if the issues resolve themselves. we've released ios 11.1.2 recently, so let's get you to back up and update first. check out this link for assistance in this step: https://t.co/ego8nzttak

Count: 2

In [81]:
# ============================================
# Cell 54 — Remove exact duplicate pairs
# ============================================

clean_support_pairs = []
seen_pairs = set()

for pair in support_pairs:

    # Normalize both sides only for duplicate detection
    customer_key = pair["customer_message"].strip().lower()
    support_key = pair["support_response"].strip().lower()

    pair_key = (
        customer_key,
        support_key
    )

    # Keep only the first occurrence
    if pair_key not in seen_pairs:

        seen_pairs.add(pair_key)
        clean_support_pairs.append(pair)

print("Original pairs:", len(support_pairs))
print("Clean pairs:", len(clean_support_pairs))
print(
    "Removed exact duplicates:",
    len(support_pairs) - len(clean_support_pairs)
)

Original pairs: 3276
Clean pairs: 3092
Removed exact duplicates: 184

In [82]:
# ============================================
# Cell 56 — Analyze Apple Support response patterns
# ============================================

import re
from collections import Counter

response_patterns = {
    "dm_request": 0,
    "question": 0,
    "troubleshooting": 0,
    "link": 0,
    "acknowledgement": 0
}

for pair in clean_support_pairs:

    response = pair["support_response"].lower()

    # DM / private support
    if (
        "dm" in response
        or "direct message" in response
        or "send us a message" in response
    ):
        response_patterns["dm_request"] += 1

    # Asking for information
    if "?" in response:
        response_patterns["question"] += 1

    # Troubleshooting / action-oriented response
    troubleshooting_words = [
        "restart",
        "reboot",
        "update",
        "backup",
        "check",
        "settings",
        "reset",
        "install",
        "remove",
        "try",
        "test"
    ]

    if any(
        word in response
        for word in troubleshooting_words
    ):
        response_patterns["troubleshooting"] += 1

    # Contains external link
    if "http://" in response or "https://" in response:
        response_patterns["link"] += 1

    # Basic acknowledgement
    acknowledgement_words = [
        "thanks for reaching out",
        "thank you for reaching out",
        "we'd like to help",
        "we'd be happy to help",
        "we can help",
        "we'd love to help",
        "we're here to help"
    ]

    if any(
        phrase in response
        for phrase in acknowledgement_words
    ):
        response_patterns["acknowledgement"] += 1


print("Apple Support Response Pattern Analysis")
print("=" * 50)

for pattern, count in response_patterns.items():

    percentage = (
        count / len(clean_support_pairs)
    ) * 100

    print(
        f"{pattern:20s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Apple Support Response Pattern Analysis
==================================================
dm_request          : 1526 (49.35%)
question            : 1144 (37.00%)
troubleshooting     : 1052 (34.02%)
link                : 2063 (66.72%)
acknowledgement     :  629 (20.34%)

In [83]:
# ============================================
# Cell 57 — Classify primary Apple response behavior
# ============================================

def classify_response(response):

    response = response.lower().strip()

    has_dm = (
        "dm" in response
        or "direct message" in response
        or "send us a message" in response
        or "message us" in response
    )

    has_question = "?" in response

    troubleshooting_words = [
        "restart",
        "reboot",
        "update",
        "backup",
        "check",
        "settings",
        "reset",
        "install",
        "remove",
        "try",
        "test",
        "turn off",
        "turn on"
    ]

    has_troubleshooting = any(
        word in response
        for word in troubleshooting_words
    )

    has_link = (
        "http://" in response
        or "https://" in response
    )

    # Primary behavior
    # More specific actions/questions take priority
    if has_troubleshooting:
        return "troubleshooting"

    elif has_question:
        return "information_request"

    elif has_dm:
        return "dm_escalation"

    elif has_link:
        return "link_resource"

    elif any(
        phrase in response
        for phrase in [
            "thanks for reaching out",
            "thank you for reaching out",
            "we'd like to help",
            "we'd be happy to help",
            "we can help",
            "we'd love to help",
            "we're here to help"
        ]
    ):
        return "acknowledgement"

    else:
        return "other"


# Apply classification
for pair in clean_support_pairs:

    pair["response_behavior"] = classify_response(
        pair["support_response"]
    )


# Count behaviors
behavior_counts = Counter(
    pair["response_behavior"]
    for pair in clean_support_pairs
)


print("Primary Apple Support Response Behavior")
print("=" * 50)

for behavior, count in behavior_counts.most_common():

    percentage = (
        count / len(clean_support_pairs)
    ) * 100

    print(
        f"{behavior:22s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Primary Apple Support Response Behavior
==================================================
troubleshooting       : 1054 (34.09%)
dm_escalation         :  908 (29.37%)
information_request   :  626 (20.25%)
link_resource         :  337 (10.90%)
other                 :  142 (4.59%)
acknowledgement       :   25 (0.81%)

In [85]:
# ============================================
# Cell 58 — Inspect DM escalation responses
# ============================================

dm_responses = [
    pair
    for pair in clean_support_pairs
    if pair["response_behavior"] == "dm_escalation"
]

print(
    "Total DM escalation responses:",
    len(dm_responses)
)

for i, pair in enumerate(dm_responses[:20], start=1):

    print("\n" + "=" * 80)
    print(f"Example {i}")
    print("Conversation:", pair["conversation_id"])

    print("\nCUSTOMER:")
    print(pair["customer_message"])

    print("\nAPPLE SUPPORT:")
    print(pair["support_response"])

Total DM escalation responses: 908

================================================================================
Example 1
Conversation: 100245

CUSTOMER:
I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.

APPLE SUPPORT:
@137967 Either way, let us know what happens via DM. We want to make sure this is fully resolved. https://t.co/GDrqU22YpT

================================================================================
Example 2
Conversation: 101241

CUSTOMER:
anyone else’s phone changing “it” to I.T

APPLE SUPPORT:
@138155 We've received your DM and will respond to you there shortly.

================================================================================
Example 3
Conversation: 101244

CUSTOMER:
Spam emails ....

APPLE SUPPORT:
@138156 Thank you for reaching out to us and providing us with this information. Please report this phishing message using the info here: https://t.co/LNMCdqt6fD

================================================================================
Example 4
Conversation: 101249

CUSTOMER:
@115858 @116333 My Apple account’s Family Sharing has been broken for 10 weeks now, and support doesn’t seem any closer to fixing this. When asked for alternative solutions the answer is to have yet more patience. This is horrible :( https://t.co/1W9S7hFGwC

APPLE SUPPORT:
@138158 We'd like to see how we can help with this. Send us a DM with further information such as a case number or serial number, if you have one. https://t.co/GDrqU22YpT

================================================================================
Example 5
Conversation: 101251

CUSTOMER:
why is my MacBook doing this

APPLE SUPPORT:
@138159 We can work together on this display issue. Were there any recent changes to the Mac or damage (liquid contact or drops). Let us know in DM to get started. https://t.co/GDrqU22YpT

================================================================================
Example 6
Conversation: 101253

CUSTOMER:
please, since the last update 10.13.1, there is a huge delay in the refresh of the files in the Finder. Same problem was before but it was fixed in the previous version. Now, the problem appears again

APPLE SUPPORT:
@138160 We want to ensure we're able to get your Mac running as expected. Please meet us in DM with more information on the exact issue you're experiencing.

You can meet us in DM, here: https://t.co/GDrqU22YpT

================================================================================
Example 7
Conversation: 101266

CUSTOMER:
No updates on the car, and my partner’s phone is pairing with Android Auto just fine. When I try plug my phone into the car, the car doesn’t respond at all. Even bought a new cord to make sure it wasn’t a connection issue.

APPLE SUPPORT:
@138164 You've completed some great steps, thanks. DM the make and model of your car and we'll continue there. https://t.co/GDrqU22YpT

================================================================================
Example 8
Conversation: 101285

CUSTOMER:
Anybody else getting really annoyed with trying to type “it” and constantly having it autocorrect to I.T ???? What’s good with that @115858 ???

APPLE SUPPORT:
@138170 We'd like to help. Please let us know in DM the device you are using, along with the software version it is running to start: https://t.co/GDrqU22YpT

================================================================================
Example 9
Conversation: 101290

CUSTOMER:
As I said I can't recreate the scenario but it happens once every week or so

APPLE SUPPORT:
@138172 If that issue happens again, go ahead and reach out to us in DM and let us know more about it then. We'll be happy to help further then. https://t.co/GDrqU22YpT

================================================================================
Example 10
Conversation: 101304

CUSTOMER:
how do I go about raising a high level complaint please? 4 senior techs couldn’t help fix my problem, now my e mails are being unanswered, want a refund for a product that’s not fit for purpose, have tried everything to fix, thanks.

APPLE SUPPORT:
@138177 We'd be happy to look into this with you. DM us using the link below and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 11
Conversation: 102363

CUSTOMER:
Dear , the feature that is suppose to keep Live Photos off doesn’t work. A fix would be nice. Thanks!

APPLE SUPPORT:
@138471 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 12
Conversation: 103143

CUSTOMER:
CAN I PLEASE TALK TO A REAL PERSON, and not an automated voice? I've been on hold for 45 mins, got hung up on. I need your HELP LIKE NOW!!

APPLE SUPPORT:
@138688 We want you get the help you're needing. Perhaps we can offer some solutions here. Shoot us a DM, letting us know what's going on and from there we'll provide any assistance we can. https://t.co/GDrqU22YpT

================================================================================
Example 13
Conversation: 103157

CUSTOMER:
I deleted the download and re-downloaded the update and again, it says an error occured while installing

APPLE SUPPORT:
@138692 Let's meet up in DM and work together there. https://t.co/GDrqU22YpT

================================================================================
Example 14
Conversation: 103162

CUSTOMER:
, did HighSierra kill my old trackpad? After the recent update, no more trackpad. Bounces between connected and mostly not.

APPLE SUPPORT:
@138693 Thanks for reaching out to us. We are always happy to help. Send us a DM. We'd like to look into this with you.

================================================================================
Example 15
Conversation: 103169

CUSTOMER:
All is correct there.

APPLE SUPPORT:
@138696 Thank you. We’d like to look further into this with you. Please send us a DM confirming which software version you are using with your iMac and MacBook Air. https://t.co/GDrqU22YpT

================================================================================
Example 16
Conversation: 103200

CUSTOMER:
dont understand why i just called you to have my phone not working stilll.... thanks so much

APPLE SUPPORT:
@138704 Send us a DM. Let us know more details on the issue. We'll do our best to help. https://t.co/GDrqU22YpT

================================================================================
Example 17
Conversation: 103205

CUSTOMER:
I tried to recreate the issue with iTunes open and was unable to reproduce the effect. Thank you for your reply.

APPLE SUPPORT:
@138705 Got it, thank you. If it still occurs in Safari, please send us a DM. We'd like to continue working on this with you. https://t.co/GDrqU22YpT

================================================================================
Example 18
Conversation: 103210

CUSTOMER:
no sound in the right earphone and yes.

APPLE SUPPORT:
@138707 Alright, we'd like to take a look at your options. Let us know when and where this set was purchased in a DM and we'll continue. https://t.co/GDrqU22YpT

================================================================================
Example 19
Conversation: 103218

CUSTOMER:
iOS 11.1.2 - it’s up to date

APPLE SUPPORT:
@138709 OK, thanks. So that we can look into this further, use the link below to DM us, and we’ll  take it from there. https://t.co/GDrqU22YpT

================================================================================
Example 20
Conversation: 103221

CUSTOMER:
I WANT Y’ALL TO EXPLAIN TO ME WHY MY 8 PLUS BATTERY IS GARBAGE. I’VE BEEN ON IT FOR LIKE AN HOUR AND IT’S AT 74%. IT GOES DOWN LIKE 5 PERCENT WHEN I LISTEN TO ONE FUCKING SONG.

APPLE SUPPORT:
@138710 We're happy to look into what's happening with your iPhone battery performance. We know how important it is to have your iPhone battery performing at its best. Send us a DM letting us know if you see the message outlined in this article: https://t.co/KyywFa9iZ3 https://t.co/GDrqU22YpT

In [86]:
# ============================================
# Cell 59 — Analyze quality of DM responses
# ============================================

def has_actionable_guidance(response):

    response = response.lower()

    actionable_words = [
        "restart",
        "reboot",
        "update",
        "backup",
        "check",
        "settings",
        "reset",
        "install",
        "remove",
        "try",
        "test",
        "confirm",
        "tell us",
        "let us know",
        "which",
        "version",
        "model",
        "serial",
        "case number",
        "country",
        "purchase",
        "error"
    ]

    return any(
        word in response
        for word in actionable_words
    )


weak_dm = 0
useful_dm = 0

for pair in clean_support_pairs:

    response = pair["support_response"].lower()

    has_dm = (
        "dm" in response
        or "direct message" in response
        or "send us a message" in response
        or "message us" in response
    )

    if not has_dm:
        continue

    if has_actionable_guidance(response):
        useful_dm += 1
    else:
        weak_dm += 1


total_dm = useful_dm + weak_dm

print("DM response analysis")
print("=" * 50)

print("Total DM responses:", total_dm)
print(
    "DM + useful guidance:",
    useful_dm,
    f"({useful_dm / total_dm * 100:.2f}%)"
)
print(
    "Weak / generic DM responses:",
    weak_dm,
    f"({weak_dm / total_dm * 100:.2f}%)"
)

DM response analysis
==================================================
Total DM responses: 1528
DM + useful guidance: 793 (51.90%)
Weak / generic DM responses: 735 (48.10%)

In [87]:
# ============================================
# Cell 60 — Inspect weak / generic DM responses
# ============================================

weak_dm_responses = []

for pair in clean_support_pairs:

    response = pair["support_response"].lower()

    has_dm = (
        "dm" in response
        or "direct message" in response
        or "send us a message" in response
        or "message us" in response
    )

    if not has_dm:
        continue

    if not has_actionable_guidance(response):
        weak_dm_responses.append(pair)


print("Weak / generic DM responses:", len(weak_dm_responses))

for i, pair in enumerate(weak_dm_responses[:30], start=1):

    print("\n" + "=" * 80)
    print(f"Example {i}")
    print("Conversation:", pair["conversation_id"])

    print("\nCUSTOMER:")
    print(pair["customer_message"])

    print("\nAPPLE SUPPORT:")
    print(pair["support_response"])

Weak / generic DM responses: 735

================================================================================
Example 1
Conversation: 101241

CUSTOMER:
anyone else’s phone changing “it” to I.T

APPLE SUPPORT:
@138155 We've received your DM and will respond to you there shortly.

================================================================================
Example 2
Conversation: 101244

CUSTOMER:
Spam emails ....

APPLE SUPPORT:
@138156 Thank you for reaching out to us and providing us with this information. Please report this phishing message using the info here: https://t.co/LNMCdqt6fD

================================================================================
Example 3
Conversation: 101253

CUSTOMER:
please, since the last update 10.13.1, there is a huge delay in the refresh of the files in the Finder. Same problem was before but it was fixed in the previous version. Now, the problem appears again

APPLE SUPPORT:
@138160 We want to ensure we're able to get your Mac running as expected. Please meet us in DM with more information on the exact issue you're experiencing.

You can meet us in DM, here: https://t.co/GDrqU22YpT

================================================================================
Example 4
Conversation: 101304

CUSTOMER:
how do I go about raising a high level complaint please? 4 senior techs couldn’t help fix my problem, now my e mails are being unanswered, want a refund for a product that’s not fit for purpose, have tried everything to fix, thanks.

APPLE SUPPORT:
@138177 We'd be happy to look into this with you. DM us using the link below and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 5
Conversation: 102355

CUSTOMER:
MacBook won’t turn on...gives me this screen, I need my serial number to call Apple support, won’t turn on....HELP

APPLE SUPPORT:
@138468 No worries. Help has arrived. We have a few questions that will help us get to the bottom of this. How were you using your Mac just before this occurred? Have you added new external hardware or accessories? Send us a DM. https://t.co/GDrqU22YpT

================================================================================
Example 6
Conversation: 102363

CUSTOMER:
Dear , the feature that is suppose to keep Live Photos off doesn’t work. A fix would be nice. Thanks!

APPLE SUPPORT:
@138471 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 7
Conversation: 103143

CUSTOMER:
CAN I PLEASE TALK TO A REAL PERSON, and not an automated voice? I've been on hold for 45 mins, got hung up on. I need your HELP LIKE NOW!!

APPLE SUPPORT:
@138688 We want you get the help you're needing. Perhaps we can offer some solutions here. Shoot us a DM, letting us know what's going on and from there we'll provide any assistance we can. https://t.co/GDrqU22YpT

================================================================================
Example 8
Conversation: 103157

CUSTOMER:
I deleted the download and re-downloaded the update and again, it says an error occured while installing

APPLE SUPPORT:
@138692 Let's meet up in DM and work together there. https://t.co/GDrqU22YpT

================================================================================
Example 9
Conversation: 103162

CUSTOMER:
, did HighSierra kill my old trackpad? After the recent update, no more trackpad. Bounces between connected and mostly not.

APPLE SUPPORT:
@138693 Thanks for reaching out to us. We are always happy to help. Send us a DM. We'd like to look into this with you.

================================================================================
Example 10
Conversation: 103174

CUSTOMER:
why does my battery drain so fast now on iOS 11.1.2 I lose 10% in an hour or less and I don’t even use the phone. Im at 26% now

APPLE SUPPORT:
@138697 We know how vital the battery is and we'll help. Are you using the Apple Lightning to USB cable and power adapter to charge your iPhone? You can DM us your answer. https://t.co/GDrqU22YpT

================================================================================
Example 11
Conversation: 103205

CUSTOMER:
I tried to recreate the issue with iTunes open and was unable to reproduce the effect. Thank you for your reply.

APPLE SUPPORT:
@138705 Got it, thank you. If it still occurs in Safari, please send us a DM. We'd like to continue working on this with you. https://t.co/GDrqU22YpT

================================================================================
Example 12
Conversation: 103215

CUSTOMER:
@116333 Please help me, apple call centre in India unable to support

APPLE SUPPORT:
@138708 We're happy to assist you. Is this related to the Face ID issue you recently had? DM us with more information and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 13
Conversation: 103218

CUSTOMER:
iOS 11.1.2 - it’s up to date

APPLE SUPPORT:
@138709 OK, thanks. So that we can look into this further, use the link below to DM us, and we’ll  take it from there. https://t.co/GDrqU22YpT

================================================================================
Example 14
Conversation: 103221

CUSTOMER:
I WANT Y’ALL TO EXPLAIN TO ME WHY MY 8 PLUS BATTERY IS GARBAGE. I’VE BEEN ON IT FOR LIKE AN HOUR AND IT’S AT 74%. IT GOES DOWN LIKE 5 PERCENT WHEN I LISTEN TO ONE FUCKING SONG.

APPLE SUPPORT:
@138710 We're happy to look into what's happening with your iPhone battery performance. We know how important it is to have your iPhone battery performing at its best. Send us a DM letting us know if you see the message outlined in this article: https://t.co/KyywFa9iZ3 https://t.co/GDrqU22YpT

================================================================================
Example 15
Conversation: 103243

CUSTOMER:
On iOS 11, the video player shows a scrubbing speed tip every time I scrub for a while. Useful the 1st / 2nd time, but maybe not the gazillionth time. Is there a way to turn it off?

APPLE SUPPORT:
@138719 We’d be glad to look into this with you. Can you start by explaining what app you are using to view the video in DM? These details help us determine where to get started. https://t.co/GDrqU22YpT

================================================================================
Example 16
Conversation: 103248

CUSTOMER:
11.1.2

APPLE SUPPORT:
@138721 Thanks. Do you notice this occurring after running or exiting out of a certain app? Let's continue via DM. https://t.co/GDrqU22YpT

================================================================================
Example 17
Conversation: 104192

CUSTOMER:
Hi . I keep my personal iPhone 6S in my pocket. Any time I also carry my work iPhone 6 in my bag, the steps count from both devices seem to get added together in the Health app. Is there a way to stop this please? It didn't happen in iOS 10.

APPLE SUPPORT:
@138973 We understand how important it is to sort this out. The Health app handles data from different sources such as from other devices or apps. However, you can prioritize the data sources and learn more about this here: https://t.co/FbDAfgVHS6 DM us any other questions. https://t.co/GDrqU22YpT

================================================================================
Example 18
Conversation: 104192

CUSTOMER:
Thanks. Yep I checked that, but neither phone has the other listed as an alternative data source. It’s almost like it’s because they’re both linked to my iCloud account or something. Here’s an example from one of them, the one listed is the same device name.

APPLE SUPPORT:
@138973 We'd like to look into this further. Please DM us to continue working on this. https://t.co/GDrqU22YpT

================================================================================
Example 19
Conversation: 105328

CUSTOMER:
Such rude folks in apple store as if they have done favors by selling iPhone  @116333 @6126 #iPhoneSucks #AppleCareSucks

APPLE SUPPORT:
@139259 That's certainly not the experience we want for our customers.  DM us with more details and we can proceed from there to get to the bottom of this. https://t.co/GDrqU22YpT

================================================================================
Example 20
Conversation: 105347

CUSTOMER:
my phone’s updated tho 🤔 what kinda bug is this @115858 fix it https://t.co/g3DalWEd91

APPLE SUPPORT:
@139265 We're here to help find the best solution. Can you send us a DM with detials on what you're referring to? https://t.co/GDrqU22YpT

================================================================================
Example 21
Conversation: 105356

CUSTOMER:
Any comment on if restarting to factory settings then downloading all software then loading back up will do anything?

APPLE SUPPORT:
@139268 Let's meet in Direct Message to continue. https://t.co/GDrqU22YpT

================================================================================
Example 22
Conversation: 105367

CUSTOMER:
I’ve tried trashing Bluetooth prefs - but this didn’t help. Could you please explain how to run the hardware test?

APPLE SUPPORT:
@139271 Absolutely, there are a few steps involved. Are you able to open the article we previously sent? If so, the steps are there. If you have any issue viewing the article send us a DM with the link below and we'll provide them for you. https://t.co/GDrqU22YpT

================================================================================
Example 23
Conversation: 105374

CUSTOMER:
my watch is running really slow, it’s up to date, I’ve restarted it, turned it on and off, not sure what else I can do?

APPLE SUPPORT:
@139272 Thanks for reaching out to us. We are always happy to help. Send us a DM so we can look into this issue with you there. https://t.co/GDrqU22YpT

================================================================================
Example 24
Conversation: 105386

CUSTOMER:
Brand New iPhoneX with GreenLine Achievement Unlocked ... Time to leave this Planet

APPLE SUPPORT:
@139276 We are sad to see those Photos, but we want to help with your new iPhone X. Please send us a DM, and we can continue. https://t.co/GDrqU22YpT

================================================================================
Example 25
Conversation: 105398

CUSTOMER:
How do I clear analytic data from my iPhone? (yes its turned off) but it's being stored anyways. Bad enough your os is 4gb.

APPLE SUPPORT:
@139279 We can offer some guidance on this. Use the link below to DM us, and we’ll take it from there. https://t.co/GDrqU22YpT

================================================================================
Example 26
Conversation: 105400

CUSTOMER:
Why is my iPhone X’s screen still freezing? I thought the last update was supposed to fix it??

APPLE SUPPORT:
@139280 We'd love to help look into this and get you back in action. Can you send us a DM with some additional details? https://t.co/GDrqU22YpT

================================================================================
Example 27
Conversation: 105421

CUSTOMER:
Hi, tried to install High Sierra on my 2011 MacBook Air, now I'm stuck here. Please help.

APPLE SUPPORT:
@139287 We'd be happy to assist with your Mac today. Send us a DM to get started. https://t.co/GDrqU22YpT

================================================================================
Example 28
Conversation: 105423

CUSTOMER:
Hi, how can I check my iPhone's battery health? Any way without going to an Apple Store?

APPLE SUPPORT:
@139288 We can definitely understand your concern. We would want to make sure our battery health is good too.  Let's partner together in DM and go from there. https://t.co/GDrqU22YpT

================================================================================
Example 29
Conversation: 105429

CUSTOMER:
Why does my Siri sound fucked up!!! Anyone else having this problem??

APPLE SUPPORT:
@139289 We'd be happy to look into this with you. Send us a DM and we'll continue working from there. https://t.co/GDrqU22YpT

================================================================================
Example 30
Conversation: 105438

CUSTOMER:
how do i make a service complaint?? Disappointed in my service for my repair

APPLE SUPPORT:
@139292 We can assist you. Please DM us via the following link for any details you can provide and we'll help you from there. https://t.co/GDrqU22YpT

In [88]:
# ============================================
# Cell 61 — Final response quality categories
# ============================================

def classify_response_quality(response):

    response_lower = response.lower().strip()

    has_dm = (
        "dm" in response_lower
        or "direct message" in response_lower
        or "send us a message" in response_lower
        or "message us" in response_lower
    )

    has_link = (
        "http://" in response_lower
        or "https://" in response_lower
    )

    troubleshooting_words = [
        "restart",
        "reboot",
        "update",
        "backup",
        "reset",
        "install",
        "remove",
        "check",
        "settings",
        "turn off",
        "turn on",
        "test",
        "try",
        "report"
    ]

    information_requests = [
        "what",
        "which",
        "how",
        "when",
        "where",
        "version",
        "model",
        "serial",
        "case number",
        "details",
        "error",
        "purchased",
        "software"
    ]

    has_troubleshooting = any(
        word in response_lower
        for word in troubleshooting_words
    )

    has_information_request = (
        "?" in response_lower
        or any(
            phrase in response_lower
            for phrase in information_requests
        )
    )

    # 1. Concrete help/resource
    if has_troubleshooting or has_link:
        return "actionable"

    # 2. DM escalation with specific information request
    if has_dm and has_information_request:
        return "guided_escalation"

    # 3. Generic DM / generic acknowledgement
    if has_dm:
        return "generic_escalation"

    # 4. Other responses
    return "other"


# Apply classification
for pair in clean_support_pairs:
    pair["response_quality"] = classify_response_quality(
        pair["support_response"]
    )


# Count categories
quality_counts = Counter(
    pair["response_quality"]
    for pair in clean_support_pairs
)

print("Response quality distribution")
print("=" * 50)

for quality, count in quality_counts.most_common():

    percentage = (
        count / len(clean_support_pairs)
    ) * 100

    print(
        f"{quality:22s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Response quality distribution
==================================================
actionable            : 2476 (80.08%)
other                 :  562 (18.18%)
generic_escalation    :   48 (1.55%)
guided_escalation     :    6 (0.19%)

In [89]:
# ============================================
# Cell 62 — Improved response quality rule
# ============================================

def classify_response_quality(response):

    response_lower = response.lower().strip()

    has_dm = (
        "dm" in response_lower
        or "direct message" in response_lower
        or "send us a message" in response_lower
        or "message us" in response_lower
    )

    has_link = (
        "http://" in response_lower
        or "https://" in response_lower
    )

    troubleshooting_words = [
        "restart",
        "reboot",
        "update",
        "backup",
        "reset",
        "install",
        "remove",
        "check",
        "settings",
        "turn off",
        "turn on",
        "test",
        "try",
        "report",
        "use the link",
        "follow the steps"
    ]

    information_request_patterns = [
        "?",
        "what",
        "which",
        "how",
        "when",
        "where",
        "version",
        "model",
        "serial",
        "case number",
        "details",
        "error",
        "purchased",
        "software",
        "device",
        "country",
        "app",
        "tell us",
        "let us know"
    ]

    has_troubleshooting = any(
        word in response_lower
        for word in troubleshooting_words
    )

    has_information_request = any(
        phrase in response_lower
        for phrase in information_request_patterns
    )

    # ------------------------------------------------
    # 1. Guided escalation
    # DM + asks for specific information / next step
    # ------------------------------------------------

    if has_dm and has_information_request:
        return "guided_escalation"

    # ------------------------------------------------
    # 2. Generic escalation
    # DM without meaningful guidance
    # ------------------------------------------------

    if has_dm:
        return "generic_escalation"

    # ------------------------------------------------
    # 3. Actionable response
    # Troubleshooting or useful resource
    # ------------------------------------------------

    if has_troubleshooting or has_link:
        return "actionable"

    # ------------------------------------------------
    # 4. Other
    # ------------------------------------------------

    return "other"


# Apply new classification
for pair in clean_support_pairs:

    pair["response_quality"] = classify_response_quality(
        pair["support_response"]
    )


# Count categories
quality_counts = Counter(
    pair["response_quality"]
    for pair in clean_support_pairs
)


print("Improved response quality distribution")
print("=" * 55)

for quality, count in quality_counts.most_common():

    percentage = (
        count / len(clean_support_pairs)
    ) * 100

    print(
        f"{quality:22s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Improved response quality distribution
=======================================================
guided_escalation     : 1025 (33.15%)
actionable            : 1002 (32.41%)
other                 :  562 (18.18%)
generic_escalation    :  503 (16.27%)

In [90]:
# ============================================
# Cell 63 — Inspect "other" responses
# ============================================

other_responses = [
    pair
    for pair in clean_support_pairs
    if pair["response_quality"] == "other"
]

print("Total OTHER responses:", len(other_responses))

for i, pair in enumerate(other_responses[:30], start=1):

    print("\n" + "=" * 80)
    print(f"Example {i}")
    print("Conversation:", pair["conversation_id"])

    print("\nCUSTOMER:")
    print(pair["customer_message"])

    print("\nAPPLE SUPPORT:")
    print(pair["support_response"])

Total OTHER responses: 562

================================================================================
Example 1
Conversation: 101239

CUSTOMER:
@115858 Just because you're releasing new phones doesn't mean you should stop making my current iPhone stop working. I have a contract and cannot just purchase a new phone every 12 months.

APPLE SUPPORT:
@138154 If at all possible, we would love to help. Can you tell us in more detail about what you're experiencing with the current iPhone you have?

================================================================================
Example 2
Conversation: 101266

CUSTOMER:
And before that I hadn’t done any updates between when it worked normally and the time it froze & crashed.

APPLE SUPPORT:
@138164 Thanks.  Are you able to successfully connect to any other Bluetooth devices?

================================================================================
Example 3
Conversation: 101302

CUSTOMER:
common guys. I rely on your products for video production for broadcast and your update to fix your security issue is completely crashing the OS... as a life long user of your products this is unacceptable

APPLE SUPPORT:
@138176 We can definitely understand and want you to be able to rely on our products and software. Which device are you using and what exactly happens?

================================================================================
Example 4
Conversation: 103146

CUSTOMER:
how do I stop this auto brightness I like my screen dark and it just randomly gets bright

APPLE SUPPORT:
@138689 Thanks for reaching out. We know how important it is to control your display brightness, and we're happy to help. Can you tell us which device model and version of software you're using so we can provide the steps for how to adjust this?

================================================================================
Example 5
Conversation: 103146

CUSTOMER:
Omg yesss thank you !!!!

APPLE SUPPORT:
@138689 You're very welcome. Please let us know if you have any additional questions. We're happy to help. Have a great evening!

================================================================================
Example 6
Conversation: 103154

CUSTOMER:
I need your help!!

APPLE SUPPORT:
@138691 You've come to the right place! What's going on?

================================================================================
Example 7
Conversation: 103179

CUSTOMER:
Yes. I think touchID was better, just my opinion. Just giving you some feedback but other than that I do like the new hardware finally.

APPLE SUPPORT:
@138699 We appreciate your feedback and we’re glad to hear that you like your new iPhone! Let us know if we can assist you with anything else in the future.  Have a wonderful day!

================================================================================
Example 8
Conversation: 103205

CUSTOMER:
The new update to my iMac messed up my play/pause button. It no longer controls Spotify but the videos on my facebook timeline and inside safari. How do I fix this?

APPLE SUPPORT:
@138705 We can assist you. Does this take place with any other apps such as iTunes?

================================================================================
Example 9
Conversation: 103210

CUSTOMER:
OMFG @115858 this is my 3rd pair of fkn headphones that have crapped out on me.

APPLE SUPPORT:
@138707 Hi, we appreciate you reaching out to us to resolve this issue. We would like to gather a little more information before we continue. First, are they Apple or Beats headphones?

================================================================================
Example 10
Conversation: 103210

CUSTOMER:
apple. ones you get when you get a new phone.

APPLE SUPPORT:
@138707 Got it, thanks. So we're sure to be on the same page is there no sound at all or is there an issue with the sound quality? Also, does it happen when connected to any device?

================================================================================
Example 11
Conversation: 103218

CUSTOMER:
Yo my iPhone just went from 100% to 20% in an hour.

APPLE SUPPORT:
@138709 Battery life is important, and we can help. To start, tell us the iOS version your iPhone is running, and we’ll take it from there.

================================================================================
Example 12
Conversation: 103224

CUSTOMER:
"Keep in mind that this version will still be available to all users as a manual update from the App Store"...@118936 @115858.. the app store does not behave like this. Please can we fix this 🙏

APPLE SUPPORT:
@138711 We're happy to look into this with you. What are you downloading when you see this message?

================================================================================
Example 13
Conversation: 103240

CUSTOMER:
They came back thanks.

APPLE SUPPORT:
@138718 That's great to hear! Please do reach back out if we can be of any further assistance.

================================================================================
Example 14
Conversation: 103245

CUSTOMER:
Is this real? The app store said there were no updates.

APPLE SUPPORT:
@138720 Thanks for taking the time to reach out. Yes, that notification is from Apple.

================================================================================
Example 15
Conversation: 103253

CUSTOMER:
@115858 The upgrade is messing up with FaceTime. I had to restart 4 times in one day because it freezes. Fix this please

APPLE SUPPORT:
@138722 We want to help. What device is the issue occurring on?

================================================================================
Example 16
Conversation: 104192

CUSTOMER:
Certainly. I’ll collect some screenshots to illustrate the problem and message you later.

APPLE SUPPORT:
@138973 Great, thanks.

================================================================================
Example 17
Conversation: 105315

CUSTOMER:
Anybody else having a problem uploading  screenshotted pictures from their #iphone? @115858

APPLE SUPPORT:
@139254 We'd be happy to help with your pictures. Provide us some details of what's going and we can work together from there.

================================================================================
Example 18
Conversation: 105323

CUSTOMER:
MY AIRPODS CASE WONT ChARGE WTF

APPLE SUPPORT:
@139257 We are here to help. Is it both that will not charge or just one?

================================================================================
Example 19
Conversation: 105334

CUSTOMER:
Thank you!

APPLE SUPPORT:
@117107 You're welcome and thank you! Contact us again if you have other concerns or questions. We'll be glad to help. Have a great day.

================================================================================
Example 20
Conversation: 105339

CUSTOMER:
Is there a way to prevent my Apple Car Play from automatically playing music from my iPhone? I've looked thru all the settings on my phone and in my car and have not found anything.

APPLE SUPPORT:
@139262 Thanks for reaching out. We'd like to know more to assist. Which iPhone model and iOS are you currently using?

================================================================================
Example 21
Conversation: 105353

CUSTOMER:
Thanks

APPLE SUPPORT:
@139267 No problem.

================================================================================
Example 22
Conversation: 105364

CUSTOMER:
Missing my voicemail on iOS11. It just says “call voicemail” what the hell....

APPLE SUPPORT:
@139270 This usually indicates that it needs to be set up. This would be best handled by your carrier.

================================================================================
Example 23
Conversation: 105409

CUSTOMER:
I work until 5 or so. I will dm you when I’m off.

APPLE SUPPORT:
@139283 Sounds good!

================================================================================
Example 24
Conversation: 105417

CUSTOMER:
@AppleSupport

APPLE SUPPORT:
@139285 We'd like to help! Tell us more please about what you're experiencing. Are you getting any error messages?

================================================================================
Example 25
Conversation: 10677

CUSTOMER:
just updated Apple Watch to 4.1. Is ESPN radio etc only available in USA, can’t get it on my watch in the UK

APPLE SUPPORT:
@117961 We want to help you. That station may not be available. Availability of live stations varies depending on your location.

================================================================================
Example 26
Conversation: 10687

CUSTOMER:
@115858 why everytime I️ type an “I️” this extra A and box pops up ??

APPLE SUPPORT:
@117965 Let's work on a solution together. To start, which device model and exact iOS version are you using?

================================================================================
Example 27
Conversation: 10687

CUSTOMER:
I figured it out thanks

APPLE SUPPORT:
@117965 Awesome! It's our pleasure. Feel free to reach out anytime a question comes up.

================================================================================
Example 28
Conversation: 10694

CUSTOMER:
why do I not have my October challenge ring after competition?

APPLE SUPPORT:
@117968 If you complete an achievement, but don't earn the award, you will earn the award within 9 days of completing the challenge.

================================================================================
Example 29
Conversation: 107346

CUSTOMER:
umm, why won’t my personal hotspot connect to my laptop? I’ve tried restarting my network settings on my iphone and restarting my laptop but it still doesn’t work. On my laptop, it says “the connection is limited”

APPLE SUPPORT:
@139841 We are here to help. Let's take a look at this. What is your cell coverage like? What is your current iOS version?

================================================================================
Example 30
Conversation: 107361

CUSTOMER:
hi apple! How am I supposed to enter my password when my number keyboard refuses to work? happening to me for a while now!

APPLE SUPPORT:
@139844 We'd love to help out. Do you know which Mac OS you're on?

In [91]:
# ============================================
# Cell 64 — Inspect potential failure cases
# ============================================

potential_failures = [
    pair
    for pair in clean_support_pairs
    if pair["response_quality"] == "generic_escalation"
]

print("Potential failure cases:", len(potential_failures))

for i, pair in enumerate(potential_failures[:50], start=1):

    print("\n" + "=" * 80)
    print(f"Example {i}")
    print("Conversation:", pair["conversation_id"])

    print("\nCUSTOMER:")
    print(pair["customer_message"])

    print("\nAPPLE SUPPORT:")
    print(pair["support_response"])

Potential failure cases: 503

================================================================================
Example 1
Conversation: 101241

CUSTOMER:
anyone else’s phone changing “it” to I.T

APPLE SUPPORT:
@138155 We've received your DM and will respond to you there shortly.

================================================================================
Example 2
Conversation: 101244

CUSTOMER:
Spam emails ....

APPLE SUPPORT:
@138156 Thank you for reaching out to us and providing us with this information. Please report this phishing message using the info here: https://t.co/LNMCdqt6fD

================================================================================
Example 3
Conversation: 101253

CUSTOMER:
please, since the last update 10.13.1, there is a huge delay in the refresh of the files in the Finder. Same problem was before but it was fixed in the previous version. Now, the problem appears again

APPLE SUPPORT:
@138160 We want to ensure we're able to get your Mac running as expected. Please meet us in DM with more information on the exact issue you're experiencing.

You can meet us in DM, here: https://t.co/GDrqU22YpT

================================================================================
Example 4
Conversation: 102363

CUSTOMER:
Dear , the feature that is suppose to keep Live Photos off doesn’t work. A fix would be nice. Thanks!

APPLE SUPPORT:
@138471 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 5
Conversation: 103157

CUSTOMER:
I deleted the download and re-downloaded the update and again, it says an error occured while installing

APPLE SUPPORT:
@138692 Let's meet up in DM and work together there. https://t.co/GDrqU22YpT

================================================================================
Example 6
Conversation: 103205

CUSTOMER:
I tried to recreate the issue with iTunes open and was unable to reproduce the effect. Thank you for your reply.

APPLE SUPPORT:
@138705 Got it, thank you. If it still occurs in Safari, please send us a DM. We'd like to continue working on this with you. https://t.co/GDrqU22YpT

================================================================================
Example 7
Conversation: 103218

CUSTOMER:
iOS 11.1.2 - it’s up to date

APPLE SUPPORT:
@138709 OK, thanks. So that we can look into this further, use the link below to DM us, and we’ll  take it from there. https://t.co/GDrqU22YpT

================================================================================
Example 8
Conversation: 104192

CUSTOMER:
Thanks. Yep I checked that, but neither phone has the other listed as an alternative data source. It’s almost like it’s because they’re both linked to my iCloud account or something. Here’s an example from one of them, the one listed is the same device name.

APPLE SUPPORT:
@138973 We'd like to look into this further. Please DM us to continue working on this. https://t.co/GDrqU22YpT

================================================================================
Example 9
Conversation: 105356

CUSTOMER:
Any comment on if restarting to factory settings then downloading all software then loading back up will do anything?

APPLE SUPPORT:
@139268 Let's meet in Direct Message to continue. https://t.co/GDrqU22YpT

================================================================================
Example 10
Conversation: 105386

CUSTOMER:
Brand New iPhoneX with GreenLine Achievement Unlocked ... Time to leave this Planet

APPLE SUPPORT:
@139276 We are sad to see those Photos, but we want to help with your new iPhone X. Please send us a DM, and we can continue. https://t.co/GDrqU22YpT

================================================================================
Example 11
Conversation: 105398

CUSTOMER:
How do I clear analytic data from my iPhone? (yes its turned off) but it's being stored anyways. Bad enough your os is 4gb.

APPLE SUPPORT:
@139279 We can offer some guidance on this. Use the link below to DM us, and we’ll take it from there. https://t.co/GDrqU22YpT

================================================================================
Example 12
Conversation: 105423

CUSTOMER:
Hi, how can I check my iPhone's battery health? Any way without going to an Apple Store?

APPLE SUPPORT:
@139288 We can definitely understand your concern. We would want to make sure our battery health is good too.  Let's partner together in DM and go from there. https://t.co/GDrqU22YpT

================================================================================
Example 13
Conversation: 10671

CUSTOMER:
/2...2 docs did open, duplicated themselves, now none open after I closed them.

APPLE SUPPORT:
@117959 Please send us a DM and we will go from there. https://t.co/GDrqU22YpT

================================================================================
Example 14
Conversation: 10681

CUSTOMER:
@115858 why is it impossible to Type “I” without a stupid box with a question mark. #notimpressed #fixit

APPLE SUPPORT:
@117963 We are here for you. Let's take a look at this further for you. Reach out to us in DM. https://t.co/GDrqU22YpT

================================================================================
Example 15
Conversation: 107348

CUSTOMER:
Went to apple store with call receiving issue with my iPhone. Their reply "1 to 2 call dropping per week is very standard. we can't do anything." That's the level of support you get from apple now a days.

APPLE SUPPORT:
@139259 That's certainly not the type of experience that we want you to go through. Please send us a DM of your current location and we'll look into this with you. https://t.co/GDrqU22YpT

================================================================================
Example 16
Conversation: 109018

CUSTOMER:
It is running incredibly slow after the new update

APPLE SUPPORT:
@140193 OK. Let's continue in DM. https://t.co/GDrqU22YpT

================================================================================
Example 17
Conversation: 109039

CUSTOMER:
The newest one

APPLE SUPPORT:
@140201 Got it. We've received your DM and you'll receive a response shortly to further assist you.

================================================================================
Example 18
Conversation: 109044

CUSTOMER:
Yes, yes,

APPLE SUPPORT:
@140202 Thanks for confirming that. Next, send us a DM and we'll take a closer look into this. https://t.co/GDrqU22YpT

================================================================================
Example 19
Conversation: 109056

CUSTOMER:
Same bug in my iPhone7 as in my iPhone5s: Volume increases without touching the buttons or the display? iOS11

APPLE SUPPORT:
@140206 We want you to have an enjoyable experience with your new phone. Let's hop in DM and continue there. Click here: https://t.co/GDrqU22YpT

================================================================================
Example 20
Conversation: 109068

CUSTOMER:
I have a problem with my iPhone. I typed the code too many times and now my device is disabled. If I set it to recovery mode and want to restore it, the iPhone won't be reset. I also can not use iTunes because I can not access the homescreen, what can i do?

APPLE SUPPORT:
@140209 Hi there! We've received your DMs and you can expect a response from us there shortly with a resolution.

================================================================================
Example 21
Conversation: 109093

CUSTOMER:
Totally disappointed in Talking to a lady on the phone who is full of attitude and isn’t helping my Mum at all!

APPLE SUPPORT:
@140214 That's not the experience we hope for you to have. Meet us in DM and let's see if there is something we can do to help here. https://t.co/GDrqU22YpT

================================================================================
Example 22
Conversation: 109767

CUSTOMER:
Done that and restarted my phone too but it still doesn’t help, my screen keeps freezing especially spanchat & google map. My keboard is become glitchy, my shortcuts have disappeared, what monster have you created

APPLE SUPPORT:
@140376 Let's look into this further. Please meet with us in DM to continue. https://t.co/GDrqU22YpT

================================================================================
Example 23
Conversation: 110869

CUSTOMER:
I’m on the latest version

APPLE SUPPORT:
@140657 We'd like to look into this further. Please DM us to continue working on this. https://t.co/GDrqU22YpT

================================================================================
Example 24
Conversation: 110884

CUSTOMER:
@AppleSupport

APPLE SUPPORT:
@140662 Hey there! We've received your DM and we'll be following up there shortly.

================================================================================
Example 25
Conversation: 110893

CUSTOMER:
@140666 @115858 @115888 For keyboard controls if something else claimed them first - eg a YouTube tab - it won’t work. If you launch Spotify first they should work. For spotlight, there’s a history of problems. Do you use multiple accounts? It used to do that for me but then I switched to just one.

APPLE SUPPORT:
@140665  We're here to help. DM us so we can look into this further with you. https://t.co/GDrqU22YpT

================================================================================
Example 26
Conversation: 110901

CUSTOMER:
how to transfer my Apple Watch on my new iPhone ? and for AirPods too pls

APPLE SUPPORT:
@140669 Hello. We can help. Please meet us in DM. https://t.co/GDrqU22YpT

================================================================================
Example 27
Conversation: 110935

CUSTOMER:
MacBook Air.2 years old. But never used. Tried to use it first time two weeks ago. Cursor uncontrollable. Service at Mangalore (Maple) says Track PAD defective. RS.10000 for replacement. Quite unfair as it is manufacturing defect.Replace free of cost

APPLE SUPPORT:
@140678 We'd like to look into this. Please DM us. https://t.co/GDrqU22YpT

================================================================================
Example 28
Conversation: 110957

CUSTOMER:
I have downloaded the update by using software update on the iPhone not through iTunes . The error message is "some error has occurred while installation "

APPLE SUPPORT:
@140682 We see your DM. We'll continue with you there.

================================================================================
Example 29
Conversation: 11096

CUSTOMER:
Well it froze as I was ordering a pizza so I had to. And now it’s already to 49%

APPLE SUPPORT:
@118093 We'd like to offer our help. Please shoot us a DM and we'll explore the battery challenge. https://t.co/GDrqU22YpT

================================================================================
Example 30
Conversation: 11101

CUSTOMER:
iPhone 7 and yes the software is up to date

APPLE SUPPORT:
@118095 We'd like to investigate with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT

================================================================================
Example 31
Conversation: 11118

CUSTOMER:
my watch has been saying I’ve been averaging 57 minutes, now today it’s 52, I checked and did the math it’s 57... what the???

APPLE SUPPORT:
@118099 We'd like to help. Let's take this to DM and we'll explore ways to provide you assistance. https://t.co/GDrqU22YpT

================================================================================
Example 32
Conversation: 11122

CUSTOMER:
6 plus, idk what iOS version.. and it was the rear facing camera

APPLE SUPPORT:
@118100 We'd like to gather more information. Let's meet in DM. https://t.co/GDrqU22YpT

================================================================================
Example 33
Conversation: 11144

CUSTOMER:
love how my computer charger just stopped working for literally no reason at all. thanks @115858 you’ve really done it for me this time, sweetie

APPLE SUPPORT:
@118108 We'd like to investigate with you. Send us a DM and we can troubleshoot more from there. https://t.co/GDrqU22YpT

================================================================================
Example 34
Conversation: 112850

CUSTOMER:
It just started today. I have the most up to date version of iOS.

APPLE SUPPORT:
@141085 Understood. Let's move to DM and we'll gather some more information. https://t.co/GDrqU22YpT

================================================================================
Example 35
Conversation: 112861

CUSTOMER:
When I call the 1-800 My iPhone, the recording states “Due to the holiday, we’re offering limited product support. You will need an extended hours agreement.”

APPLE SUPPORT:
@141089 We can definitely understand the confusion. We at this channel can help resolve your issue. Due to the holiday our phone support is closed for the day. If you would like to work with us, hit the DM link and we'll get started. https://t.co/GDrqU22YpT

================================================================================
Example 36
Conversation: 112878

CUSTOMER:
Done!

APPLE SUPPORT:
@141092 We've received your DM and will continue working with you there.

================================================================================
Example 37
Conversation: 112899

CUSTOMER:
Hello A friend of mine has trouble. He paid for a Swiss National Anthem file, sung by Red Army Choir: (Russian famous choir) and iTunes deleted the file from the library & iCloud. How it is possible? cc

APPLE SUPPORT:
@141098 Hey there! Thanks for reaching out to us about this. Shoot us a DM so we can get you pointed in the right direction. https://t.co/GDrqU22YpT

================================================================================
Example 38
Conversation: 112905

CUSTOMER:
iphone5s I want to go back to iOS 10. How? Battery draining can’t withstand 12hrs.

APPLE SUPPORT:
@141102 We want to be sure you get the most out of your battery life. Send us a DM so we can help you further. https://t.co/GDrqU22YpT

================================================================================
Example 39
Conversation: 112907

CUSTOMER:
I was just on SnapChat and my battery went EXACTLY from 79% then in a SPLIT SECOND it drops to 11% and shuts off DEAD. I would like to know why this hasn’t been fixed with the already several updates of iOS 11 having been released?

APPLE SUPPORT:
@141103 Thanks for reaching out. We're here to help. DM us so we can look into this further with you. https://t.co/GDrqU22YpT

================================================================================
Example 40
Conversation: 112909

CUSTOMER:
@115858 I thought y’all fixed this shit why does the damn A keep popping up

APPLE SUPPORT:
@141104 Hey there! This issue was addressed in a recent update. Let's have you backup and update and see if that resolves the issue. Check out this link if you need help with the backup: https://t.co/ui8Itz8ESg DM us if you're still having issues: https://t.co/GDrqU22YpT

================================================================================
Example 41
Conversation: 114457

CUSTOMER:
My brand new iPhone X won’t connect to ANY of my devices over bluetooth.

APPLE SUPPORT:
@141446 We'd like to help. Let's take this to DM and we'll explore ways to provide you assistance. https://t.co/GDrqU22YpT

================================================================================
Example 42
Conversation: 114459

CUSTOMER:
A recent upgrade to iOS 11.1.2 has made my phone so so slow . I hate it. It’s so laggy now

APPLE SUPPORT:
@141447 You've come to the right place for help. We can definitely look into this with you. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 43
Conversation: 114471

CUSTOMER:
Sadly, my #applewatch did not sync my 2 workouts with my phone today, so no turkey 🦃 achievement for me.  Anyone know what I did wrong? @115858

APPLE SUPPORT:
@141450 We'd like to help. Let's take this to DM and we'll explore ways to provide you assistance. https://t.co/GDrqU22YpT

================================================================================
Example 44
Conversation: 114473

CUSTOMER:
@115858 can we update these chargers pls https://t.co/I3SmgsOLeG

APPLE SUPPORT:
@141451 We're here to help. Send us a DM with your location so we can explore your service options. Support options differ by region. https://t.co/GDrqU22YpT

================================================================================
Example 45
Conversation: 114481

CUSTOMER:
Correct. I went to take a photo just now, and Live was set to on and flash to Auto even though they had both previously been turned off.

APPLE SUPPORT:
@141452 Please DM us to continue. Thank you. https://t.co/GDrqU22YpT

================================================================================
Example 46
Conversation: 114489

CUSTOMER:
Battery life awful, iOS 11.2, iPhone X

APPLE SUPPORT:
@141455 We’d love to help with your battery life. To start, please send us a DM. https://t.co/GDrqU22YpT

================================================================================
Example 47
Conversation: 114507

CUSTOMER:
Says the same thing.

APPLE SUPPORT:
@141457 We'd like to take a closer look at this with you. Reach out via DM using the link below. https://t.co/GDrqU22YpT

================================================================================
Example 48
Conversation: 114509

CUSTOMER:
After installing iOS 11.1.2 apple apps close such as Podcasts, while playing and also apps from other developers. iPhone also feels slow and it gets hot and battery is running lower than usual. ios1112

APPLE SUPPORT:
@141458 Let's look into that. Send us a DM and we'll go from there. https://t.co/GDrqU22YpT

================================================================================
Example 49
Conversation: 114512

CUSTOMER:
It’s the iPhone 6 and it’s ios 11.1.2

APPLE SUPPORT:
@141459 Alright. Let's continue to look further into this in DM: https://t.co/GDrqU22YpT

================================================================================
Example 50
Conversation: 115990

CUSTOMER:
@115858 why is this a Siri suggested website? https://t.co/P7SQKqRIpr

APPLE SUPPORT:
@141829 Let's look into this together. Please DM us. https://t.co/GDrqU22YpT

In [92]:
# ============================================
# Cell 65 — Prepare customer messages
# ============================================

customer_messages = [
    pair["customer_message"]
    for pair in clean_support_pairs
]

print("Customer messages available:", len(customer_messages))
print("Unique customer messages:", len(set(
    msg.strip().lower()
    for msg in customer_messages
)))

print("\nSample customer messages:")
print("=" * 70)

for i, message in enumerate(customer_messages[:20], start=1):
    print(f"{i}. {message}")

Customer messages available: 3092
Unique customer messages: 3023

Sample customer messages:
======================================================================
1. What is this ? since I upgraded with this $hi&*y macOS my instant click before is now lagging to almost a minute and that disrupts my writing e-mails (work and personal) wow! this is getting crazy everyday not enjoying Apple Macbook NOW!
2. I have tried restarting my macbook but it keeps lagging. I will try rebooting and close all apps once again.
3. My iPhone been moving slow af the past couple weeks. I need answers
4. Dear god not again,
5. Noticed a bug on my @115858 iPhone X/iOS 11.1.2 While I’m on the phone I can’t close apps.
6. leg dit even uit? Dit is mijn oud e-mail adress/apple id, sinds een recente update krijg ik constant deze melding. Ik heb sinds paar jaar een nieuw e-mail adres en ook een apple id op dit adres. Ik was (nog altijd) het wachtwoord kwijt van het oude e-mail & apple-id
7. Since a recent update i’m constantly getting these notifications about my old apple ID /e-mail adress, wich i’ve lost the pw years ago. I allready got a new account and e-mail, but it doesn’t appear anywhere, alltho i can still acces the app store etc..
8. Yes ofcourse, iphone 6s version 11.1.2 (15B202)
9. @115858 Just because you're releasing new phones doesn't mean you should stop making my current iPhone stop working. I have a contract and cannot just purchase a new phone every 12 months.
10. anyone else’s phone changing “it” to I.T
11. Spam emails ....
12. updated to iOS 11.1.2, phone crashes repeatedly at 32% battery life. Briefly flashes ‘plug in graphic’, the will restart and crash again within seconds. When drained past 30%, suddenly works fine. Something buggy with the low battery emergency shutdown trigger.
13. @115858 @116333 My Apple account’s Family Sharing has been broken for 10 weeks now, and support doesn’t seem any closer to fixing this. When asked for alternative solutions the answer is to have yet more patience. This is horrible :( https://t.co/1W9S7hFGwC
14. why is my MacBook doing this
15. please, since the last update 10.13.1, there is a huge delay in the refresh of the files in the Finder. Same problem was before but it was fixed in the previous version. Now, the problem appears again
16. please helpmeni can't sign in icloud account
17. I forget account and pasword icloud,
18. Only to break File Sharing! Sigh :-( /cc @115858 https://t.co/QGw2mX4igg
19. Why does the iPhone have “I.T” as the autocorrect for “it”??!
20. 11.0.3

In [93]:
# ============================================
# Cell 66 — Explore recurring intent keywords
# ============================================

from collections import Counter
import re

intent_keywords = {
    "performance": [
        "slow", "lag", "lagging", "freeze", "freezing",
        "crash", "crashes", "hang", "hanging"
    ],

    "battery": [
        "battery", "drain", "charging", "charge",
        "charger", "battery life"
    ],

    "update": [
        "update", "updated", "upgrading", "upgrade",
        "ios 11", "ios 10", "high sierra", "macos"
    ],

    "apple_id_icloud": [
        "apple id", "icloud", "i cloud",
        "account", "password", "sign in", "login"
    ],

    "keyboard_autocorrect": [
        "keyboard", "autocorrect", "auto correct",
        "typing", "type", "it", "i.t"
    ],

    "connectivity": [
        "wifi", "wi-fi", "bluetooth",
        "hotspot", "connect", "connection",
        "pairing", "paired"
    ],

    "audio": [
        "sound", "audio", "headphone",
        "headphones", "earphone", "earphones",
        "speaker"
    ],

    "display_touch": [
        "screen", "display", "touch",
        "brightness", "greenline"
    ],

    "apps": [
        "app", "apps", "itunes", "safari",
        "spotify", "facetime", "podcasts",
        "finder", "app store"
    ],

    "family_sharing": [
        "family sharing"
    ],

    "spam_security": [
        "spam", "phishing", "scam",
        "security", "fraud"
    ],

    "hardware": [
        "macbook", "iphone", "ipad",
        "apple watch", "airpods",
        "trackpad", "mouse", "camera"
    ]
}


keyword_counts = Counter()

for message in customer_messages:

    text = message.lower()

    for intent, keywords in intent_keywords.items():

        if any(keyword in text for keyword in keywords):
            keyword_counts[intent] += 1


print("Keyword-based intent signals")
print("=" * 60)

for intent, count in keyword_counts.most_common():

    percentage = count / len(customer_messages) * 100

    print(
        f"{intent:22s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Keyword-based intent signals
============================================================
keyboard_autocorrect  : 1664 (53.82%)
update                :  832 (26.91%)
apps                  :  832 (26.91%)
hardware              :  726 (23.48%)
performance           :  313 (10.12%)
battery               :  267 (8.64%)
display_touch         :  203 (6.57%)
connectivity          :  163 (5.27%)
apple_id_icloud       :  153 (4.95%)
audio                 :   62 (2.01%)
spam_security         :   34 (1.10%)
family_sharing        :    1 (0.03%)

In [94]:
# ============================================
# Cell 67 — Clean Intent Signal Analysis
# ============================================

intent_keywords_clean = {
    "performance": [
        "slow", "lag", "lagging", "freeze",
        "freezing", "crash", "crashes",
        "crashed", "hang", "hanging"
    ],

    "battery": [
        "battery", "battery life", "battery drain",
        "drain", "charging", "charger"
    ],

    "software_update": [
        "update", "updated", "upgrading",
        "upgrade", "ios 11", "ios 10",
        "ios 11.1", "macos", "high sierra"
    ],

    "apple_id_icloud": [
        "apple id", "icloud", "i cloud",
        "sign in", "login", "password",
        "forgot password"
    ],

    "keyboard_autocorrect": [
        "autocorrect", "auto correct",
        "keyboard", "typing", "typing issue"
    ],

    "connectivity": [
        "wifi", "wi-fi", "bluetooth",
        "hotspot", "pairing", "paired",
        "cannot connect", "can't connect",
        "connection"
    ],

    "audio": [
        "sound", "audio", "headphone",
        "headphones", "earphone",
        "earphones", "speaker"
    ],

    "display_touch": [
        "screen", "display", "touch",
        "brightness", "touchscreen"
    ],

    "apps_services": [
        "app store", "itunes", "safari",
        "facetime", "finder", "icloud drive",
        "photos app", "music app"
    ],

    "family_sharing": [
        "family sharing"
    ],

    "security_spam": [
        "spam email", "spam emails",
        "phishing", "scam", "fraud"
    ],

    "file_sharing": [
        "file sharing", "file sharing issue",
        "finder", "files"
    ]
}


keyword_counts_clean = Counter()

for message in customer_messages:

    text = message.lower()

    for intent, keywords in intent_keywords_clean.items():

        matched = False

        for keyword in keywords:

            # Exact phrase/word matching
            if " " in keyword:
                if keyword in text:
                    matched = True
                    break
            else:
                if re.search(r"\b" + re.escape(keyword) + r"\b", text):
                    matched = True
                    break

        if matched:
            keyword_counts_clean[intent] += 1


print("Cleaned keyword-based intent signals")
print("=" * 65)

for intent, count in keyword_counts_clean.most_common():

    percentage = count / len(customer_messages) * 100

    print(
        f"{intent:22s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Cleaned keyword-based intent signals
=================================================================
software_update       :  783 (25.32%)
battery               :  229 (7.41%)
display_touch         :  170 (5.50%)
performance           :  161 (5.21%)
apps_services         :  150 (4.85%)
apple_id_icloud       :  125 (4.04%)
connectivity          :  118 (3.82%)
keyboard_autocorrect  :   82 (2.65%)
audio                 :   59 (1.91%)
security_spam         :   10 (0.32%)
file_sharing          :    8 (0.26%)
family_sharing        :    1 (0.03%)

In [95]:
# ============================================
# Cell 68 — Initial Intent Assignment
# ============================================

def assign_initial_intent(text):
    text = text.lower()

    # 1. Account / iCloud
    if any(keyword in text for keyword in [
        "apple id",
        "icloud",
        "i cloud",
        "sign in",
        "login",
        "forgot password",
        "password"
    ]):
        return "account_icloud"

    # 2. Connectivity
    if any(keyword in text for keyword in [
        "wifi",
        "wi-fi",
        "bluetooth",
        "hotspot",
        "pairing",
        "paired",
        "cannot connect",
        "can't connect"
    ]):
        return "connectivity"

    # 3. Battery / power
    if any(keyword in text for keyword in [
        "battery",
        "battery life",
        "battery drain",
        "drain",
        "charging",
        "charger"
    ]):
        return "battery_power"

    # 4. Software / update
    if any(keyword in text for keyword in [
        "update",
        "updated",
        "upgrading",
        "upgrade",
        "ios 11",
        "ios 10",
        "macos",
        "high sierra"
    ]):
        return "software_update"

    # 5. Performance
    if any(keyword in text for keyword in [
        "slow",
        "lag",
        "lagging",
        "freeze",
        "freezing",
        "crash",
        "crashes",
        "crashed",
        "hang",
        "hanging"
    ]):
        return "performance"

    # 6. Apps / Apple services
    if any(keyword in text for keyword in [
        "app store",
        "itunes",
        "safari",
        "facetime",
        "finder",
        "photos app",
        "music app"
    ]):
        return "apps_services"

    # 7. Device hardware
    if any(keyword in text for keyword in [
        "screen",
        "display",
        "touch",
        "touchscreen",
        "brightness",
        "sound",
        "audio",
        "headphone",
        "headphones",
        "earphone",
        "earphones",
        "speaker"
    ]):
        return "device_hardware"

    # 8. Everything else
    return "other_support"


initial_intents = [
    assign_initial_intent(message)
    for message in customer_messages
]

intent_distribution = Counter(initial_intents)

print("Initial intent distribution")
print("=" * 65)

for intent, count in intent_distribution.most_common():

    percentage = count / len(initial_intents) * 100

    print(
        f"{intent:20s}: "
        f"{count:4d} "
        f"({percentage:.2f}%)"
    )

Initial intent distribution
=================================================================
other_support       : 1630 (52.72%)
software_update     :  653 (21.12%)
battery_power       :  224 (7.24%)
performance         :  147 (4.75%)
device_hardware     :  130 (4.20%)
account_icloud      :  127 (4.11%)
connectivity        :  110 (3.56%)
apps_services       :   71 (2.30%)

In [96]:
# ============================================
# Cell 69 — Inspect Initial "Other" Messages
# ============================================

other_messages = [
    message
    for message, intent in zip(customer_messages, initial_intents)
    if intent == "other_support"
]

print("Messages classified as other_support:", len(other_messages))
print("=" * 80)

for i, message in enumerate(other_messages[:100], start=1):
    print(f"{i}. {message}")
    print("-" * 80)

Messages classified as other_support: 1630
================================================================================
1. Dear god not again,
--------------------------------------------------------------------------------
2. Yes ofcourse, iphone 6s version 11.1.2 (15B202)
--------------------------------------------------------------------------------
3. @115858 Just because you're releasing new phones doesn't mean you should stop making my current iPhone stop working. I have a contract and cannot just purchase a new phone every 12 months.
--------------------------------------------------------------------------------
4. Spam emails ....
--------------------------------------------------------------------------------
5. @115858 @116333 My Apple account’s Family Sharing has been broken for 10 weeks now, and support doesn’t seem any closer to fixing this. When asked for alternative solutions the answer is to have yet more patience. This is horrible :( https://t.co/1W9S7hFGwC
--------------------------------------------------------------------------------
6. why is my MacBook doing this
--------------------------------------------------------------------------------
7. Only to break File Sharing! Sigh :-( /cc @115858 https://t.co/QGw2mX4igg
--------------------------------------------------------------------------------
8. Why does the iPhone have “I.T” as the autocorrect for “it”??!
--------------------------------------------------------------------------------
9. 11.0.3
--------------------------------------------------------------------------------
10. Alguien sabe pxq le pasa esto a mi nuevo iPhone X ese cuadro q?
--------------------------------------------------------------------------------
11. yo what’s your phone number
--------------------------------------------------------------------------------
12. Hey could you make it more impossible and frustrating to get a Genius Bar Reservation for an elderly person? Ridiculous.
--------------------------------------------------------------------------------
13. Anybody else getting really annoyed with trying to type “it” and constantly having it autocorrect to I.T ???? What’s good with that @115858 ???
--------------------------------------------------------------------------------
14. MY PHONE IS UNLOCKED SO WHY CAN'T I VIEW MY NOTIFICATIONS iOS11
--------------------------------------------------------------------------------
15. Nothing happens. iOS11.1.2. iPhone 7.
--------------------------------------------------------------------------------
16. happened multiple times over 3-4 weeks. even after restarting. can't seem to replicate the scenario though.
--------------------------------------------------------------------------------
17. As I said I can't recreate the scenario but it happens once every week or so
--------------------------------------------------------------------------------
18. is it possible to make an appointment for someone else? My sister is locked out of her account and her iPhone is dead so she can’t receive the code.
--------------------------------------------------------------------------------
19. how do I go about raising a high level complaint please? 4 senior techs couldn’t help fix my problem, now my e mails are being unanswered, want a refund for a product that’s not fit for purpose, have tried everything to fix, thanks.
--------------------------------------------------------------------------------
20. Dear , the feature that is suppose to keep Live Photos off doesn’t work. A fix would be nice. Thanks!
--------------------------------------------------------------------------------
21. CAN I PLEASE TALK TO A REAL PERSON, and not an automated voice? I've been on hold for 45 mins, got hung up on. I need your HELP LIKE NOW!!
--------------------------------------------------------------------------------
22. Omg yesss thank you !!!!
--------------------------------------------------------------------------------
23. I need your help!!
--------------------------------------------------------------------------------
24. Via my iPhone because I no longer have a computer
--------------------------------------------------------------------------------
25. @115858 iPhone X orange camera problem? https://t.co/HooDTPyYNl
--------------------------------------------------------------------------------
26. Hey - Over the last few days my messages app on my iMac and MBA stopped syncing with my iMessages from my iOS devices. Any ideas on how to fix this problem? I've lost one of my favorite parts of AppleSimplicity
--------------------------------------------------------------------------------
27. Yes they are. My iPad is as well and that one is still working normally.
--------------------------------------------------------------------------------
28. All is correct there.
--------------------------------------------------------------------------------
29. Zouden jullie mij uit kunnen leggen waarom mijn telefoon ineens geen geheugenruimte meer over heeft terwijl ik er al van alles heb afgegooid? En dit tot grote ergernis blijft doen?
--------------------------------------------------------------------------------
30. It’s not that. It’s because there’s many possible inference vision to the face. Like hands on face and other objects.
--------------------------------------------------------------------------------
31. @115858  thanks for making my phone backup fucking useless, cant download it back onto my phone because of a shitty ''two-factior verification' with my fucking old number, load a shite
--------------------------------------------------------------------------------
32. 11.2
--------------------------------------------------------------------------------
33. dont understand why i just called you to have my phone not working stilll.... thanks so much
--------------------------------------------------------------------------------
34. Yo @115858 you can make my phone not send/receive texts all you want I’m not buying your overpriced piece of glass #CanYouHearMeNow
--------------------------------------------------------------------------------
35. apple. ones you get when you get a new phone.
--------------------------------------------------------------------------------
36. @116333 Please help me, apple call centre in India unable to support
--------------------------------------------------------------------------------
37. Yo my iPhone just went from 100% to 20% in an hour.
--------------------------------------------------------------------------------
38. @138713 Estou com problemas com a querida @115858 tbem e tive que acionar o Procon.
--------------------------------------------------------------------------------
39. Are you guys kidding with these keyboard bugs?? I.T is so frustrating. Android is looking very tempting and be been an Apple user for YEARS. Is there a timeframe for a fix? Published workarounds don’t work!
--------------------------------------------------------------------------------
40. @115858 Estoy muy decepcionado con la calidad de la compra online. Despues de esperar tanto tiempo para el IPhone X + AppleWatch teneis problemas con el sistema de pago. Muy muy decepcionado !!! Espero que esto no afecte a la fecha de entrega de mi pedido!!!
--------------------------------------------------------------------------------
41. Err um. when are we gonna fix the issue with all my I’s looking like trash
--------------------------------------------------------------------------------
42. Why did all my pictures just delete from my phone. WTF just happened
--------------------------------------------------------------------------------
43. They came back thanks.
--------------------------------------------------------------------------------
44. Hey is this a known bug that will be fixed soon? My dock on iPad continues to not stay centered and only a reboot will reset it. See attached picture.
--------------------------------------------------------------------------------
45. 11.1.2
--------------------------------------------------------------------------------
46. hey @115858 fix the damn iOS so my phone stops freaking out. you want people to pay $1000 for a phone that has bugs?! it just deleted my entire yahoo inbox and now it’s downloading them again. all 8000! 😡
--------------------------------------------------------------------------------
47. MY AIRPODS CASE WONT ChARGE WTF
--------------------------------------------------------------------------------
48. Dear WTF is up with inserting A? When I type I in a text fix this
--------------------------------------------------------------------------------
49. Such rude folks in apple store as if they have done favors by selling iPhone  @116333 @6126 #iPhoneSucks #AppleCareSucks
--------------------------------------------------------------------------------
50. Thank you!
--------------------------------------------------------------------------------
51. @115858 I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ I️ .... when are you going to fix this!?
--------------------------------------------------------------------------------
52. Is there a way to prevent my Apple Car Play from automatically playing music from my iPhone? I've looked thru all the settings on my phone and in my car and have not found anything.
--------------------------------------------------------------------------------
53. why tf do i pay $800 for a fucking phone that always has problems. @115858
--------------------------------------------------------------------------------
54. porque me pasa esto a mi??
--------------------------------------------------------------------------------
55. Thanks
--------------------------------------------------------------------------------
56. Any comment on if restarting to factory settings then downloading all software then loading back up will do anything?
--------------------------------------------------------------------------------
57. iPhone don’t even need to fix that letter i glitch anymore, I️ see a question box and I️ already know what It is smh... y’all takin forever @115858
--------------------------------------------------------------------------------
58. Missing my voicemail on iOS11. It just says “call voicemail” what the hell....
--------------------------------------------------------------------------------
59. Ok thanks - yes I have that - I hadn’t opened it but I’ll follow along and get back to you.
--------------------------------------------------------------------------------
60. When you turn it off from the settings it says “off” and does not connect randomly. If you turn it off from the control centre it says “not connected” in the settings and connects sometimes randomly.
--------------------------------------------------------------------------------
61. Brand New iPhoneX with GreenLine Achievement Unlocked ... Time to leave this Planet
--------------------------------------------------------------------------------
62. El caos post bug root de @115858

- MBP sin parchear.
- El bug NO funciona (se supone por por actualización oculta).
- El parche aparece en actualizaciones.

¿Que hago? ¿Instalo o no instalo? https://t.co/NCVbKLo6nd
--------------------------------------------------------------------------------
63. How do I clear analytic data from my iPhone? (yes its turned off) but it's being stored anyways. Bad enough your os is 4gb.
--------------------------------------------------------------------------------
64. Why is every picture I take with my iphoneX with flash on, I get red eyes??? I never had this issue with my previous iphone help
--------------------------------------------------------------------------------
65. I did that. It just keeps turning itself back on whenever it chooses.
--------------------------------------------------------------------------------
66. I work until 5 or so. I will dm you when I’m off.
--------------------------------------------------------------------------------
67. my 7 plus is failing when I send pics to droids or iMessage. iMessage is on. It was fine yesterday. I’ve restarted the phone.
--------------------------------------------------------------------------------
68. @AppleSupport
--------------------------------------------------------------------------------
69. how do i make a service complaint?? Disappointed in my service for my repair
--------------------------------------------------------------------------------
70. 4 days ago.
--------------------------------------------------------------------------------
71. Ok, @ATT and @115858 figure your collective shit out. The error when attempting to type “I am” &amp; getting weird ASCII characters is stoopid.
--------------------------------------------------------------------------------
72. So, since updating the latest iOS, Pages no longer lets me open any docs, all show, just don’t open. Suggestions? Anyone?
--------------------------------------------------------------------------------
73. /2...2 docs did open, duplicated themselves, now none open after I closed them.
--------------------------------------------------------------------------------
74. Depois da ultima atualizado do IOS a bateria do IPhone 6 tá durando quase nada
--------------------------------------------------------------------------------
75. @115858 why is it impossible to Type “I” without a stupid box with a question mark. #notimpressed #fixit
--------------------------------------------------------------------------------
76. Baje la App de la cual es gratuita y me llego un cargo de $18.11 Pesos ¿cuál es el motivo?
--------------------------------------------------------------------------------
77. @115858 why everytime I️ type an “I️” this extra A and box pops up ??
--------------------------------------------------------------------------------
78. I figured it out thanks
--------------------------------------------------------------------------------
79. why do I not have my October challenge ring after competition?
--------------------------------------------------------------------------------
80. Well it is now 11 days after and still no sign of it
--------------------------------------------------------------------------------
81. My phone just died on 42%. No joke.
--------------------------------------------------------------------------------
82. where do we forward fake Apple emails?
--------------------------------------------------------------------------------
83. I’m using Tri 4G LTE (Indonesia), my ios is the latest one, 11.1.2. My friend is using the same provider and it works for her
--------------------------------------------------------------------------------
84. Went to apple store with call receiving issue with my iPhone. Their reply "1 to 2 call dropping per week is very standard. we can't do anything." That's the level of support you get from apple now a days.
--------------------------------------------------------------------------------
85. yes, I'm on 10.11.6. It's only doing this for numbers from 1 to 9, times to times.
--------------------------------------------------------------------------------
86. my app suddenly is not working
--------------------------------------------------------------------------------
87. I have done so, but still same issues
--------------------------------------------------------------------------------
88. Thanks for the help! It’s working
--------------------------------------------------------------------------------
89. please help I can’t retrieve a song I downloaded!
--------------------------------------------------------------------------------
90. Hey, / / , Why you lyin’?
--------------------------------------------------------------------------------
91. ?
--------------------------------------------------------------------------------
92. Apple turkey organization can not solve a problem in 3 months @115858
--------------------------------------------------------------------------------
93. can you tell me what other is and why it’s taking up ALL OF MY STORAGE
--------------------------------------------------------------------------------
94. 11.1.2
--------------------------------------------------------------------------------
95. okay basically i deleted vsco so i could delete all the pics and i re downloaded it so it takes up less space, AND NOW IT REFUSES TO GO BACK INTO THE FOLDER @115858 fix it
--------------------------------------------------------------------------------
96. The newest one
--------------------------------------------------------------------------------
97. Yes, yes,
--------------------------------------------------------------------------------
98. why have you taken my Apple subscription twice within two days?
--------------------------------------------------------------------------------
99. Do I have to buy an iPhone 8 directly from Apple to be eligible for AppleCare+ or can I buy the phone separately and add AC+ afterwards, as long as it's within 60 days of my purchase?
--------------------------------------------------------------------------------
100. Thank you very much!
--------------------------------------------------------------------------------

In [97]:
# Cell 47 — Save reconstructed conversation dataset

import os

os.makedirs("../data/processed", exist_ok=True)

conversation_df.to_csv(
    "../data/processed/conversation_df.csv",
    index=False
)

print("Saved conversation dataset successfully.")
print("Rows:", len(conversation_df))
print("Columns:", len(conversation_df.columns))
print("File: ../data/processed/conversation_df.csv")

Saved conversation dataset successfully.
Rows: 6836
Columns: 16
File: ../data/processed/conversation_df.csv

In [98]:
# Cell 56 — Save cleaned customer-support pairs

support_pairs_df = pd.DataFrame(clean_support_pairs)

support_pairs_df.to_csv(
    "../data/processed/support_pairs.csv",
    index=False
)

print("Saved support pairs successfully.")
print("Rows:", len(support_pairs_df))
print("Columns:", len(support_pairs_df.columns))
print("File: ../data/processed/support_pairs.csv")

Saved support pairs successfully.
Rows: 3092
Columns: 7
File: ../data/processed/support_pairs.csv